// Generates supabase/seed.sql from the current MOUNTAINS + ROUTES in ClimbMatch.jsx.
// Run: node supabase/gen-seed.cjs
const fs = require("fs");
const path = require("path");
const SRC = path.join(__dirname, "..", "ClimbMatch.jsx");
const OUT = path.join(__dirname, "seed.sql");
const txt = fs.readFileSync(SRC, "utf8");

function arrayLiteral(name) {
  const s = txt.indexOf("const " + name + "=[");
  const open = txt.indexOf("[", s);
  let d = 0, i = open;
  for (; i < txt.length; i++) { if (txt[i] === "[") d++; else if (txt[i] === "]") { d--; if (d === 0) { i++; break; } } }
  return new Function("return (" + txt.slice(open, i) + ")")();
}
const MOUNTAINS = arrayLiteral("MOUNTAINS");
const ROUTES = arrayLiteral("ROUTES");

// ── SQL value helpers ──
const q = v => v == null ? "null" : "'" + String(v).replace(/'/g, "''") + "'";
const num = v => (v == null || isNaN(v)) ? "null" : String(v);
const arr = v => (!v || !v.length) ? "null" : "ARRAY[" + v.map(q).join(",") + "]::text[]";
const json = v => (v == null) ? "null" : "'" + JSON.stringify(v).replace(/'/g, "''") + "'::jsonb";

// ── grade system + normalized number (mirrors the app's logic) ──
function gradeSystem(disc) {
  if (disc === "bouldering") return "v";
  if (["scrambling", "mountaineering", "hiking"].includes(disc)) return "class";
  if (["trad", "sport", "alpine", "rock"].includes(disc)) return "yds";
  if (disc === "ice") return "wi";
  if (disc === "mixed") return "m";
  if (disc === "aid") return "aid";
  return null;
}
function gradeNum(g, sys) {
  if (!g) return null;
  if (sys === "yds") { const m = g.match(/5\.(\d+)([a-d]?)/); return m ? parseInt(m[1]) + ("abcd".indexOf(m[2]) + 1) / 4 : null; }
  if (sys === "v")   { const m = g.match(/V(\d+)/);  return m ? parseInt(m[1]) : null; }
  if (sys === "wi")  { const m = g.match(/WI(\d+)/); return m ? parseInt(m[1]) : null; }
  if (sys === "m")   { const m = g.match(/M(\d+)/);  return m ? parseInt(m[1]) : null; }
  if (sys === "class"){ const m = g.match(/Class\s*(\d)/i); return m ? parseInt(m[1]) : null; }
  if (sys === "aid") { const m = g.match(/[AC](\d)/); return m ? parseInt(m[1]) : null; }
  return null;
}
function avgStars(r) {
  const a = (r.activity || []).map(x => x && x.stars).filter(x => x != null);
  return a.length ? +(a.reduce((s, x) => s + x, 0) / a.length).toFixed(2) : null;
}

// ── topological order: parents before children (path trigger needs the parent) ──
const byId = {}; MOUNTAINS.forEach(m => byId[m.id] = m);
const ordered = []; const seen = new Set();
function emit(m) {
  if (seen.has(m.id)) return;
  if (m.parentId && byId[m.parentId] && !seen.has(m.parentId)) emit(byId[m.parentId]);
  seen.add(m.id); ordered.push(m);
}
MOUNTAINS.forEach(emit);

const lines = [];
lines.push("-- AUTO-GENERATED by supabase/gen-seed.cjs from ClimbMatch.jsx. Do not edit by hand.");
lines.push("-- Apply AFTER 0001_areas_routes.sql. Order matters (parents before children).");
lines.push("begin;");
lines.push("");
lines.push("-- areas");
ordered.forEach(m => {
  lines.push(`insert into areas (id,name,parent_id,area_type,region,lat,lng,elevation,avy_zone,blurb,source) values (` +
    [q(m.id), q(m.name), q(m.parentId), q(m.areaType), q(m.region), num(m.lat), num(m.lng), num(m.elevation), q(m.avyZone), q(m.blurb), q("seed")].join(",") + `);`);
});
lines.push("");
lines.push("-- routes");
ROUTES.forEach(r => {
  const sys = gradeSystem(r.discipline);
  const gear = (r.cams || r.rack || r.gearTiers) ? { cams: r.cams, rack: r.rack, gearTiers: r.gearTiers } : null;
  const lenM = r.routeFt != null ? Math.round(r.routeFt * 0.3048) : null;
  lines.push(`insert into routes (id,area_id,name,discipline,grade,grade_system,grade_num,pitches,length_m,sort_order,stars,aspect,season,description,gear,verif,source) values (` +
    [q(r.id), q(r.mountainId), q(r.name), q(r.discipline), q(r.grade), q(sys), num(gradeNum(r.grade, sys)),
     num(r.pitches), num(lenM), num(r.sortOrder), num(avgStars(r)), q(r.aspect), q(r.season),
     q(r.blurb || r.summary), json(gear), json(r.verif), q("seed")].join(",") + `);`);
});
lines.push("");
lines.push("commit;");
lines.push("");
lines.push("-- sanity: every route landed on a leaf, and counts aggregated up");
lines.push("-- select id, route_count from areas where parent_id is null;  -- expect total = " + ROUTES.length);

fs.writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`Wrote ${OUT}: ${ordered.length} areas, ${ROUTES.length} routes.`);
