-- Comprehensive Alpine Trailhead Enrichment (Phase 2) - EXACT ID MATCHING
-- 16 thin WA alpine routes with complete trailhead documentation
-- Generated with precise route ID matching from database
-- Run in Supabase SQL Editor

BEGIN TRANSACTION;

-- Fuhrer Thumb
-- Peak: Mount Rainier | Trailhead: Paradise
UPDATE routes
SET approach_logistics = '{"trailhead": "Paradise", "trailheadDirection": "South-southwest from trailhead via Nisqually Moraine descent to Nisqually Glacier, cross glacier westward, ascend Wilson Gully/Wilson Bench/Wilson Chute on west side of glacier to Lower Castle camp, then continue northwest to Fuhrer Thumb couloir", "trailheadLat": 46.8529, "trailheadLng": -121.76047, "peakLat": 46.852825, "peakLng": -121.7604876}'::jsonb, approach = 'South-southwest from trailhead via Nisqually Moraine descent to Nisqually Glacier, cross glacier westward, ascend Wilson Gully/Wilson Bench/Wilson Chute on west side of glacier to Lower Castle camp, then continue northwest to Fuhrer Thumb couloir', dist_km = 8, gain_ft = 3599, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '4.5'), beta = 'Grade II alpine climb (50° snow/ice couloir); 5-7 hours summit day from camp (~9,000 ft); requires prior glacier travel experience, cramponing on firm ice, two ice tools competency; hazards include ice fall from Kautz Ice Cliff, rockfall, avalanche danger (early start essential), crevasses on Wilson and Nisqually Glaciers; best season June-September; technical skills: rope team travel, secure belay placement, avalanche awareness', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Mount Rainier National Park climbing permit required ($82 per person through Pay.gov); registration through Recreation.gov mandatory for summit attempts; Paradise parking available year-round; wilderness permit ($10 per person per night, $6 transaction fee); entrance fees waived for nonresidents in 2026; typical season closure November-May due to snow; storms possible June-September"')
WHERE id = 'wa_mount_rainier_fuhrer_thumb';

-- Disappointment Cleaver / Sitkum Glacier
-- Peak: Glacier Peak | Trailhead: North Fork Sauk River Trailhead
UPDATE routes
SET approach_logistics = '{"trailhead": "North Fork Sauk River Trailhead", "trailheadDirection": "From Darrington, south on Mountain Loop Highway (~10 miles to gravel section), continue 8 miles on gravel, turn left on Sloan Creek Road (FS 49), drive 6.6 miles to trailhead parking", "trailheadLat": 48.05946, "trailheadLng": -121.28903, "peakLat": 48.1097, "peakLng": -121.1117}'::jsonb, approach = 'From Darrington, south on Mountain Loop Highway (~10 miles to gravel section), continue 8 miles on gravel, turn left on Sloan Creek Road (FS 49), drive 6.6 miles to trailhead parking', dist_km = 14.5, gain_ft = 4501, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '8'), beta = 'Grade: Grade I Glacier / 3rd-4th Class Rock. Hike North Fork Sauk River Trail 5 miles to Mackinaw Shelter, ascend steeply 3 miles to White Pass (5,900 ft), follow Disappointment Cleaver north toward summit. Final climb involves 3rd-4th class scrambling over Disappointment Peak (8,500-9,700 ft) with some loose/chossy rock, or bypass via upper Gerdine and Cool Glaciers. Hazards: Loose rock, crevasses (if taking glacier alternative), avalanche terrain on adjacent Cool Glacier, navigation challenges in fog, high winds (30+ mph at summit), rockfall.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Northwest Forest Pass required ($5 day pass or $30 annual). Wilderness permits are self-issuing and free at trailhead. No special climbing permits needed. Peak camping is available at Mackinaw Shelter. Season: May-October (July recommended for best weather and lowest avalanche danger). Contact: Darrington Ranger District, (360) 436-1155."')
WHERE id = 'wa_glacier_peak_disappointment_cleaver';

-- King Kong - Gorillas Direct Direct
-- Peak: Mount Stuart | Trailhead: Stuart Lake Trailhead
UPDATE routes
SET approach_logistics = '{"trailhead": "Stuart Lake Trailhead", "trailheadDirection": "Southwest via Stuart Lake Trail (#1599); from Leavenworth, take Icicle Creek Road 8.4 miles, turn left onto FR 7601, continue 3.7 miles to trailhead. From Stuart Lake (4.5 miles, 1,665 ft gain), continue west along lake shore through trees to open fields below North Face, then traverse south and approach West Face Wall where King Kong route begins", "trailheadLat": 47.5277, "trailheadLng": -120.821, "peakLat": 47.4751, "peakLng": -120.9031}'::jsonb, approach = 'Southwest via Stuart Lake Trail (#1599); from Leavenworth, take Icicle Creek Road 8.4 miles, turn left onto FR 7601, continue 3.7 miles to trailhead. From Stuart Lake (4.5 miles, 1,665 ft gain), continue west along lake shore through trees to open fields below North Face, then traverse south and approach West Face Wall where King Kong route begins', dist_km = 7.2, gain_ft = 1663, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '4.5'), beta = 'Grade: IV 5.11+ alpine rock climb (5.12a on some topos). Route length: 900 feet (8 pitches) on West Face Wall. First ascent: September 9, 2016 by Sol Wertkin and Jon Gleason. Route climbs first 4 pitches of Gorillas in the Mist, moves left onto Gorillas Direct (2 pitches), then climbs 2-pitch direct finish up aesthetic splitter crack on overhanging headwall (5.11d crux). Connector pitch (5.10b): roof bulge, stem-box, runout overhanging jug climbing. Headwall pitch (5.11d): slabby steps, vertical features, meaty hand/fist jams, wild layback sequences. Required gear: double rack cams/nuts (small-medium), two fixed nuts at headwall top. Best season: late summer through early September (before fall storms and snow). Hazards: significant runouts between protection placements, loose rock with hidden chock stones, 30+ meters of overhanging exposure on headwall, alpine weather exposure risk (unplanned bivy possible).', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Permits: America the Beautiful Pass or Northwest Forest Pass required. Backcountry camping permit required for overnight stays (online application with fee). Enchantments area requires Recreation.gov permit for May 15–October 31. Road access: FR 7601 closes during winter (typically November–May). Parking: 20–30 car spaces with toilet at Stuart Lake trailhead. Dogs not allowed in Stuart Lake area."')
WHERE id = 'wa_king_kong_gorillas_direct_direct';

-- South Headwall
-- Peak: Mount Stuart | Trailhead: Esmeralda Basin Trailhead
UPDATE routes
SET approach_logistics = '{"trailhead": "Esmeralda Basin Trailhead", "trailheadDirection": "Northeast via Longs Pass Trail #1229 and Ingalls Way Trail #1390; ascend first major clearing west of Ulrich''s Couloir", "trailheadLat": 47.4367, "trailheadLng": -120.9369, "peakLat": 47.4773, "peakLng": -120.9022}'::jsonb, approach = 'Northeast via Longs Pass Trail #1229 and Ingalls Way Trail #1390; ascend first major clearing west of Ulrich''s Couloir', dist_km = 9.2, gain_ft = 5009, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '1.92'), beta = '5.8 YDS / VI- UIAA Grade II Alpine. 5 pitches trad climbing with 4–5 technical pitches. Two 20–30 ft sections of 5.7; extensive 4th–5th class scrambling. Hazards: frequent rockfall, loose rock/choss, exposure, early-season snow/ice. Requires cams, stoppers, long slings. Best June–August (peak July); avoid late season. First Ascent: Myhre & Sorenson (1966).', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Northwest Forest Pass required ($5/day or $30/annual). Free self-issuing wilderness permits at trailhead. Overnight permits required May 15–October 31 (advance booking). Limited parking; full in summer. Teanaway River Road may close until June. Located in Okanogan-Wenatchee National Forest."')
WHERE id = 'wa_south_headwall';

-- Liberty Traverse
-- Peak: Liberty Bell Mountain | Trailhead: Blue Lake Trailhead
UPDATE routes
SET approach_logistics = '{"trailhead": "Blue Lake Trailhead", "trailheadDirection": "South side of Highway 20, 1 mile west of Washington Pass overlook; from trailhead follow Blue Lake Trail 1.5 miles to climber''s trail junction", "trailheadLat": 48.53, "trailheadLng": -120.668, "peakLat": 48.51548, "peakLng": -120.65874}'::jsonb, approach = 'South side of Highway 20, 1 mile west of Washington Pass overlook; from trailhead follow Blue Lake Trail 1.5 miles to climber''s trail junction', dist_km = 3.2, gain_ft = 2001, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '2.5'), beta = 'Grade V alpine, 5.9 YDS, 26 pitches, approximately 2,000 ft (606 m) of climbing. Route composition: Beckey Route on Liberty Bell (5.3-5.6), North Face of Concord Tower, North Face of Lexington Tower, Northwest Corner of North Early Winter Spire (5.9+), Southwest Rib of South Early Winter Spire. Hazards include significant rockfall danger in approach gully ("bowling alley for rocks"), exposed alpine terrain, route finding challenges. Requires excellent trad climbing skills, solid alpine rock climbing experience, and good protection/anchor placement ability. Standard rack with couple bigger pieces for North Early Winter Spire. Short rappel descent from summits. Popular route—expect crowds on weekends. Best season: July-August during optimal weather windows. Typically done as 1-2 day alpine climb with experienced parties.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Northwest Forest Pass required for parking. Parking at Blue Lake Trailhead on south side of SR 20, 1 mile west of Washington Pass. No additional permit requirements for climbing. Summer climbing season (mid-June through September). Early alpine start recommended to avoid afternoon rockfall and crowds."')
WHERE id = 'wa_liberty_traverse';

-- Wright-Pond
-- Peak: Cutthroat Creek Wall / Little Liberty Bell | Trailhead: Cutthroat Creek Trailhead
UPDATE routes
SET approach_logistics = '{"trailhead": "Cutthroat Creek Trailhead", "trailheadDirection": "From Winthrop, drive west on SR-20 for approximately 28 miles (4.5 miles east of Washington Pass). Turn right on Forest Service Road 400 and follow for 1 mile to the trailhead parking area on the left side of the road.", "trailheadLat": 48.556, "trailheadLng": -120.654, "peakLat": 48.54975, "peakLng": -120.6435}'::jsonb, approach = 'From Winthrop, drive west on SR-20 for approximately 28 miles (4.5 miles east of Washington Pass). Turn right on Forest Service Road 400 and follow for 1 mile to the trailhead parking area on the left side of the road.', dist_km = 2.5, gain_ft = 1312, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '1.25'), beta = '4-pitch trad climbing route graded 5.11a/b (also 6c/23/VIII-/E3 in other systems). Granite climbing on Cutthroat Creek Wall. From parking, hike approximately 1/4 mile on old roadbed, look for cairns marking left turn uphill. Bushwhack through woods with no trail, gaining elevation quickly. Traverse leftward in open forest and on slabby benches to reach shoulder at base of wall''s right-hand side. Expect lichen and loose rock (newer route, FA October 4, 2010). Trad protection: doubles from tips to #2 plus single #3 and #4 cams. Early season may have snow/ice hazards. Rock is granite of good quality.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Northwest Forest Pass or America the Beautiful Pass required ($5/day or $30 annually). Digital payment only via recreation.gov mobile app. Parking lot fills quickly, especially mid-season. Vault toilet available. No overnight parking allowed. FS-400 is semi-paved with potholes; navigate with caution. Highway 20 closed in winter, typically reopens by early June. Best season: late June through late September."')
WHERE id = 'wa_wright_pond';

-- Thin Red Line
-- Peak: Liberty Bell Mountain | Trailhead: Washington Pass East Face Trailhead (Pond Approach)
UPDATE routes
SET approach_logistics = '{"trailhead": "Washington Pass East Face Trailhead (Pond Approach)", "trailheadDirection": "From Highway 20 hairpin curve on east side of Washington Pass, locate small pond on south side of road; trailhead pullout on north side of highway; follow climbers'' path marked with cairns from pond eastward into forest", "trailheadLat": 48.5245, "trailheadLng": -120.6581, "peakLat": 48.5154, "peakLng": -120.6579}'::jsonb, approach = 'From Highway 20 hairpin curve on east side of Washington Pass, locate small pond on south side of road; trailhead pullout on north side of highway; follow climbers'' path marked with cairns from pond eastward into forest', dist_km = 1.6, gain_ft = 1312, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '1'), beta = 'Grade: 5.12 (YDS), Grade IV overall. 11 pitches, approximately 1,100 feet of climbing. Route follows intricate crack systems and faces on East Face of Liberty Bell. Hazards: significant rock fall danger in approach gully (described as "party-induced rock fall bowling alley"); loose rock throughout approach; exposed alpine terrain; weather exposure on big wall. Required skills: advanced alpine rock climbing, 5.11+ crack climbing, self-rescue, anchor building, multi-pitch experience. First ascent: 1967 (aid climbing); free ascent variation established 2008 by Mikey Schaefer. Best season: June-September; July-September strongly preferred (late June requires ice axe, crampons). Notable: route features substantial fixed gear on most pitches; descent via two-rope rappel from M&M Ledge or summit traverse.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Northwest Forest Pass required for parking. Seasonal access: optimal late June through September (approach gully snow-filled until late June, autumn storms typically arrive in October). Parking: small pullout on north side of Highway 20 just east of Washington Pass near pond. Day permits available via Recreation.gov app ($5)."')
WHERE id = 'wa_liberty_bell_thin_red_line';

-- Northeast Ridge (1963 Route)
-- Peak: Johannesburg Mountain | Trailhead: Cascade Pass Trailhead
UPDATE routes
SET approach_logistics = '{"trailhead": "Cascade Pass Trailhead", "trailheadDirection": "East/Northeast from Cascade Pass trailhead; descend and cross Cascade River, then approach the northeast face via C-J couloir", "trailheadLat": 48.4683, "trailheadLng": -121.06, "peakLat": 48.46456, "peakLng": -121.09192}'::jsonb, approach = 'East/Northeast from Cascade Pass trailhead; descend and cross Cascade River, then approach the northeast face via C-J couloir', dist_km = 4.83, gain_ft = 4563, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '3'), beta = 'Grade: 5.7+ YDS, Grade IV, 12 pitches, 4,000 feet. First ascent: 1963. Route: Climb partway up C-J couloir to hanging glacier on right; ascend leftmost rib to summit. Hazards: Objective danger from falling rock/ice, steep snow, exposed scrambling, avalanche potential. Equipment: Small-to-medium alpine rock rack (to 3 inches), 10+ runners, helmet. Best season: July-September. No bush climbing.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Wilderness permit required year-round for overnight stays in North Cascades National Park. Permits via Recreation.gov (60% reservation) or first-come-first-serve (40%). Cascade River Road (unpaved, 23 miles) opens late June/July. Free trailhead parking."')
WHERE id = 'wa_northeast_ridge_1963_route';

-- Serpentine Crack
-- Peak: Liberty Bell Mountain | Trailhead: Blue Lake Trail (Trail #314)
UPDATE routes
SET approach_logistics = '{"trailhead": "Blue Lake Trail (Trail #314)", "trailheadDirection": "West, from Washington Pass area near Winthrop, Washington", "trailheadLat": 48.5197, "trailheadLng": -120.674183, "peakLat": 48.51548, "peakLng": -120.65874}'::jsonb, approach = 'West, from Washington Pass area near Winthrop, Washington', dist_km = 2.5, gain_ft = 918, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '2.5'), beta = 'Grade III alpine rock, 5.11 crux. Four pitches on Liberty Bell West Face. Pitch 1 (5.8): Slab moves left into corner with short bulge. Pitch 2 (5.11 crux): Wide hand crack, physical, excellent gear. Pitch 3 (5.10): Left-angling hand crack with roof/bulge exit. Pitch 4 (5.7): Navigate tunnel or harder left slab variation, then simul/scramble on exposed sunny arete to summit. Approach via Beckey Route approach, staying left at fork in gully. Excellent hand crack climbing with minimal traffic. Hazards: loose rock from freeze-thaw cycles, afternoon thunderstorms, exposure on final arete.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Northwest Forest Pass required for parking. No climbing permit required (peak is outside North Cascades National Park boundary). Best climbing season: July-September (July-August optimal). June approach often snow-filled; ice axe/crampons may be needed. Afternoon thunderstorm risk July-August."')
WHERE id = 'wa_liberty_bell_serpentine_crack';

-- North Mowich Headwall (Edmunds Headwall)
-- Peak: Mount Rainier | Trailhead: Mowich Lake
UPDATE routes
SET approach_logistics = '{"trailhead": "Mowich Lake", "trailheadDirection": "Northwest corner of Mount Rainier National Park via SR 165", "trailheadLat": 46.93872, "trailheadLng": -121.86149, "peakLat": 46.8529, "peakLng": -121.80861}'::jsonb, approach = 'Northwest corner of Mount Rainier National Park via SR 165', dist_km = 11, gain_ft = 4757, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '7'), beta = 'Grade IV, WI3 Moderate Snow. Steep hourglass rock/ice section (40-50 ft), ~45° snow slope, 5th class rock band, ~2,000 ft vertical gain on climb. Rockfall hazard (climb early). Crevasses, avalanche debris. Bivouac at 9,600 ft between North Mowich and Edmunds Glaciers. Two-day approach recommended. Best June-August.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"$82 climbing registration per person (Pay.gov), $12-26 wilderness permit per person/night (May 1-Sept 15). Mount Rainier National Park requires backcountry permit. CRITICAL: Mowich Lake Road currently CLOSED (SR 165 bridge). When open: mid-July to mid-October. Helmet and rescue gear essential. Permit advance planning required via Recreation.gov."')
WHERE id = 'rainier_north_mowich_headwall';

-- Upper North Ridge w/Great Gendarme
-- Peak: Mount Stuart | Trailhead: Esmeralda Basin Trailhead
UPDATE routes
SET approach_logistics = '{"trailhead": "Esmeralda Basin Trailhead", "trailheadDirection": "From I-90 Exit 85, take Highway 970 east 7 miles to Teanaway Road, then bear right onto North Fork Teanaway Road continuing 22.5 miles total. From trailhead: northeast via Lake Ingalls to Goat Pass (east-northeast), then south to Stuart Glacier and North Ridge notch", "trailheadLat": 47.4361, "trailheadLng": -120.9372, "peakLat": 47.4751, "peakLng": -120.9031}'::jsonb, approach = 'From I-90 Exit 85, take Highway 970 east 7 miles to Teanaway Road, then bear right onto North Fork Teanaway Road continuing 22.5 miles total. From trailhead: northeast via Lake Ingalls to Goat Pass (east-northeast), then south to Stuart Glacier and North Ridge notch', dist_km = 6.4, gain_ft = 2998, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '4.5'), beta = 'Grade IV, 5.9. Eleven pitches of low/mid 5th class (5.5-5.6) to Great Gendarme; two crux pitches of 5.9 on the Gendarme itself (steep hand/finger dihedral and offwidth requiring 3.5 protection). Hazards: knife-edge ridge with 1,000+ feet of exposure, loose rock, variable snow/ice conditions, wet terrain mid-ridge, cold wind on exposed ridge, rockfall from climber traffic, steep descent terrain. Requires advanced alpine rock climbing skills, crack protection (especially 3.5"), excellent weather judgment, overnight bivy capability. Total climbing time: 16-20 hours car-to-car. Best months: June-August (snow dependent).', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Free Wilderness Permit required May 15-October 31 (Alpine Lakes Wilderness). Northwest Forest Pass or America the Beautiful Pass required at trailhead. Parking available at Esmeralda Basin Trailhead (47.4361, -120.9372). Best season June-August. Road access to trailhead year-round, but approach conditions heavily snow/weather dependent before June."')
WHERE id = 'wa_upper_north_ridge_w_great_gendarme';

-- Northeast Face
-- Peak: Mount Goode | Trailhead: Rainy Pass PCT Trailhead
UPDATE routes
SET approach_logistics = '{"trailhead": "Rainy Pass PCT Trailhead", "trailheadDirection": "South on Pacific Crest Trail along Bridge Creek for 9.6 miles to North Fork Bridge Creek Trail junction; then north with final bushwhacking to glacier base camp", "trailheadLat": 48.5181, "trailheadLng": -120.7331, "peakLat": 48.4829, "peakLng": -120.911}'::jsonb, approach = 'South on Pacific Crest Trail along Bridge Creek for 9.6 miles to North Fork Bridge Creek Trail junction; then north with final bushwhacking to glacier base camp', dist_km = 25.7, gain_ft = 4799, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '8.5'), beta = 'Grade IV 5.5 alpine rock with 6-8 pitches of low 5th class climbing. Approach requires glacier travel with crampons, navigation skills, and rope handling. Route includes Class 3-4 scrambling sections and rappel descents. Hazards: glacial crevasses/seracs, loose rock, rockfall, sun exposure. Best climbing season: mid-July for snowmelt conditions. Total climb: 2.2 miles, 3,300-3,800 ft elevation gain, ~10 hours.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Backcountry permit required ($10/person + $6 reservation fee) through Recreation.gov and noca_wilderness@nps.gov. Wilderness Info Center operates mid-May to mid-October. Free parking at Rainy Pass trailhead. No park entrance fee. Northwest Forest Pass may be required at adjacent trailheads."')
WHERE id = 'wa_goode_mountain_northeast_face';

-- Liberty Ridge
-- Peak: Liberty Cap | Trailhead: White River Campground (Glacier Basin Trailhead)
UPDATE routes
SET approach_logistics = '{"trailhead": "White River Campground (Glacier Basin Trailhead)", "trailheadDirection": "Northeast side of Mount Rainier; from trailhead proceed via Glacier Basin Trail, cross White River, ascend to St. Elmo Pass (7,400 ft), descend onto lower Winthrop Glacier, traverse Curtis Ridge, ascend Carbon Glacier to Liberty Ridge base", "trailheadLat": 46.9024, "trailheadLng": -121.6438, "peakLat": 46.8529, "peakLng": -121.76047}'::jsonb, approach = 'Northeast side of Mount Rainier; from trailhead proceed via Glacier Basin Trail, cross White River, ascend to St. Elmo Pass (7,400 ft), descend onto lower Winthrop Glacier, traverse Curtis Ridge, ascend Carbon Glacier to Liberty Ridge base', dist_km = 9.6, gain_ft = 9708, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '6.67'), beta = 'Grade IV alpine ice climbing with 40-60 degree steep snow and ice; 5,512 ft technical climbing from ridge base (8,600 ft) to Liberty Cap (14,112 ft); 5.7 pitches; requires Alpine Ice Grade III+ experience and multi-day expedition commitment; crux is sustained steep ice and exposed ridge sections with high rockfall hazard from Willis Wall above Carbon Glacier', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Annual Climbing Fee: $82 per person per year; Climbing Permit required (one per party) for glacier access and climbing above 10,000 ft - available via Recreation.gov (June-September) or in-person at ranger station; Wilderness Permit: $10 per person per night (youth 15 and under free); National Park entrance fee required; White River Campground at 4,232 ft offers parking and camping; climbing best May 27 - June 8; winter conditions into July possible; absolutely requires crevasse rescue training, multi-pitch ice climbing experience, and established belay/anchor skills"')
WHERE id = 'wa_mount_rainier_liberty_ridge';

-- Cockscomb Ridge
-- Peak: Mount Baker | Trailhead: Artist Point (Ptarmigan Ridge Trailhead)
UPDATE routes
SET approach_logistics = '{"trailhead": "Artist Point (Ptarmigan Ridge Trailhead)", "trailheadDirection": "Start at Artist Point parking area (elevation 5,075 ft). Follow Ptarmigan Ridge Trail northwesterly for 5 miles to Camp Kiser (~5,800 ft), then head northeasterly across Coleman Glacier, then Roosevelt Glacier, ascending toward the ridge base at 7,500 ft", "trailheadLat": 48.8465, "trailheadLng": -121.6927, "peakLat": 48.7797, "peakLng": -121.8204}'::jsonb, approach = 'Start at Artist Point parking area (elevation 5,075 ft). Follow Ptarmigan Ridge Trail northwesterly for 5 miles to Camp Kiser (~5,800 ft), then head northeasterly across Coleman Glacier, then Roosevelt Glacier, ascending toward the ridge base at 7,500 ft', dist_km = 10.5, gain_ft = 7201, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '7'), beta = 'Grade: 4th class YDS, AI2-3 ice, M1b mixed, PG-13. Technical: 3,000 ft vertical gain over 5 pitches on the ridge itself. Hazards: Extremely loose and unstable rock (especially late season), bergschrunds, extensive crevassing, icefall terrain. Route: Ascend Ptarmigan Ridge Trail to Camp Kiser, cross Coleman and Roosevelt Glaciers northeastward, climb low-moderate snow ramps to ridge at ~7,500 ft, bypass Cockscomb Tower on left via steep snow, continue ridge to summit. Descent: Coleman-Deming Route (easy-moderate glacier). Required: Ice climbing competency, crevasse rescue skills, glacier travel experience, rock scrambling ability. Protection: Few ice screws/pickets, glacier gear essential. Best season: Spring or early summer (late season loose rock creates high hazard). First ascent: July 4, 1961 (Murley, Musser, Vielbig).', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Northwest Forest Pass ($5 day use or $30 annual) or America the Beautiful Pass required. Free self-issue wilderness permit available at trailhead (day use or overnight). Group size limit 12 people maximum. Vault toilets and parking for ~160 vehicles at Artist Point. No water available. Seasonal: Route becomes significantly more hazardous (loose rock) after early summer; spring/early summer strongly recommended. Glacier conditions variable year to year."')
WHERE id = 'wa_mount_baker_cockscomb_ridge';

-- Southeast Ridge (SE Corner)
-- Peak: Mount Shuksan | Trailhead: Shannon Ridge Trailhead (Sulphide Glacier approach)
UPDATE routes
SET approach_logistics = '{"trailhead": "Shannon Ridge Trailhead (Sulphide Glacier approach)", "trailheadDirection": "East-northeast up Shannon Ridge, then traverse Sulphide Glacier to reach southeast ridge base", "trailheadLat": 48.76721, "trailheadLng": -121.61795, "peakLat": 48.83096, "peakLng": -121.60292}'::jsonb, approach = 'East-northeast up Shannon Ridge, then traverse Sulphide Glacier to reach southeast ridge base', dist_km = 11.3, gain_ft = 6627, timing = jsonb_set(coalesce(timing, '{}'), '{approachTimeHrs}', '5.5'), beta = 'Grade 5.3-5.7, II-III Alpine. 600 vertical feet over 6 pitches from ridge base to summit. Rock quality excellent. Primary hazards: high exposure, significant glacier crevasses, late-season ice conditions, Class 4 downclimbing. 60m rope required for descent rappels. Accessible via Sulphide Glacier or Fisher Chimneys approaches. Often requires bivy camp due to multi-day approach.', access = jsonb_set(coalesce(access, '{}'), '{notes}', '"Backcountry permit required ($10/person + $6 fee peak season May 17-Oct 12); Northwest Forest Pass or America the Beautiful Pass for parking; permits lottery-based May 17-Oct 12, first-come first-serve off-season; no dogs allowed; best season: late July to August"')
WHERE id = 'wa_southeast_ridge_se_corner';

COMMIT;

-- Verification query
SELECT id, name, approach, dist_km, gain_ft,
  approach_logistics->>'trailhead' as trailhead,
  LEFT(approach_logistics->>'trailheadDirection', 50) as direction
FROM routes
WHERE id IN (
  'wa_mount_rainier_fuhrer_thumb',
  'wa_glacier_peak_disappointment_cleaver',
  'wa_king_kong_gorillas_direct_direct',
  'wa_south_headwall',
  'wa_liberty_traverse',
  'wa_wright_pond',
  'wa_liberty_bell_thin_red_line',
  'wa_northeast_ridge_1963_route',
  'wa_liberty_bell_serpentine_crack',
  'rainier_north_mowich_headwall',
  'wa_upper_north_ridge_w_great_gendarme',
  'wa_goode_mountain_northeast_face',
  'wa_mount_rainier_liberty_ridge',
  'wa_mount_baker_cockscomb_ridge',
  'wa_southeast_ridge_se_corner'
)
ORDER BY name;