// Enrichment data display components
// Used on route detail page, Details and Safety tabs

export function PeakMetadataPanel({route, C, MOUNTAINS}) {
  if (!route.peakMetadata) return null;
  const {elevation, prominence, county, range, geology, firstAscent} = route.peakMetadata;
  return <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"13px 15px",marginBottom:13}}><div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:10,display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:16}}>📍</span><span>PEAK</span></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:12}}><div><div style={{fontSize:10.5,fontWeight:700,color:C.textMuted,textTransform:"uppercase",letterSpacing:0.5,marginBottom:3}}>Elevation</div><div style={{fontSize:14,fontWeight:700,color:C.text}}>{elevation?elevation.toLocaleString()+" ft":""}</div></div><div><div style={{fontSize:10.5,fontWeight:700,color:C.textMuted,textTransform:"uppercase",letterSpacing:0.5,marginBottom:3}}>Prominence</div><div style={{fontSize:14,fontWeight:700,color:C.text}}>{prominence?prominence.toLocaleString()+" ft":""}</div></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:12}}><div><div style={{fontSize:10.5,fontWeight:700,color:C.textMuted,textTransform:"uppercase",letterSpacing:0.5,marginBottom:3}}>County</div><div style={{fontSize:13,color:C.textSub}}>{county||"—"}</div></div><div><div style={{fontSize:10.5,fontWeight:700,color:C.textMuted,textTransform:"uppercase",letterSpacing:0.5,marginBottom:3}}>Range</div><div style={{fontSize:13,color:C.textSub}}>{range||"—"}</div></div></div>{geology?<div style={{marginBottom:12}}><div style={{fontSize:10.5,fontWeight:700,color:C.textMuted,textTransform:"uppercase",letterSpacing:0.5,marginBottom:3}}>Geology</div><div style={{fontSize:13,color:C.textSub,lineHeight:1.5}}>{geology}</div></div>:null}{firstAscent?<div><div style={{fontSize:10.5,fontWeight:700,color:C.textMuted,textTransform:"uppercase",letterSpacing:0.5,marginBottom:3}}>First Ascent</div><div style={{fontSize:13,color:C.textSub,lineHeight:1.5}}>{firstAscent.date||""}{ firstAscent.date?" by ":""}{(firstAscent.climbers||[]).join(", ")}{firstAscent.notes?<div style={{marginTop:4,fontSize:12,color:C.textMuted,fontStyle:"italic"}}>{firstAscent.notes}</div>:null}</div></div>:null}</div>;
}

export function SeasonalGuidancePanel({route, C}) {
  if (!route.seasonalGuidance) return null;
  const {optimalWindow, monthBreakdown} = route.seasonalGuidance;
  return <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"13px 15px",marginBottom:13}}><div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:10,display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:16}}>📅</span><span>SEASONAL GUIDANCE</span></div>{optimalWindow?<div style={{background:C.greenBg,border:"1px solid "+C.greenDim,borderRadius:9,padding:"10px 12px",marginBottom:12}}><div style={{fontSize:11.5,fontWeight:700,color:C.green,marginBottom:3}}>Optimal window</div><div style={{fontSize:13,color:C.text}}>{optimalWindow}</div></div>:null}{monthBreakdown&&Object.keys(monthBreakdown).length?<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{Object.entries(monthBreakdown).map(([month,info])=>{const colors={optimal:[C.green,C.greenBg],good:[C.blue,C.blueBg],marginal:[C.amber,C.amberBg],risky:[C.red,C.redBg]};const [col,bg]=colors[info.status]||[C.textMuted,C.surface];return <div key={month} style={{background:bg,border:"1px solid "+col+"55",borderRadius:9,padding:"8px 10px"}}><div style={{fontSize:12,fontWeight:700,color:col}}>{month}</div><div style={{fontSize:11,color:C.textSub,marginTop:2}}>{info.status}</div></div>;})}</div>:null}</div>;
}

export function HazardsDetailPanel({route, C}) {
  if (!route.seasonalHazards) return null;
  const {avalanche, weather, crevasses, exposure} = route.seasonalHazards;
  return <div style={{background:C.card,border:"1px solid "+C.redDim,borderRadius:12,padding:"13px 15px",marginBottom:13}}><div style={{fontSize:14,fontWeight:700,color:C.red,marginBottom:10,display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:16}}>⚠️</span><span>HAZARD DETAILS</span></div>{avalanche?<div style={{marginBottom:14}}><div style={{fontSize:13,fontWeight:700,color:C.text,marginBottom:3,display:"flex",alignItems:"center",gap:6}}><span style={{fontSize:14}}>🏔️</span><span>Avalanche</span></div>{avalanche.zone?<div style={{fontSize:12,color:C.textMuted,marginBottom:8}}>Zone: {avalanche.zone}</div>:null}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{Object.entries(avalanche.byMonth||{}).map(([month,level])=>{const colors={Considerable:[C.red,C.redBg],Moderate:[C.amber,C.amberBg],Low:[C.green,C.greenBg]};const [col,bg]=colors[level]||[C.textMuted,C.surface];return <div key={month} style={{background:bg,border:"1px solid "+col+"55",borderRadius:8,padding:"6px 8px"}}><div style={{fontSize:11.5,fontWeight:700,color:col}}>{month}</div><div style={{fontSize:10.5,color:C.textSub}}>{level}</div></div>;})}</div></div>:null}{weather?<div><div style={{fontSize:13,fontWeight:700,color:C.text,marginBottom:3,display:"flex",alignItems:"center",gap:6}}><span style={{fontSize:14}}>⛈️</span><span>Weather</span></div><div style={{fontSize:12.5,color:C.textSub,lineHeight:1.5,marginBottom:3}}>{weather.typical}</div>{weather.probability?<div style={{fontSize:12,color:C.amber,fontWeight:700,background:C.amberBg,border:"1px solid "+C.amber+"55",borderRadius:8,padding:"6px 10px"}}>{weather.probability}</div>:null}</div>:null}</div>;
}

export function CrowdsPanel({route, C}) {
  if (!route.crowds) return null;
  const {estimatePerSeason, peakTraffic, solitudeRating} = route.crowds;
  return <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"13px 15px",marginBottom:13}}><div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:10,display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:16}}>👥</span><span>CROWDS & SOLITUDE</span></div>{estimatePerSeason?<div style={{marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:2}}>Parties per season</div><div style={{fontSize:14,fontWeight:700,color:C.text}}>{estimatePerSeason}+</div></div>:null}{peakTraffic?<div style={{marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:2}}>Peak traffic</div><div style={{fontSize:13,color:C.textSub}}>{peakTraffic}</div></div>:null}{solitudeRating?<div><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:3}}>Solitude rating</div><div style={{fontSize:16}}>{'★'.repeat(5-solitudeRating)+'☆'.repeat(solitudeRating)}</div></div>:null}</div>;
}

export function PermitsAccessPanel({route, C}) {
  if (!route.permitInfo) return null;
  const {type, cost, regulations, notes} = route.permitInfo;
  return <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"13px 15px",marginBottom:13}}><div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:10,display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:16}}>📋</span><span>PERMITS & ACCESS</span></div>{type?<div style={{marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:2}}>Permit type</div><div style={{fontSize:13,color:C.textSub}}>{type}</div></div>:null}{cost!==undefined?<div style={{marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:2}}>Cost</div><div style={{fontSize:13,color:C.text,fontWeight:700}}>{cost==="Free"||cost==="free"?"Free":cost||"—"}</div></div>:null}{regulations?<div style={{marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:2}}>Regulations</div><div style={{fontSize:12.5,color:C.textSub,lineHeight:1.5}}>{regulations}</div></div>:null}{notes?<div style={{fontSize:12,color:C.amber,background:C.amberBg,border:"1px solid "+C.amber+"55",borderRadius:8,padding:"8px 10px",lineHeight:1.5}}>{notes}</div>:null}</div>;
}

export function PartnerRequirementsPanel({route, C}) {
  if (!route.partnerRequirements) return null;
  const {experienceLevel, fitnessSpec, requiredSkills, approachTime} = route.partnerRequirements;
  return <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"13px 15px",marginBottom:13}}><div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:10,display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:16}}>🤝</span><span>PARTNER REQUIREMENTS</span></div>{experienceLevel?<div style={{marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:2}}>Experience level</div><div style={{fontSize:13,color:C.textSub}}>{experienceLevel}</div></div>:null}{fitnessSpec?<div style={{marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:2}}>Fitness specs</div>{typeof fitnessSpec==="string"?<div style={{fontSize:13,color:C.textSub}}>{fitnessSpec}</div>:<div style={{fontSize:12.5,color:C.textSub}}>{Object.entries(fitnessSpec).map(([k,v])=>k+": "+v).join(" · ")}</div>}</div>:null}{requiredSkills&&requiredSkills.length?<div style={{marginBottom:10}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:3}}>Required skills</div><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{requiredSkills.map(s=><span key={s} style={{fontSize:11.5,color:C.blue,background:C.blueBg,padding:"3px 8px",borderRadius:6}}>{s}</span>)}</div></div>:null}{approachTime?<div><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:2}}>Approach time</div><div style={{fontSize:13,color:C.textSub}}>{approachTime}</div></div>:null}</div>;
}

export function DataQualityPanel({route, C}) {
  if (!route.dataQuality) return null;
  const {confidence, lastVerified, gaps} = route.dataQuality;
  const confColor=confidence==="HIGH"?C.green:confidence==="MEDIUM"?C.amber:C.red;
  return <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:12,padding:"13px 15px",marginBottom:13}}><div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:10,display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:16}}>📊</span><span>DATA QUALITY</span></div><div style={{marginBottom:10,padding:"8px 11px",background:confColor+"22",border:"1px solid "+confColor+"55",borderRadius:8}}><div style={{fontSize:12,fontWeight:700,color:confColor,marginBottom:2}}>Confidence: {confidence}</div><div style={{fontSize:11.5,color:C.textSub}}>Data verified from {lastVerified?lastVerified:"recent sources"}</div></div>{gaps&&gaps.length?<div><div style={{fontSize:12,fontWeight:700,color:C.amber,marginBottom:4}}>Flagged gaps:</div><div style={{display:"flex",gap:3,flexWrap:"wrap"}}>{gaps.map(g=><span key={g} style={{fontSize:11,color:C.amber,background:C.amberBg,border:"1px solid "+C.amber+"55",padding:"2px 7px",borderRadius:5}}>{g}</span>)}</div></div>:null}</div>;
}
