// load-state.mjs — additively load a state's catalog into Supabase (UPSERT, no truncate).
// Appends/updates one state without touching the others. Uses the PostgREST REST API + service-role key.
// The service_role key is a SECRET: Supabase Dashboard > Project Settings > API > service_role.
//
//   SUPABASE_SERVICE_KEY="<service_role key>" node load-state.mjs wa
//
import { readFileSync } from "node:fs";

const PREFIX = process.argv[2];
if (!PREFIX) { console.error("Usage: SUPABASE_SERVICE_KEY=... node load-state.mjs <prefix>"); process.exit(1); }

let url = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
if (!url) { try { url = (readFileSync(".env.local", "utf8").match(/VITE_SUPABASE_URL=(.+)/) || [])[1]?.trim(); } catch {} }
const key = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) { console.error("Need VITE_SUPABASE_URL (in .env.local) and SUPABASE_SERVICE_KEY (the service_role secret)."); process.exit(1); }
url = url.replace(/\/$/, "");
const H = { apikey: key, Authorization: "Bearer " + key, "Content-Type": "application/json" };

const A = JSON.parse(readFileSync(`catalog/${PREFIX}/${PREFIX}_areas.json`, "utf8"));
const R = JSON.parse(readFileSync(`catalog/${PREFIX}/${PREFIX}_routes.json`, "utf8"));

function gradeSystem(d) { if (d === "bouldering") return "v"; if (["scrambling", "mountaineering", "hiking"].includes(d)) return "class"; if (["trad", "sport", "alpine", "rock"].includes(d)) return "yds"; if (d === "ice") return "wi"; if (d === "mixed") return "m"; if (d === "aid") return "aid"; return null; }
// grade_num is parsed by lib/grade.js — the SINGLE implementation. This file used to
// carry its own copy; there were FOUR, and they had already drifted (this one and the
// two beside it agreed, scripts/oneoff/import-class2-3-routes.mjs did not, and none
// handled a bare ordinal like "4th"). Equivalence with the copy removed here was
// proven over every distinct (grade, system) in the live WA catalog before the swap:
// scripts/oneoff/verify-grade-parser-equivalence.mjs. Do not re-inline it —
// check:grade-parser fails if a second parser appears.
import { gradeNumFrom as gradeNum } from "../../lib/grade.js";

// USA root is shared across states — upsert is idempotent. Topological order (parents first) for the path trigger.
const areas = [{ id: "usa", name: "United States", parentId: null, areaType: "country", region: "USA", lat: 39.83, lng: -98.58 }, ...A];
const byId = {}; areas.forEach(a => byId[a.id] = a);
const ordered = [], seen = new Set();
function emit(a) { if (seen.has(a.id)) return; if (a.parentId && byId[a.parentId]) emit(byId[a.parentId]); seen.add(a.id); ordered.push(a); }
areas.forEach(emit);

const aRow = a => ({ id: a.id, name: a.name, parent_id: a.parentId, area_type: a.areaType, region: a.region, lat: a.lat, lng: a.lng, elevation_ft: a.elevationFt ?? null, prominence_ft: a.prominenceFt ?? null, parent_peak: a.parentPeak ?? null, source: a.source ?? null });
const rRow = r => { const disc = r.discipline === "rock" ? (r.style ? r.style.toLowerCase() : "rock") : r.discipline; const sys = r.gradeSystem || gradeSystem(disc); return { id: r.id, area_id: r.mountainId, name: r.name, discipline: disc, grade: r.grade, grade_system: sys, grade_num: gradeNum(r.grade, sys), pitches: r.pitches, sort_order: r.sortOrder ?? null, length_m: r.routeFt != null ? Math.round(r.routeFt / 3.28084) : null, aspect: r.aspect ?? null, season: r.season ?? null, fa: r.fa ?? null, gain_ft: r.gainFt ?? (r.gainM!=null?Math.round(r.gainM*3.28084):null), loss_ft: r.lossFt ?? (r.lossM!=null?Math.round(r.lossM*3.28084):null), dist_km: r.distKm ?? null, max_angle: r.maxAngle ?? null, rappels: r.rappels ?? null, commitment: r.commitment ?? null, face: r.face ?? null, permit: r.permit ?? null, comms: r.comms ?? null, descent: r.descent ?? null, obj_haz: r.objHaz ?? null, waypoints: r.waypoints ?? null, gpx: r.gpxPts ?? null, elev_pts: r.elevPts ?? null, overview: r.overview ?? null, beta: r.beta ?? null, turnaround: r.turnaround ?? null, auto_generated: r.autoGenerated ?? false, source: r.source ?? null, alpine_grade: r.alpineGrade ?? null, rock_grade: r.rockGrade ?? null, ice_grade: r.iceGrade ?? null, disciplines: r.disciplines ?? null, high_point_ft: r.highPointFt ?? null, aid_grade: r.aidGrade ?? null, gear: r.gear ?? null, hazards: r.hazards ?? null, approach: r.approach ?? null, descent_text: r.descentText ?? null, bail: r.bail ?? null, pitch_detail: r.pitchDetail ?? null, itinerary: r.itinerary ?? null, access: r.access ?? null, road: r.road ?? null, climate: r.climate ?? null, emergency: r.emergency ?? null, lists: r.lists ?? null }; };

async function up(table, rows, size) {
  for (let i = 0; i < rows.length; i += size) {
    const r = await fetch(`${url}/rest/v1/${table}`, { method: "POST", headers: { ...H, Prefer: "resolution=merge-duplicates,return=minimal" }, body: JSON.stringify(rows.slice(i, i + size)) });
    if (!r.ok) throw new Error(table + " @" + i + ": " + r.status + " " + (await r.text()).slice(0, 400));
    process.stdout.write(`\r  ${table}: ${Math.min(i + size, rows.length)}/${rows.length}   `);
  }
  console.log("");
}
async function count(table) {
  const r = await fetch(`${url}/rest/v1/${table}?select=id`, { method: "HEAD", headers: { ...H, Prefer: "count=exact" } });
  const cr = r.headers.get("content-range"); return cr ? cr.split("/")[1] : "?";
}

// The upsert resolves duplicates on the PRIMARY KEY, so it only updates a route whose id
// already matches. If a route's id ever changes shape — as it did when route ids became
// peak-scoped (`wa_mount_baker_north_ridge`) instead of state-scoped (`wa_north_ridge_2`)
// — the same climb arrives under a new id and INSERTS a second copy rather than updating
// the first. On WA that is 8,000+ silent duplicates, catalog-wide 200,000.
//
// So before writing, check the identity that actually means "the same climb": the pair
// (area_id, name). Any incoming route matching an existing row on that pair but carrying a
// different id is a rename-in-disguise, and loading it would duplicate.
async function preflight(rows) {
  const areaIds = new Set(rows.map(r => r.area_id).filter(Boolean));
  const existing = new Map();          // "area_id|lowername" -> existing id
  let last = "";
  for (let guard = 0; guard < 5000; guard++) {
    const q = `${url}/rest/v1/routes?select=id,area_id,name&id=like.${PREFIX}\\_*` +
      `${last ? `&id=gt.${encodeURIComponent(last)}` : ""}&order=id.asc&limit=1000`;
    const res = await fetch(q, { headers: H });
    if (!res.ok) throw new Error("preflight: " + res.status + " " + (await res.text()).slice(0, 200));
    const page = await res.json();
    if (!page.length) break;
    for (const e of page) {
      if (areaIds.has(e.area_id)) existing.set(`${e.area_id}|${(e.name || "").trim().toLowerCase()}`, e.id);
    }
    last = page[page.length - 1].id;
    if (page.length < 1000) break;
  }
  const clashes = [];
  for (const r of rows) {
    const prior = existing.get(`${r.area_id}|${(r.name || "").trim().toLowerCase()}`);
    if (prior && prior !== r.id) clashes.push({ incoming: r.id, existing: prior, area: r.area_id, name: r.name });
  }
  if (!clashes.length) { console.log(`  preflight OK — no (area_id, name) already held under a different id`); return; }
  console.error(`\nREFUSING TO LOAD: ${clashes.length} route(s) already exist on the same area with the same name under a DIFFERENT id.`);
  console.error("Loading would insert a second copy of each rather than updating it.\n");
  for (const c of clashes.slice(0, 15)) {
    console.error(`  ${c.area}  "${c.name}"`);
    console.error(`      incoming id: ${c.incoming}`);
    console.error(`      existing id: ${c.existing}`);
  }
  if (clashes.length > 15) console.error(`  ... and ${clashes.length - 15} more`);
  console.error(`\nEither migrate the existing ids to the new scheme first, or re-run with`);
  console.error(`--allow-duplicate-names if you have confirmed these really are distinct climbs.`);
  process.exit(1);
}

const routeRows = R.map(rRow);
if (process.argv.includes("--allow-duplicate-names")) {
  console.log("WARNING: --allow-duplicate-names — skipping the (area_id, name) collision check.");
} else {
  console.log("Preflight: checking for the same climb already stored under a different id...");
  await preflight(routeRows);
}

console.log(`Upserting ${ordered.length} areas (additive — keeps existing states)...`);
await up("areas", ordered.map(aRow), 500);
console.log(`Upserting ${routeRows.length} routes...`);
await up("routes", routeRows, 250);

const ac = await count("areas"), rc = await count("routes");
const usa = await (await fetch(`${url}/rest/v1/areas?id=eq.usa&select=route_count`, { headers: H })).json();
console.log(`\nDONE — total areas now: ${ac} | total routes now: ${rc} | USA rolls up: ${usa[0]?.route_count}`);
