// load-state.mjs — additively load a state's catalog into Supabase (UPSERT, no truncate).
// Appends/updates one state without touching the others. Uses the PostgREST REST API + service-role key.
// The service_role key is a SECRET: Supabase Dashboard > Project Settings > API > service_role.
//
//   SUPABASE_SERVICE_KEY="<service_role key>" node load-state.mjs wa
//
import { readFileSync } from "node:fs";

const PREFIX = process.argv[2];
if (!PREFIX) { console.error("Usage: SUPABASE_SERVICE_KEY=... node load-state.mjs <prefix>"); process.exit(1); }

let url = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
if (!url) { try { url = (readFileSync(".env.local", "utf8").match(/VITE_SUPABASE_URL=(.+)/) || [])[1]?.trim(); } catch {} }
const key = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) { console.error("Need VITE_SUPABASE_URL (in .env.local) and SUPABASE_SERVICE_KEY (the service_role secret)."); process.exit(1); }
url = url.replace(/\/$/, "");
const H = { apikey: key, Authorization: "Bearer " + key, "Content-Type": "application/json" };

const A = JSON.parse(readFileSync(`catalog/${PREFIX}/${PREFIX}_areas.json`, "utf8"));
const R = JSON.parse(readFileSync(`catalog/${PREFIX}/${PREFIX}_routes.json`, "utf8"));

function gradeSystem(d) { if (d === "bouldering") return "v"; if (["scrambling", "mountaineering", "hiking"].includes(d)) return "class"; if (["trad", "sport", "alpine", "rock"].includes(d)) return "yds"; if (d === "ice") return "wi"; if (d === "mixed") return "m"; if (d === "aid") return "aid"; return null; }
function gradeNum(g, s) { if (!g) return null; let m; if (s === "yds" && (m = g.match(/5\.(\d+)([a-d]?)/))) return parseInt(m[1]) + (m[2] ? ("abcd".indexOf(m[2]) + 1) / 4 : 0); if (s === "v" && (m = g.match(/V(\d+)/))) return parseInt(m[1]); if (s === "wi" && (m = g.match(/WI(\d+)/i))) return parseInt(m[1]); if (s === "m" && (m = g.match(/M(\d+)/))) return parseInt(m[1]); if (s === "aid" && (m = g.match(/[AC](\d)/))) return parseInt(m[1]); if ((m = g.match(/5\.(\d+)([a-d]?)/))) return parseInt(m[1]) + (m[2] ? ("abcd".indexOf(m[2]) + 1) / 4 : 0); if ((m = g.match(/\b(?:WI|AI)(\d+)/i))) return parseInt(m[1]); if ((m = g.match(/\bV(\d+)/))) return parseInt(m[1]); if ((m = g.match(/\b(TD|PD|AD|ED)\b/)) || (m = g.match(/^(D|F)[+-]?$/))) { const ag = { F:1, PD:2, AD:3, D:4, TD:5, ED:6 }; return ag[m[1]]; } if ((m = g.match(/class\s*(\d)/i)) || (m = g.match(/(\d)\s*(?:rd|th|nd)?\s*class/i))) return parseInt(m[1]); if ((m = g.match(/^\s*(VII|VI|IV|III|II|I|V)\b/))) { const rm = { I:1, II:2, III:3, IV:4, V:5, VI:6, VII:7 }; return rm[m[1]]; } return null; }

// USA root is shared across states — upsert is idempotent. Topological order (parents first) for the path trigger.
const areas = [{ id: "usa", name: "United States", parentId: null, areaType: "country", region: "USA", lat: 39.83, lng: -98.58 }, ...A];
const byId = {}; areas.forEach(a => byId[a.id] = a);
const ordered = [], seen = new Set();
function emit(a) { if (seen.has(a.id)) return; if (a.parentId && byId[a.parentId]) emit(byId[a.parentId]); seen.add(a.id); ordered.push(a); }
areas.forEach(emit);

const aRow = a => ({ id: a.id, name: a.name, parent_id: a.parentId, area_type: a.areaType, region: a.region, lat: a.lat, lng: a.lng, elevation_ft: a.elevationFt ?? null, prominence_ft: a.prominenceFt ?? null, parent_peak: a.parentPeak ?? null, source: a.source ?? null });
const rRow = r => { const disc = r.discipline === "rock" ? (r.style ? r.style.toLowerCase() : "rock") : r.discipline; const sys = r.gradeSystem || gradeSystem(disc); return { id: r.id, area_id: r.mountainId, name: r.name, discipline: disc, grade: r.grade, grade_system: sys, grade_num: gradeNum(r.grade, sys), pitches: r.pitches, sort_order: r.sortOrder ?? null, length_m: r.routeFt != null ? Math.round(r.routeFt / 3.28084) : null, aspect: r.aspect ?? null, season: r.season ?? null, fa: r.fa ?? null, gain_ft: r.gainFt ?? (r.gainM!=null?Math.round(r.gainM*3.28084):null), loss_ft: r.lossFt ?? (r.lossM!=null?Math.round(r.lossM*3.28084):null), dist_km: r.distKm ?? null, max_angle: r.maxAngle ?? null, rappels: r.rappels ?? null, commitment: r.commitment ?? null, face: r.face ?? null, permit: r.permit ?? null, comms: r.comms ?? null, descent: r.descent ?? null, obj_haz: r.objHaz ?? null, waypoints: r.waypoints ?? null, gpx: r.gpxPts ?? null, elev_pts: r.elevPts ?? null, overview: r.overview ?? null, beta: r.beta ?? null, turnaround: r.turnaround ?? null, auto_generated: r.autoGenerated ?? false, source: r.source ?? null, alpine_grade: r.alpineGrade ?? null, rock_grade: r.rockGrade ?? null, ice_grade: r.iceGrade ?? null, disciplines: r.disciplines ?? null, high_point_ft: r.highPointFt ?? null, aid_grade: r.aidGrade ?? null, gear: r.gear ?? null, hazards: r.hazards ?? null, approach: r.approach ?? null, descent_text: r.descentText ?? null, bail: r.bail ?? null, pitch_detail: r.pitchDetail ?? null, itinerary: r.itinerary ?? null, access: r.access ?? null, road: r.road ?? null, climate: r.climate ?? null, emergency: r.emergency ?? null, lists: r.lists ?? null }; };

async function up(table, rows, size) {
  for (let i = 0; i < rows.length; i += size) {
    const r = await fetch(`${url}/rest/v1/${table}`, { method: "POST", headers: { ...H, Prefer: "resolution=merge-duplicates,return=minimal" }, body: JSON.stringify(rows.slice(i, i + size)) });
    if (!r.ok) throw new Error(table + " @" + i + ": " + r.status + " " + (await r.text()).slice(0, 400));
    process.stdout.write(`\r  ${table}: ${Math.min(i + size, rows.length)}/${rows.length}   `);
  }
  console.log("");
}
async function count(table) {
  const r = await fetch(`${url}/rest/v1/${table}?select=id`, { method: "HEAD", headers: { ...H, Prefer: "count=exact" } });
  const cr = r.headers.get("content-range"); return cr ? cr.split("/")[1] : "?";
}

console.log(`Upserting ${ordered.length} areas (additive — keeps existing states)...`);
await up("areas", ordered.map(aRow), 500);
console.log(`Upserting ${R.length} routes...`);
await up("routes", R.map(rRow), 250);

const ac = await count("areas"), rc = await count("routes");
const usa = await (await fetch(`${url}/rest/v1/areas?id=eq.usa&select=route_count`, { headers: H })).json();
console.log(`\nDONE — total areas now: ${ac} | total routes now: ${rc} | USA rolls up: ${usa[0]?.route_count}`);
