import fs from "node:fs";
const inp = JSON.parse(fs.readFileSync("enrichment-wip/camping-roles/input/batch-04.json"));
const TH="Cutthroat Creek trailhead", SB="Cutthroat basin climbers' bivy — SOUTH-SIDE routes only", CL="Cutthroat Lake basin, outside the quarter-mile closure", WT="Cutthroat Wall base terrace", LF="Lone Fir Campground", KC="Klipchuck Campground, with Early Winters nearby";
const RP="Rainy Pass PCT north trailhead", CP="Cutthroat Pass, PCT crest camps", GP="Granite Pass", SL="Snowy Lakes basin", MP="Methow Pass and the PCT meadow camps below Snowy Lakes", SW="Swamp Creek highway pullout, for Mount Hardy's south face";
const HI="Eldorado-Inspiration snow arm high camp", RB="Eldorado East Ridge rock bivies", EB="Eldorado Basin camp", RC="Roush Creek Basin camp", KL="Klawatti Col camp", MC="Marble Creek Campground, Cascade River Road";
const R = {};
const peakDay = (onR, note) => ({ main:[LF,KC], onRoute:onR, drop:[TH,CL,WT, ...(onR.includes(SB)?[]:[SB])], note });
R.wa_cutthroat_south_buttress = peakDay([SB], "Usually a day climb from the SR 20 pullout near State Creek, so the car campground is the main camp; the listed Cutthroat Creek trailhead is on the wrong side of Washington Pass for this route.");
R.wa_complete_south_buttress = peakDay([SB], "Same south-side day approach as the South Buttress; car campground main, south basin bivy as the on-route option.");
R.wa_cutthroat_peak_southeast_buttress = peakDay([SB], "Day climb from the State Creek pullout; the south basin bivy sits on the approach.");
R.wa_cutthroat_peak_northeast_face = peakDay([SB], "Approach goes through the south basin then over the rib, so the south basin bivy is on route; normally done in a day.");
R.wa_cutthroat_peak_cauthorn_wilson_couloir = peakDay([SB], "Shoulder-season ice route done in a day from SR 20; Lone Fir may already be closed when it is in condition, which I could not pin down.");
R.wa_cutthroat_west_ridge = peakDay([], "Short day route from a pullout near Blue Lake; unsure whether its basin overlaps the south-side bivy area, so that bivy is dropped.");
R.wa_north_ridge_3 = peakDay([], "Day climb via the south-side basin or from Rainy Pass up Porcupine Creek; the basin bivy is physically near the south approach but its own text says it is not for this route, so it is dropped.");
const wall = note => ({ main:[TH,LF,KC], onRoute:[WT], drop:[SB,CL], note });
for (const id of ["wa_easy_getaway","wa_one_piece_at_a_time","wa_the_perfect_crime_with_variations"]) R[id]=wall("Car-to-car from the Cutthroat Creek trailhead is the norm; trailhead or Lone Fir is where parties sleep, the base terrace is the on-route bivy.");
R.wa_narcos = wall("Same wall and approach as Easy Getaway; confident.");
R.wa_wright_pond = wall("Listed on the same approach from Forest Road 400 as Cutthroat Wall; assumed the same base terrace applies.");
R.wa_tower_mountain_southwest_route = { main:[SL], onRoute:[RP,CP,GP], drop:[MP,SW,"Snowy Lakes basin camp"], note:"Snowy Lakes is the standard two-day base; the waypoint 'Snowy Lakes basin camp' duplicates it, and Methow Pass lies beyond the Snowy Lakes turnoff." };
R.wa_golden_horn_north_face = { main:[SL], onRoute:[SW,RP,CP,GP], drop:[MP], note:"Rarely climbed face with little beta; the route text starts at Swamp Creek but most parties reach Snowy Lakes by the PCT, so both lines are kept on route." };
R.wa_mount_hardy_snow_scramble = { main:[MP,SL], onRoute:[RP,CP,GP], drop:[SW,"Upper Snowy Lake basin"], note:"From the PCT the route leaves at Methow Pass, so its meadow camps or Snowy Lakes are the base; Swamp Creek is a separate one-day approach and is dropped, which a reviewer may prefer to keep." };
R.wa_whistler_mountain_scramble = { main:[RP], onRoute:[], drop:[CP,GP,SL,MP,SW], note:"A half-day scramble from the Rainy Pass lot; none of the PCT camps are on its gully line." };
R.wa_davis_peak_nc_southwest = { main:["Goodell Creek Campground, Newhalem"], onRoute:["Gorge Creek overlook, the trailhead you sleep at","Snowfield benches on the south side, around 4,800 feet","The 5,720 ft saddle south of the summit"], drop:["South Davis Saddle"], note:"Almost always a long single day; the waypoint 'South Davis Saddle' duplicates the 5,720 ft saddle." };
const eld = (main, extraOn, drop, note) => ({ main, onRoute:[MC,EB,RC,...extraOn], drop, note });
const dor = (dropX, note) => eld([HI,KL],[RB],dropX,note);
R.wa_austera_peak = eld([KL,HI],[RB],["Eldorado (East Ridge) camp"],"Parties either day-trip from the Eldorado high camp or move camp to Klawatti Col, which is closer; the waypoint duplicates the East Ridge high camp.");
R.wa_austera_peak_chockstone_route = eld([KL,HI],[RB],[],"Same base as the standard Austera route.");
R.wa_austera_peak_southwest_ridge = eld([KL,HI],[RB],["Eldorado Creek Basin","Roush Creek Basin (Eldorado high camp)"],"Waypoints duplicate the Eldorado Basin and Roush Creek Basin camps.");
R.wa_direct_southwest_buttress = dor(["Eldorado/Inspiration Glacier high camp"],"Dorado Needle is usually done from the Eldorado high camp or a camp moved to Klawatti Col; waypoint is a duplicate of the high camp.");
R.wa_dorado_needle_east_ridge = dor([],"Same base as the other Dorado Needle routes.");
R.wa_northwest_ridge = dor(["Eldorado Creek Basin camp","Eldorado/Inspiration Glacier high camp"],"Waypoints duplicate the Eldorado Basin camp and the snow arm high camp.");
R.wa_southwest_buttress = dor(["Eldorado Creek Basin camp","Eldorado/Inspiration Glacier high camp"],"Waypoints duplicate the Eldorado Basin camp and the snow arm high camp.");
R.wa_klawatti_peak_north_ridge = dor([],"Day trip from the Eldorado high camp or from Klawatti Col.");
R.wa_klawatti_peak_southeast_face = dor(["Roush Creek Basin camps","Eldorado ice-cap / Inspiration Glacier high camp"],"The two waypoints duplicate the Roush Creek Basin camp and the snow arm high camp; the second says 'near Klawatti Col', so it could instead be the col camp.");
R.wa_klawatti_peak_sw_buttress = dor(["Eldorado (East Ridge) camp"],"Starts from Klawatti Col, so either high camp works; waypoint duplicates the East Ridge high camp.");
R.wa_tepeh_towers = dor(["Eldorado (East Ridge) camp"],"A short add-on near the Inspiration-McAllister col, done from the Eldorado high camp or Klawatti Col.");
const eldPk = (dropX, note) => eld([HI],[RB],[KL,...dropX],note);
R.wa_eldorado_peak_eldorado_glacier_nw = eldPk(["Eldorado / Inspiration Glacier camp"],"High camp on the Eldorado-Inspiration snow is the usual base, with the lower basins as alternatives.");
R.wa_eldorado_peak_north_ridge = eldPk(["Eldorado (East Ridge) camp"],"Reached from the Inspiration Glacier high camp.");
R.wa_eldorado_peak_northeast_face = eldPk([],"Same base as the East Ridge.");
R.wa_south_ridge_4 = eldPk(["Eldorado camp (Inspiration Glacier flat)"],"Assumed based at the standard high camp; the waypoint duplicates it.");
R.wa_eldorado_peak_east_ridge = { main:["Eldorado-Inspiration Glacier saddle high camp"], onRoute:["Eldorado Creek Basin","Roush Creek Basin"], drop:["Eldorado / Inspiration Glacier camp"], add:[], note:"Standard two-day plan; the waypoint duplicates the saddle high camp." };
R.wa_eldorado_peak_west_arete = { main:[], onRoute:[MC,EB,RC,HI,RB], drop:[KL], add:[{ name:"Eldorado-Triad saddle ledges", type:"bivy", elev:6400, capacity:"A few tent or bivy spots on glacier-polished granite ledges", water:"Snowmelt or small trickles early in the season; plan to melt snow later on", permit:"North Cascades National Park wilderness permit, picked up in person in Marblemount", notes:"Smooth granite ledges just under the saddle between Eldorado and The Triad, reached by traversing about a mile and a half across the basin below the Eldorado Glacier. This is the usual camp for the West Arete: from it you cross the notch and descend the glacier on the far side to the base of the route. The descent returns over the summit and past the Eldorado high camp.", role:"main" }], note:"The route's real camp, the Eldorado-Triad saddle, was missing and is added; the Inspiration high camp is kept because the descent passes it." };
R.wa_elephant_butte_standard_route = { main:["Stetattle Ridge tarn camps"], onRoute:["Sourdough Camp, Sourdough Creek","Sourdough Mountain summit ground","Improvised camp on the shoulder of Elephant Butte"], drop:["Pierce Mountain Camp"], note:"Ridge tarn camps are the usual base; unsure whether Sourdough Camp sits below or just past where the climbers' line leaves the trail." };
const eldPermit = { what:"North Cascades National Park wilderness permit required for any overnight; $10 per person plus a reservation fee", where:"Reserve on Recreation.gov, or take a walk-up permit the day of or day before. Permits for Eldorado must be picked up in person at the Wilderness Information Center in Marblemount.", url:"https://www.nps.gov/noca/planyourvisit/permits.htm" };
const sr20Permit = { what:"North Cascades National Park wilderness permit required for any overnight; none for a day climb", where:"Reserve on Recreation.gov, or get a walk-up permit in person at the Wilderness Information Center in Marblemount.", url:"https://www.nps.gov/noca/planyourvisit/permits.htm" };
const fsNone = { what:"No overnight permit required", where:"Dispersed camping on national forest land needs no permit. A Northwest Forest Pass or interagency pass is needed to park at signed trailhead lots.", url:null };
const zones = [ {zone:"cutthroat",overnightPermit:fsNone},{zone:"cutthroat-methow-pass",overnightPermit:fsNone},{zone:"davis-peak",overnightPermit:sr20Permit},{zone:"eldorado",overnightPermit:eldPermit},{zone:"elephant-butte",overnightPermit:{...sr20Permit, what:"North Cascades National Park wilderness permit required for any overnight, including Sourdough Camp and the ridge"}} ];
const routes = []; const miss = [];
for (const z of inp) for (const r of z.routes) { const o = R[r.id]; if (!o) { miss.push(r.id); continue; } routes.push({ id:r.id, main:o.main, onRoute:o.onRoute, drop:o.drop, add:o.add||[], overnightPermit:null, note:o.note }); }
if (miss.length) console.log("MISSING", miss);
const misassigned = [
 "wa_cutthroat_south_buttress, wa_complete_south_buttress, wa_cutthroat_peak_southeast_buttress, wa_cutthroat_peak_northeast_face, wa_cutthroat_peak_cauthorn_wilson_couloir, wa_cutthroat_west_ridge, wa_north_ridge_3: Cutthroat Peak routes start from SR 20 pullouts west of Washington Pass (State Creek / Blue Lake), but the zone's trailhead camp, Cutthroat Lake camp and wall terrace all belong to the Cutthroat Creek trailhead east of the pass. The south-side bivy's own text also says to reach it from the Cutthroat Lake trail, which is wrong; its directions need rewriting from the State Creek pullout.",
 "wa_eldorado_peak_west_arete: the route's own camp at the Eldorado-Triad saddle was missing; added.",
];
fs.writeFileSync("enrichment-wip/camping-roles/output/batch-04.json", JSON.stringify({ zones, routes, misassigned }, null, 1));
let c={main:0,onRoute:0,drop:0,add:0}; for(const r of routes){c.main+=r.main.length;c.onRoute+=r.onRoute.length;c.drop+=r.drop.length;c.add+=r.add.length;} console.log(routes.length,c);
