// Moved out of ClimbMatchCore.jsx verbatim so it can load lazily, off the first-paint
// bundle. It is rendered only from App (ClimbMatch.jsx) behind React.lazy + Suspense.
import { DISC_LABELS as DL } from "./discLabels";
import { USE_DB } from "./supabase";
import { POP_REMOVE } from "./popupChrome.js";
import { removeProfileAvatar, uploadProfilePhoto } from "./db";
import { useState } from "react";
import { Av, C, DiscIcon, DOW, Lbl, US_CITIES, US_ST, CA_PROV, hasVulgarity, SKILLS, SKILL_GROUPS, PROFILE_GRADES, CLIMB_ROLES, BELAY_DEVICES, BELAY_LEVELS, certExpiryInfo, profileGradeRows, roleLabel } from "../ClimbMatchCore.jsx";

export default function EditProfileScreen({draft,setDraft,onSave,onCancel,uid,zipNow,zipReady,ecNow,ecReady}){
  /* The avatar used to be `set("avatar",URL.createObjectURL(f))`, and saveEdit PATCHes that
     straight into `profiles.avatar` — so the column held a blob: URL, an in-memory handle that
     resolves to nothing after a reload and to nothing for any other climber. Measured on the
     live project before this change.
     The instant preview is kept, because that part was right; what changes is that the value
     which reaches the draft is the UPLOADED url, and only once the upload has landed. */
  const [avaBusy,setAvaBusy]=useState(false);const [avaErr,setAvaErr]=useState("");const [avaPreview,setAvaPreview]=useState("");
  const set=(k,v)=>setDraft(d=>({...d,[k]:v}));
  /* climb_grades / belay_devices / cert_expiry (0237) are maps; an emptied entry is DELETED, never left
     as {} or "", so what is stored is only what the climber actually said. */
  const setCG=(k,field,v)=>setDraft(d=>{const cg={...(d.climbGrades||{})};const x={...(cg[k]||{})};if(v)x[field]=v;else delete x[field];if(Object.keys(x).length)cg[k]=x;else delete cg[k];return {...d,climbGrades:cg};});
  const setBelay=(k,lvl)=>setDraft(d=>{const b={...(d.belayDevices||{})};if(lvl&&b[k]!==lvl)b[k]=lvl;else delete b[k];return {...d,belayDevices:b};});
  const toggleSkill=lbl=>setDraft(d=>{const sk=d.skills||[];return {...d,skills:sk.includes(lbl)?sk.filter(x=>x!==lbl):[...sk,lbl]};});
  const ec=draft.ec!==undefined?draft.ec:{name:(ecNow&&ecNow.name)||"",phone:(ecNow&&ecNow.phone)||""};
  const setEc=(k,v)=>set("ec",{...ec,[k]:v});
  /* REMOVING the photo acts IMMEDIATELY rather than waiting for Save, and the asymmetry with the
     rest of this editor is deliberate. Every other field here is a draft the climber commits with
     Save — but "Change photo" already uploads on selection, so the storage half of this control was
     never drafted either. More to the point, a climber clearing their face off a partner-search
     screen is taking a PRIVACY action, and leaving it pending behind a button they might never
     press is the wrong direction to fail: navigating away would silently keep the photo.
     The draft is cleared alongside so the editor shows what the database now holds. */
  const removeAva=()=>{setAvaErr("");
    /* Seed mode has no storage and no row to clear — the handle is all there is, exactly as the
       upload path says on the way in. */
    if(!USE_DB){setAvaPreview("");set("avatar","");return;}
    setAvaBusy(true);
    removeProfileAvatar(uid,avaPreview||draft.avatar).then(function(){setAvaBusy(false);setAvaPreview("");set("avatar","");})
      .catch(function(err){setAvaBusy(false);setAvaErr((err&&err.message)||"Couldn’t remove that photo. Check your connection and try again.");});};
  const [ncert,setNcert]=useState("");const [nexp,setNexp]=useState("");const [nskill,setNskill]=useState("");
  const toggleDisc=k=>setDraft(d=>({...d,disciplines:d.disciplines.includes(k)?d.disciplines.filter(x=>x!==k):[...d.disciplines,k]}));
  const DISC=[["sport",DL.sport],["trad",DL.trad],["bouldering",DL.bouldering],["scrambling",DL.scrambling],["alpine",DL.alpine],["mountaineering",DL.mountaineering],["ice",DL.ice],["mixed",DL.mixed],["aid",DL.aid]];
  const LEVELS=["Beginner","Intermediate","Advanced","Expert"];
  const [uTouched,setUTouched]=useState(false);
  const uErr=draft.username.trim().length<3?"Username must be at least 3 characters.":hasVulgarity(draft.username)?"Please choose a different username.":"";
  const nErr=draft.name.trim().length<1;
  const ok=!uErr&&!nErr;
  const uShow=uTouched&&uErr;
  const lbl={fontSize:12,color:C.textMuted,textTransform:"uppercase",letterSpacing:0.4,marginBottom:5,marginTop:14};
  const inp={width:"100%",padding:"10px 12px",borderRadius:10,border:"1px solid "+C.border,background:C.surface,color:C.text,fontSize:14,boxSizing:"border-box"};
  return (<div style={{position:"fixed",inset:0,background:C.bg,zIndex:1100,overflowY:"auto",overscrollBehavior:"contain",maxWidth:520,margin:"0 auto",boxSizing:"border-box"}}>
    <div style={{position:"sticky",top:0,background:C.surface,borderBottom:"1px solid "+C.border,padding:"12px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",zIndex:2}}>
      <div style={{display:"flex",alignItems:"center",gap:12}}><button onClick={onCancel} style={{background:C.card,border:"1px solid "+C.border,color:C.text,borderRadius:8,padding:"9px 11px",fontSize:13,fontWeight:700,cursor:"pointer"}}>Cancel</button><div style={{fontSize:15,fontWeight:700,color:C.text}}>Edit profile</div></div>
      <button disabled={!ok} onClick={onSave} style={{background:ok?C.blueSolid:C.card,color:ok?"#fff":C.textMuted,border:"1px solid "+(ok?C.blue:C.border),borderRadius:8,padding:"6px 16px",fontSize:13,fontWeight:700,cursor:ok?"pointer":"not-allowed"}}>Save</button>
    </div>
    <div style={{maxWidth:560,margin:"0 auto",padding:"4px 16px 44px"}}>
      <div style={{display:"flex",alignItems:"center",gap:14,marginTop:10,marginBottom:2}}><div style={{flexShrink:0}}><Av src={avaPreview||draft.avatar} size={72}/></div><div style={{minWidth:0}}><label style={{display:"inline-flex",alignItems:"center",gap:6,padding:"8px 13px",borderRadius:9,border:"1px solid "+C.blueDim,background:avaBusy?C.card:C.blueBg,color:avaBusy?C.textMuted:C.blue,fontSize:13,fontWeight:700,cursor:avaBusy?"default":"pointer"}}>{avaBusy?"Uploading…":"Change photo"}<input type="file" accept="image/*" disabled={avaBusy} onChange={e=>{const f=e.target.files&&e.target.files[0];e.target.value="";if(!f)return;const local=URL.createObjectURL(f);setAvaErr("");setAvaPreview(local);/* Seed mode has no storage to upload to, so the handle is all there is — and nothing persists there anyway. */if(!USE_DB){set("avatar",local);return;}setAvaBusy(true);uploadProfilePhoto(f).then(function(url){setAvaBusy(false);set("avatar",url);/* Drop the local handle once the real one is in the draft, so what you are looking at is the image that was actually stored rather than a copy that dies with the tab. */setAvaPreview("");}).catch(function(err){setAvaBusy(false);setAvaPreview("");setAvaErr((err&&err.message)||"Couldn’t upload that photo. Check your connection and try again.");});}} className="cm-file-input"/></label>{(avaPreview||draft.avatar)?<button onClick={removeAva} disabled={avaBusy} style={{marginLeft:8,padding:"8px 13px",borderRadius:9,border:"1px solid "+C.border,background:"transparent",color:avaBusy?C.textMuted:C.textSub,fontSize:13,fontWeight:700,cursor:avaBusy?"default":"pointer"}}>{"Remove photo"}</button>:null}<div style={{fontSize:11.5,color:C.textMuted,marginTop:6,lineHeight:1.5}}>This is the photo other climbers see when searching for partners.</div>{avaErr?<div role="alert" style={{fontSize:11.5,color:C.red,marginTop:5,lineHeight:1.45}}>{avaErr}</div>:null}</div></div><div style={lbl}>Display name</div>
      <input aria-label="Your name" value={draft.name} onChange={e=>set("name",e.target.value)} placeholder="Your name" style={inp}/>
      {nErr?<div style={{fontSize:12,color:C.red,marginTop:4}}>Name cannot be empty.</div>:null}
      <div style={lbl}>Username</div>
      <input aria-label="username" value={draft.username} onChange={e=>set("username",e.target.value.replace(/\s/g,""))} placeholder="username" onBlur={()=>setUTouched(true)} style={{...inp,border:"1px solid "+(uShow?C.red:C.border)}}/>
      <div style={{fontSize:12,color:uShow?C.red:C.textMuted,marginTop:4}}>{uShow||("Shown publicly as @"+(draft.username.trim()||"username")+". Hide your real name with the toggle below.")}</div>
      <div style={lbl}>Bio</div>
      <textarea aria-label="Tell partners about your climbing" value={draft.bio} onChange={e=>set("bio",e.target.value)} rows={3} placeholder="Tell partners about your climbing..." style={{...inp,resize:"vertical",fontFamily:"inherit"}}/>
      {(()=>{var parts=(draft.location||"").split(",");var curCity=(parts[0]||"");var curAbbr=(parts[1]||"").trim().toUpperCase();var _regions=US_ST.concat(CA_PROV);var curFull=(_regions.find(function(p){return p[1]===curAbbr;})||["",""])[0];var setLoc=function(city,abbr){set("location",abbr?(city+", "+abbr):city);};return <div><div style={lbl}>Home city</div><input aria-label="Start typing your city" list="cm-cities" value={curCity} onChange={function(ev){setLoc(ev.target.value.replace(/,.*$/,""),curAbbr);}} placeholder="Start typing your city…" style={inp}/><datalist id="cm-cities">{US_CITIES.map(function(c){return <option key={c} value={c}/>;})}</datalist><div style={{...lbl,marginTop:11}}>State or province</div><select aria-label="Select your state or province" value={curFull} onChange={function(ev){var ab=(_regions.find(function(p){return p[0]===ev.target.value;})||["",""])[1];setLoc(curCity,ab);}} style={{...inp,color:C.text}}><option value="">Select your state or province…</option><optgroup label="United States">{US_ST.map(function(p){return <option key={p[1]} value={p[0]}>{p[0]}</option>;})}</optgroup><optgroup label="Canada">{CA_PROV.map(function(p){return <option key={p[1]} value={p[0]}>{p[0]}</option>;})}</optgroup></select></div>;})()}
      {/* Zip code (0189): stored in an owner-only table, never on the public profile. Other climbers
          see only a rounded distance from partner search. `zipReady` is false while the zip is loading, after a failed read,
          and in the demo, so the field is not offered then -- shown blank it would invite a save
          that CLEARS the stored zip. `draft.zip` exists only once the climber edits it. */}
      {zipReady?<div><div style={{...lbl,marginTop:11}}>Zip code</div><input aria-label="Your zip code" inputMode="numeric" autoComplete="postal-code" maxLength={5} value={draft.zip!==undefined?draft.zip:(zipNow||"")} onChange={function(ev){set("zip",ev.target.value.replace(/[^0-9]/g,"").slice(0,5));}} placeholder="e.g. 98101" style={inp}/><div style={{fontSize:11.5,color:C.textMuted,marginTop:5,lineHeight:1.45}}>Used to find partners near you. Only you can see it — other climbers see roughly how far away you are, never your zip.</div></div>:null}
      {/* Emergency contact (0237): an owner-only table, like the zip -- never on the public profile, and
          not offered until the stored one has loaded, so a blank field cannot invite a save that CLEARS it. */}
      {ecReady?<div><div style={lbl}>Emergency contact</div><div style={{display:"flex",gap:8}}><input aria-label="Emergency contact name" autoComplete="off" maxLength={80} value={ec.name} onChange={e=>setEc("name",e.target.value)} placeholder="Name" style={{...inp,flex:1,minWidth:0}}/><input aria-label="Emergency contact phone" type="tel" autoComplete="off" maxLength={32} value={ec.phone} onChange={e=>setEc("phone",e.target.value)} placeholder="Phone" style={{...inp,flex:1,minWidth:0}}/></div><div style={{fontSize:11.5,color:C.textMuted,marginTop:5,lineHeight:1.45}}>Only you can see this. It fills in the contact on your float plans, which you send yourself — ClimbMatch never contacts anyone.</div>{(!!ec.name.trim())!==(!!ec.phone.trim())?<div style={{fontSize:11.5,color:C.amber,marginTop:4}}>Add both a name and a phone number, or clear both.</div>:null}</div>:null}
      <div style={lbl}>Experience level</div>
      <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{LEVELS.map(L=>{const on=draft.level===L;return <button key={L} onClick={()=>set("level",L)} aria-current={on?"true":undefined} style={{padding:"7px 13px",borderRadius:10,border:"1px solid "+(on?C.blue:C.border),background:on?C.blueBg:C.surface,color:on?C.blue:C.textSub,fontSize:13,fontWeight:600,cursor:"pointer"}}>{L}</button>;})}</div>
      <div style={lbl}>Days & times you can climb</div><div style={{fontSize:11.5,color:C.textMuted,margin:"-2px 0 9px",lineHeight:1.45}}>{"Tap the slots you usually climb — your crews use this to find a day that works for everyone."}</div><div style={{display:"flex",alignItems:"center",marginBottom:5}}><div style={{width:30,flexShrink:0}}/><div style={{flex:1,display:"flex",gap:4}}>{DOW.map(d=><div key={d[0]} style={{flex:1,textAlign:"center",fontSize:10.5,fontWeight:700,color:C.textMuted}}>{d[2]}</div>)}</div></div>{["am","pm"].map(p=><div key={p} style={{display:"flex",alignItems:"center",marginBottom:4}}><div style={{width:30,flexShrink:0,fontSize:10.5,fontWeight:700,color:C.textMuted}}>{p.toUpperCase()}</div><div style={{flex:1,display:"flex",gap:4}}>{DOW.map(d=>{const tok=d[0]+"_"+p;const on=(draft.availWeek||[]).includes(tok);return <button key={d[0]} type="button" onClick={()=>set("availWeek",(draft.availWeek||[]).includes(tok)?(draft.availWeek||[]).filter(x=>x!==tok):(draft.availWeek||[]).concat(tok))} aria-label={d[1]+" "+p} aria-pressed={on} style={{flex:1,aspectRatio:"1",minHeight:28,borderRadius:7,border:"1px solid "+(on?C.blue:C.border),background:on?C.blueSolid:C.surface,cursor:"pointer",padding:0}}/>;})}</div></div>)}<div style={{display:"flex",gap:7,margin:"9px 0 16px",flexWrap:"wrap"}}>{[["Weekends",["sat_am","sat_pm","sun_am","sun_pm"]],["Weekday eves",["mon_pm","tue_pm","wed_pm","thu_pm","fri_pm"]],["Anytime",[].concat.apply([],DOW.map(d=>[d[0]+"_am",d[0]+"_pm"]))],["Clear",[]]].map(q=><button key={q[0]} type="button" onClick={()=>set("availWeek",q[1])} style={{background:C.surface,border:"1px solid "+C.border,color:C.textSub,borderRadius:16,padding:"8px 12px",fontSize:11.5,fontWeight:600,cursor:"pointer"}}>{q[0]}</button>)}</div><div style={lbl}>Disciplines</div>
      <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{DISC.map(d=>{const on=draft.disciplines.includes(d[0]);return <button key={d[0]} onClick={()=>toggleDisc(d[0])} aria-pressed={on} style={{display:"inline-flex",alignItems:"center",gap:5,padding:"8px 13px",borderRadius:16,border:"1px solid "+(on?C.green:C.border),background:on?C.greenBg:C.surface,color:on?C.green:C.textSub,fontSize:12,fontWeight:600,cursor:"pointer"}}><DiscIcon d={d[0]} size={13}/>{d[1]}</button>;})}</div>
      <div style={lbl}>Grades you climb</div>
      <div style={{fontSize:11.5,color:C.textMuted,margin:"-2px 0 9px",lineHeight:1.45}}>Your usual top grade, and whether you lead it or follow — the first thing a partner asks.</div>
      {/* A row per discipline you climb; sport, trad and boulder always, since their grades predate the
          discipline chips. A grade typed before the pickers existed stays offered, so opening the
          editor can never silently change it. */}
      {PROFILE_GRADES.filter(g=>{const discKey=g.k==="boulder"?"bouldering":g.k;const x=(draft.climbGrades||{})[g.k]||{};return g.col||draft.disciplines.includes(discKey)||x.grade||x.role;}).map(g=>{const x=(draft.climbGrades||{})[g.k]||{};const cur=(g.col?draft[g.col]:x.grade)||"";const curOk=cur&&cur!=="N/A"&&cur!=="-";return <div key={g.k} style={{display:"flex",alignItems:"center",gap:8,marginBottom:7,flexWrap:"wrap"}}><div style={{width:58,flexShrink:0,fontSize:13,fontWeight:700,color:C.textSub}}>{g.label}</div><select aria-label={g.label+" grade"} value={curOk?cur:""} onChange={e=>{const v=e.target.value;if(g.col)set(g.col,v);else setCG(g.k,"grade",v);}} style={{...inp,width:"auto",flex:"1 1 96px",minWidth:90,padding:"8px 10px"}}><option value="">—</option>{curOk&&!g.ladder.includes(cur)?<option value={cur}>{cur}</option>:null}{g.ladder.map(v=><option key={v} value={v}>{v}</option>)}</select>{g.roped?<div style={{display:"flex",gap:5}}>{CLIMB_ROLES.map(r=>{const on=x.role===r[0];return <button key={r[0]} type="button" onClick={()=>setCG(g.k,"role",on?"":r[0])} aria-pressed={on} aria-label={g.label+": "+r[1]} style={{padding:"8px 11px",borderRadius:9,border:"1px solid "+(on?C.blue:C.border),background:on?C.blueBg:C.surface,color:on?C.blue:C.textSub,fontSize:12,fontWeight:700,cursor:"pointer",whiteSpace:"nowrap"}}>{r[1]}</button>;})}</div>:null}</div>;})}
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,background:C.surface,border:"1px solid "+C.border,borderRadius:11,padding:"11px 13px",marginTop:18}}>
        <div style={{minWidth:0}}><div style={{fontSize:13,fontWeight:600,color:C.text}}>Show my real name publicly</div><div style={{fontSize:12,color:C.textMuted,marginTop:2}}>{"Off means others see @"+(draft.username.trim()||"username")+" instead of your name."}</div></div>
        <button onClick={()=>set("showRealName",!draft.showRealName)} aria-label="Toggle real name" role="switch" aria-checked={draft.showRealName} style={{flexShrink:0,width:46,height:26,borderRadius:13,border:"none",background:draft.showRealName?C.green:C.border,position:"relative",cursor:"pointer"}}><span style={{position:"absolute",top:3,left:draft.showRealName?23:3,width:20,height:20,borderRadius:10,background:"#fff"}}></span></button>
      </div>
      <div style={{borderTop:"1px solid "+C.border,marginTop:20,paddingTop:14}}><div style={{fontSize:13,fontWeight:800,color:C.text,textTransform:"uppercase",letterSpacing:0.4,marginBottom:8,borderLeft:"3px solid "+C.blue,paddingLeft:9}}>Certifications</div><div style={{fontSize:11.5,color:C.textMuted,marginBottom:9,lineHeight:1.45}}>Certifications add to your trust score. Add the expiry date and your profile shows when one has lapsed — in-app verification comes later.</div>{(draft.certifications||[]).length?<div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:10}}>{(draft.certifications||[]).map((c,i)=>{const ex=certExpiryInfo((draft.certExpiry||{})[c]);return <span key={i} style={{display:"inline-flex",alignItems:"center",gap:7,fontSize:12,color:ex&&ex.expired?C.amber:C.green,background:ex&&ex.expired?C.amberBg:C.greenBg,border:"1px solid "+(ex&&ex.expired?C.amber:C.greenDim),padding:"4px 6px 4px 10px",borderRadius:8}}>{c}{ex?" · "+ex.label:""}<button onClick={()=>setDraft(d=>{const ce={...(d.certExpiry||{})};delete ce[c];return {...d,certExpiry:ce,certifications:(d.certifications||[]).filter((_,j)=>j!==i)};})} aria-label={"Remove certification "+c} style={Object.assign({},POP_REMOVE,{marginLeft:4})}>✕</button></span>;})}</div>:<div style={{fontSize:12,color:C.textMuted,marginBottom:10}}>No certifications added yet.</div>}<div style={{display:"flex",gap:7,marginBottom:7}}><input aria-label="Add a certification" value={ncert} onChange={e=>setNcert(e.target.value)} placeholder="e.g. Wilderness First Responder" style={{flex:2,minWidth:0,padding:"9px 11px",borderRadius:9,border:"1px solid "+C.border,background:C.surface,color:C.text,fontSize:13.5,outline:"none"}}/><input aria-label="Expiry date (optional)" type="date" value={nexp} onChange={e=>setNexp(e.target.value)} style={{flex:1,minWidth:0,padding:"9px 11px",borderRadius:9,border:"1px solid "+C.border,background:C.surface,color:C.text,fontSize:13.5,outline:"none",colorScheme:"dark"}}/></div><button onClick={()=>{const n=ncert.trim();if(!n)return;setDraft(d=>{const list=d.certifications||[];const ce={...(d.certExpiry||{})};if(nexp)ce[n]=nexp;else delete ce[n];return {...d,certifications:list.includes(n)?list:[...list,n],certExpiry:ce};});setNcert("");setNexp("");}} disabled={!ncert.trim()} style={{width:"100%",padding:"9px",borderRadius:9,border:"1px solid "+C.blueDim,background:ncert.trim()?C.blueBg:C.surface,color:ncert.trim()?C.blue:C.textMuted,fontSize:13,fontWeight:700,cursor:ncert.trim()?"pointer":"default"}}>+ Add certification</button>
        <div style={{fontSize:13,fontWeight:800,color:C.text,textTransform:"uppercase",letterSpacing:0.4,margin:"20px 0 8px",borderLeft:"3px solid "+C.blue,paddingLeft:9}}>Belay devices</div><div style={{fontSize:11.5,color:C.textMuted,marginBottom:9,lineHeight:1.45}}>Tap how well you use each device you belay with. Tap again to clear it.</div>{BELAY_DEVICES.map(dv=>{const cur=(draft.belayDevices||{})[dv[0]];return <div key={dv[0]} style={{display:"flex",alignItems:"center",gap:8,marginBottom:6,flexWrap:"wrap"}}><div style={{flex:"1 1 150px",minWidth:0,fontSize:13,color:cur?C.text:C.textSub,fontWeight:600}}>{dv[1]}</div><div style={{display:"flex",gap:5}}>{BELAY_LEVELS.map(L=>{const on=cur===L;return <button key={L} type="button" onClick={()=>setBelay(dv[0],L)} aria-pressed={on} aria-label={dv[1]+": "+L} style={{padding:"7px 10px",borderRadius:9,border:"1px solid "+(on?C.blue:C.border),background:on?C.blueBg:C.surface,color:on?C.blue:C.textSub,fontSize:12,fontWeight:700,cursor:"pointer"}}>{L}</button>;})}</div></div>;})}
        <div style={{fontSize:13,fontWeight:800,color:C.text,textTransform:"uppercase",letterSpacing:0.4,margin:"20px 0 8px",borderLeft:"3px solid "+C.blue,paddingLeft:9}}>Safety skills</div><div style={{fontSize:11.5,color:C.textMuted,marginBottom:9,lineHeight:1.45}}>Tap the skills you are solid on. These are the same skills a partner can vouch for.</div>{SKILL_GROUPS.map(gr=><div key={gr.label} style={{marginBottom:9}}><div style={{fontSize:11.5,fontWeight:700,color:C.textMuted,marginBottom:5}}>{gr.label}</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{gr.keys.map(k=>{const L=SKILLS[k].label;const on=(draft.skills||[]).includes(L);return <button key={k} type="button" onClick={()=>toggleSkill(L)} aria-pressed={on} style={{padding:"7px 11px",borderRadius:14,border:"1px solid "+(on?C.green:C.border),background:on?C.greenBg:C.surface,color:on?C.green:C.textSub,fontSize:12,fontWeight:600,cursor:"pointer"}}>{L}</button>;})}</div></div>)}
        <div style={{fontSize:11.5,fontWeight:700,color:C.textMuted,margin:"4px 0 5px"}}>Other skills</div>{(()=>{const std=new Set(Object.keys(SKILLS).map(k=>SKILLS[k].label));const other=(draft.skills||[]).filter(x=>!std.has(x));return other.length?<div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:10}}>{other.map(sk=><span key={sk} style={{display:"inline-flex",alignItems:"center",gap:7,fontSize:12,color:C.text,background:C.surface,border:"1px solid "+C.border,padding:"4px 6px 4px 10px",borderRadius:8}}>{sk}<button onClick={()=>setDraft(d=>({...d,skills:(d.skills||[]).filter(x=>x!==sk)}))} aria-label={"Remove skill "+sk} style={Object.assign({},POP_REMOVE,{marginLeft:4})}>✕</button></span>)}</div>:null;})()}<div style={{display:"flex",gap:7}}><input aria-label="Add a skill" value={nskill} onChange={e=>setNskill(e.target.value)} placeholder="e.g. Crack climbing, aid soloing" style={{flex:1,minWidth:0,padding:"9px 11px",borderRadius:9,border:"1px solid "+C.border,background:C.surface,color:C.text,fontSize:13.5,outline:"none"}}/><button onClick={()=>{const n=nskill.trim();if(!n)return;setDraft(d=>(d.skills||[]).includes(n)?d:({...d,skills:[...(d.skills||[]),n]}));setNskill("");}} disabled={!nskill.trim()} style={{flexShrink:0,padding:"9px 16px",borderRadius:9,border:"1px solid "+C.blueDim,background:nskill.trim()?C.blueBg:C.surface,color:nskill.trim()?C.blue:C.textMuted,fontSize:13,fontWeight:700,cursor:nskill.trim()?"pointer":"default"}}>Add</button></div></div>
      <div style={{borderTop:"1px solid "+C.border,marginTop:20,paddingTop:14}}>
        <div style={{fontSize:13,fontWeight:800,color:C.text,textTransform:"uppercase",letterSpacing:0.4,marginBottom:8,borderLeft:"3px solid "+C.blue,paddingLeft:9}}>How climbers will see you</div>
        <div style={{background:C.card,border:"1px solid "+C.border,borderRadius:13,padding:14}}>
          <div style={{display:"flex",gap:12,alignItems:"center"}}><Av src={draft.avatar} size={48}/><div style={{minWidth:0}}>
            <div style={{fontSize:16,fontWeight:700,color:C.text}}>{draft.showRealName?(draft.name.trim()||"Your name"):("@"+(draft.username.trim()||"username"))}</div>
            <div style={{fontSize:12,color:C.textSub,marginTop:1}}>{<Lbl s={"📍 "+(draft.location.trim()||"Location")+(draft.level?" · "+draft.level:"")}/>}</div>
          </div></div>
          {draft.bio.trim()?<div style={{fontSize:13,color:C.textSub,lineHeight:1.5,marginTop:10}}>{draft.bio}</div>:null}
          <div style={{display:"flex",flexWrap:"wrap",gap:5,marginTop:10}}>{draft.disciplines.map(d=><span key={d} style={{fontSize:12,color:C.textSub,background:C.surface,border:"1px solid "+C.border,borderRadius:6,padding:"2px 8px"}}>{d}</span>)}</div>
          <div style={{fontSize:11.5,color:C.textMuted,marginTop:9}}>{profileGradeRows(draft).map(g=>g.label+(g.grade?" "+g.grade:"")+(g.role?" ("+roleLabel(g.role)+")":"")).join(" · ")}</div>
        </div>
        <div style={{fontSize:12,color:C.textMuted,marginTop:8,lineHeight:1.4}}>This preview reflects your privacy settings. Your real name stays hidden behind your @username unless the toggle above is on.</div>
      </div>
    </div>
  </div>);
}
