// Moved out of ClimbMatchCore.jsx verbatim so it can load lazily, off the first-paint
// bundle. It is rendered only from App (ClimbMatch.jsx) behind React.lazy + Suspense.
import { clickable } from "./clickable";
import { searchMatches } from "./search";
import { useProfilesByIds } from "./db";
import { useState } from "react";
import { ActionIcon, Av, C, CLIMBERS, ME, ROUTES, SZ5, SwipeRow, crewSize, pubName, vScore } from "../ClimbMatchCore.jsx";

export default function Inbox({dmUnavailable,dmLoading,msgs,crews,crewMsgs,connections,onOpenDM,onOpenCrew,onClose,onDeleteDM,onDeleteCrew,msgFrom,onAcceptReq,crewUnread,dmUnread,routeById}){
  const [itab,setItab]=useState("friends");const [msgQ,setMsgQ]=useState("");const mqOk=str=>!msgQ.trim()||(str||"").toLowerCase().includes(msgQ.trim().toLowerCase());
  const dmIds=Object.keys(msgs||{}).filter(id=>(msgs[id]||[]).length>0);
  const _realDmIds=dmIds.filter(id=>!/^\d+$/.test(id));const dmProfilesQ=useProfilesByIds(_realDmIds);
  const dmThreads=dmIds.map(id=>{const c=/^\d+$/.test(id)?(+id===0?ME:CLIMBERS.find(x=>x.id===+id)):((dmProfilesQ.data||[]).find(p=>p.id===id));const arr=msgs[id]||[];return c?{c:c,last:arr[arr.length-1]}:null;}).filter(Boolean).sort((a,b)=>((b.last&&b.last.ts)||0)-((a.last&&a.last.ts)||0));  const crewThreads=(crews||[]).map(cr=>{const r=(routeById?routeById(cr.routeId):ROUTES.find(x=>x.id===cr.routeId))||{};const arr=(crewMsgs&&crewMsgs[cr.id])||[];return {cr:cr,r:r,last:arr.length?arr[arr.length-1]:null,count:arr.length,un:(crewUnread&&crewUnread[cr.id])||0};}).filter(t=>t.count||t.un).sort((a,b)=>(b.un-a.un)||(((b.last&&b.last.ts)||0)-((a.last&&a.last.ts)||0)));
  const friendsNoDM=(connections||[]).filter(f=>dmIds.indexOf(String(f.id))<0);
  const lastTxt=m=>m?((m.from==="me"?"You: ":"")+(m.image?"Photo":m.text)):null;
  const row={display:"flex",alignItems:"center",gap:10,padding:"11px 12px",marginBottom:0,background:C.card,border:"1px solid "+C.border,borderRadius:12};
  const lbl={fontSize:12,color:C.textMuted,textTransform:"uppercase",letterSpacing:0.4,marginBottom:7,fontWeight:700};
  const prev={fontSize:12.5,color:C.textSub,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",fontWeight:400,letterSpacing:0.1,marginTop:1};
  const del={background:"transparent",border:"none",color:C.textMuted,fontSize:16,cursor:"pointer",flexShrink:0,padding:"4px 6px",lineHeight:1};
  return (<div style={{position:"fixed",inset:0,background:C.bg,zIndex:1100,overflowY:"auto",overscrollBehavior:"contain",maxWidth:520,margin:"0 auto",boxSizing:"border-box"}}>
    <div style={{position:"sticky",top:0,background:C.surface,borderBottom:"1px solid "+C.border,padding:"12px 16px",display:"flex",alignItems:"center",gap:10,zIndex:2}}>
      <button onClick={onClose} style={{background:C.card,border:"1px solid "+C.border,color:C.text,borderRadius:8,padding:"12px 14px",fontSize:16,fontWeight:700,cursor:"pointer"}}>← Back</button>
      <div style={{fontSize:15,fontWeight:700,color:C.text}}>Messages</div>
    </div>
    <div style={{maxWidth:560,margin:"0 auto",padding:"14px 16px 40px",color:C.text}}>
      <div style={{display:"flex",gap:8,marginBottom:14}}>{[["friends","Friends",dmThreads.length],["crews","Crews",crewThreads.length]].map(z=><button key={z[0]} onClick={()=>setItab(z[0])} aria-label={z[2]?z[1]+", "+z[2]:z[1]} aria-current={itab===z[0]?"true":undefined} style={{flex:1,padding:"9px 4px",borderRadius:11,border:"1px solid "+(itab===z[0]?C.blue:C.border),cursor:"pointer",background:itab===z[0]?C.blueSolid:C.card,color:itab===z[0]?"#fff":C.textSub,fontSize:13,fontWeight:700}}>{z[1]}{z[2]?<span style={{marginLeft:5,fontSize:12,fontWeight:800,opacity:0.85}}>{z[2]}</span>:null}</button>)}</div>
      {(dmThreads.length||crewThreads.length)?<div style={{display:"flex",alignItems:"center",gap:8,background:C.card,border:"1px solid "+C.border,borderRadius:10,padding:"0 11px",marginBottom:12}}><span style={{display:"inline-flex",color:C.textMuted}}><ActionIcon name="search" size={13} color={C.textMuted}/></span><input aria-label="Search messages" value={msgQ} onChange={e=>setMsgQ(e.target.value)} placeholder="Search messages…" style={{flex:1,padding:"9px 0",border:"none",background:"transparent",color:C.text,fontSize:13.5,outline:"none"}}/></div>:null}{itab==="friends"?(()=>{const isFr=t=>(connections||[]).some(c=>c.id===t.c.id);const crewMateIds=new Set();(crews||[]).forEach(c=>(c.members||[]).forEach(m=>{if(m&&m.status==="confirmed"&&m.climberId!=null)crewMateIds.add(String(m.climberId));}));const isCrewMate=t=>crewMateIds.has(String(t.c.id));const mainT=(msgFrom==="everyone"?dmThreads:msgFrom==="requests"?dmThreads.filter(isFr):dmThreads.filter(t=>isFr(t)||isCrewMate(t))).filter(t=>mqOk((t.c.name||"")+" @"+(t.c.username||"")));const reqT=msgFrom==="requests"?dmThreads.filter(t=>!isFr(t)):[];return <div>
        {reqT.length?<div style={{marginBottom:12}}><div style={lbl}>Message requests ({reqT.length})</div>{reqT.map(t=><div key={t.c.id} style={row}><div {...clickable(()=>onOpenDM(t.c))} style={SZ5}><Av src={t.c.avatar} size={42} online={t.c.online}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:14,fontWeight:700}}>{pubName(t.c)}</div><div style={prev}>{lastTxt(t.last)||"Wants to message you"}</div></div></div><div style={{display:"flex",gap:6,flexShrink:0}}><button onClick={()=>onAcceptReq(t.c.id)} style={{padding:"8px 12px",borderRadius:8,border:"none",background:C.green,color:"#04110a",fontSize:12,fontWeight:700,cursor:"pointer"}}>✓ Accept friend</button><button onClick={()=>onDeleteDM(t.c.id)} style={{padding:"8px 12px",borderRadius:8,border:`1px solid ${C.border}`,background:"transparent",color:C.textMuted,fontSize:12,fontWeight:700,cursor:"pointer"}}>Decline</button></div></div>)}</div>:null}
        <div className="cm-stagger">{mainT.map(function(t){var nu=(dmUnread||{})[t.c.id]||0;return <SwipeRow key={t.c.id} onDelete={()=>onDeleteDM(t.c.id)}><div style={row}><div {...clickable(()=>onOpenDM(t.c))} style={SZ5}><Av src={t.c.avatar} size={42} online={t.c.online}/><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"center",gap:5,minWidth:0}}><span style={{fontSize:14,fontWeight:700,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{pubName(t.c)}</span><span style={{flexShrink:0,fontSize:10.5,fontWeight:800,color:vScore(t.c)>=90?C.green:vScore(t.c)>=70?C.blue:C.textMuted}}>{vScore(t.c)}</span></div>{(()=>{var sh=(t.c.objectiveIds||[]).filter(function(id){return (ME.objectiveIds||[]).indexOf(id)>=0;});var sr=sh.length?ROUTES.find(function(r){return r.id===sh[0];}):null;return sr?<div style={{fontSize:11,color:C.blue,fontWeight:600,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",marginTop:1}}>{"↳ both want "+sr.name}</div>:null;})()}<div style={nu>0?Object.assign({},prev,{color:C.text,fontWeight:600}):prev}>{lastTxt(t.last)||"Tap to open"}</div></div></div>{nu>0?<span style={{flexShrink:0,minWidth:18,height:18,borderRadius:9,background:C.blueSolid,color:"#fff",fontSize:11,fontWeight:800,display:"flex",alignItems:"center",justifyContent:"center",padding:"0 5px"}}>{nu}</span>:null}</div></SwipeRow>;})}</div>
        {friendsNoDM.length?<div style={{marginTop:dmThreads.length?10:0}}><div style={lbl}>Start a chat</div><div style={{display:"flex",gap:12,flexWrap:"wrap"}}>{friendsNoDM.map(f=><button key={f.id} onClick={()=>onOpenDM(f)} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:5,background:"transparent",border:"none",cursor:"pointer",width:64}}><Av src={f.avatar} size={46} online={f.online}/><span style={{fontSize:12,color:C.textSub,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",maxWidth:64}}>{f.name.split(" ")[0]}</span></button>)}</div></div>:null}
        {(!mainT.length&&!reqT.length&&!friendsNoDM.length)?<div style={{textAlign:"center",padding:"48px 20px",color:C.textMuted}}><div style={{display:"flex",justifyContent:"center",marginBottom:10}}><ActionIcon name="chat" size={34} color={C.textMuted}/></div><div style={{fontSize:12,color:C.textMuted,fontWeight:600,marginBottom:5}}>{dmUnavailable?"Couldn't load your chats":dmLoading?"Loading your chats…":"No friend chats yet"}</div>{dmLoading&&!dmUnavailable?null:<div style={{fontSize:13,lineHeight:1.6}}>{dmUnavailable?"Your conversations are still here — this list just couldn't be loaded. Try again in a moment.":"Message a partner from their profile and your chats will live here."}</div>}</div>:null}
      </div>;})():null}
      {itab==="crews"?<div>
        {crewThreads.filter(t=>(!msgQ.trim()||searchMatches(msgQ,t.r.name))).length?crewThreads.filter(t=>(!msgQ.trim()||searchMatches(msgQ,t.r.name))).map(t=><SwipeRow key={t.cr.id} onDelete={()=>onDeleteCrew(t.cr.id)}><div style={row}><div {...clickable(()=>onOpenCrew(t.cr))} style={SZ5}><div style={{width:42,height:42,borderRadius:10,background:C.blueBg,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><ActionIcon name="crews" size={20} color={C.blue}/></div><div style={{flex:1,minWidth:0}}><div style={{fontSize:14,fontWeight:700}}>{t.r.name||"Crew"}{t.un?<span style={{marginLeft:6,fontSize:12,fontWeight:800,color:"#fff",background:C.blueSolid,borderRadius:9,padding:"1px 7px",verticalAlign:"middle"}}>{t.un+" new"}</span>:null}</div><div style={prev}>{lastTxt(t.last)||(crewSize(t.cr)+" climber"+(crewSize(t.cr)===1?"":"s")+" · tap to open")}</div></div></div></div></SwipeRow>):<div style={{textAlign:"center",padding:"48px 20px",color:C.textMuted}}><div style={{display:"flex",justifyContent:"center",marginBottom:10}}><ActionIcon name="chat" size={34} color={C.textMuted}/></div><div style={{fontSize:12,color:C.textMuted,fontWeight:600,marginBottom:5}}>No crew chats yet</div><div style={{fontSize:13,lineHeight:1.6}}>Start a crew on a climb and the conversation shows up here.</div></div>}
      </div>:null}
    </div>
  </div>);
}
