// Moved out of ClimbMatchCore.jsx verbatim so it can load lazily, off the first-paint
// bundle. It is rendered only from App (ClimbMatch.jsx) behind React.lazy + Suspense.
import { clickable } from "./clickable";
import { useEffect, useState } from "react";
import { C, CAT, CLIMBERS, DiscIcon, HERO_BG, HERO_SHEEN, ROUTES, catOf, mtnOf, pubFirst, renderMD } from "../ClimbMatchCore.jsx";

export default function MyAscents({logs,onOpen,onReport,onVouch,onView,focusId,routeById,condReports,onReportCond,logsUnavailable,climberFor}){
  const [asort,setASort]=useState("new");const [adisc,setADisc]=useState("all");const [hl,setHl]=useState(null);useEffect(function(){if(!focusId)return;var idx=-1,bestDate="";logs.forEach(function(l,i){if(l.routeId===focusId&&(l.date||"")>=bestDate){bestDate=l.date||"";idx=i;}});if(idx<0)return;setHl(idx);var el=document.getElementById("asc-"+idx);if(el)el.scrollIntoView({behavior:"smooth",block:"center"});var tm=setTimeout(function(){setHl(null);},2600);return function(){clearTimeout(tm);};},[focusId,logs]);
  const MN=["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  const fmt=d=>{if(!d)return"";const q=d.split("-");return (MN[parseInt(q[1])]||"")+" "+(q[2]?parseInt(q[2])+", ":"")+q[0];};
  const tickCol=t=>t==="Onsight"||t==="Flash"?C.green:t==="Redpoint"||t==="Lead"?C.blue:t==="Fell"||t==="Hung"?C.amber:C.textSub;
  const _enr=logs.map((l,i)=>({l,i})).map(o=>{const r=(routeById?routeById(o.l.routeId):ROUTES.find(x=>x.id===o.l.routeId));return r?{l:o.l,i:o.i,_disc:catOf(r)}:null;}).filter(Boolean);const _discs=Array.from(new Set(_enr.map(o=>o._disc)));const list=_enr.filter(o=>adisc==="all"||o._disc===adisc).sort((a,b)=>asort==="old"?(a.l.date||"").localeCompare(b.l.date||""):asort==="stars"?(((b.l.stars||0)-(a.l.stars||0))||(b.l.date||"").localeCompare(a.l.date||"")):(b.l.date||"").localeCompare(a.l.date||""));
  return <div>
    <div style={{background:HERO_BG,boxShadow:HERO_SHEEN,borderRadius:14,padding:16,marginBottom:14,border:"1px solid "+C.border}}><div style={{fontSize:16,fontWeight:700,marginBottom:3}}>✓ My Ascents</div><div style={{fontSize:12,color:C.textMuted}}>{logsUnavailable?"Couldn’t load your climbs — this count is not your record.":logs.length+" logged · every send builds your verified résumé."}</div></div>
    {logs.length>1?<div style={{marginBottom:11}}><select aria-label="Sort areas" value={asort} onChange={e=>setASort(e.target.value)} style={{width:"100%",padding:"8px 11px",borderRadius:9,border:`1px solid ${C.border}`,background:C.surface,color:C.text,fontSize:12.5,cursor:"pointer",marginBottom:8}}>{[["new","Newest first"],["old","Oldest first"],["stars","Top rated"]].map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>{_discs.length>1?<div className="cm-hscroll" style={{display:"flex",gap:6,overflowX:"auto",paddingBottom:5}}>{[["all","All"]].concat(_discs.map(d=>[d,(CAT[d]||{}).label||d])).map(x=><button key={x[0]} onClick={()=>setADisc(x[0])} aria-current={adisc===x[0]?"true":undefined} style={{flexShrink:0,whiteSpace:"nowrap",padding:"9px 11px",borderRadius:20,border:`1px solid ${adisc===x[0]?C.blue:C.border}`,background:adisc===x[0]?C.blueBg:"transparent",color:adisc===x[0]?C.blue:C.textSub,fontSize:12,fontWeight:600,cursor:"pointer"}}><span style={{display:"inline-flex",alignItems:"center",gap:5}}>{x[0]!=="all"?<DiscIcon d={x[0]} size={13}/>:null}{x[1]}</span></button>)}</div>:null}</div>:null}{logs.length===0?<div style={{background:C.card,borderRadius:12,padding:"22px 16px",border:`1px solid ${C.border}`,textAlign:"center"}}><div style={{fontSize:31,marginBottom:8}}>✓</div><div style={{fontSize:12,fontWeight:600,marginBottom:5,color:C.textMuted}}>{logsUnavailable?"Couldn’t load your climbs":"Log your completed climbs here"}</div><div style={{fontSize:13,color:C.textMuted,lineHeight:1.6}}>{logsUnavailable?"Your logged climbs didn’t load, so this is not an empty logbook — check your connection and try again.":"Open any climb and tap “Log ascent” to record a send. Logged climbs build the catch ledger and résumé that partners trust."}</div></div>
    :<div style={{display:"flex",flexDirection:"column",gap:8}}>{list.map(({l,i},ix)=>{const r=(routeById?routeById(l.routeId):ROUTES.find(x=>x.id===l.routeId));if(!r)return null;const cat=CAT[catOf(r)]||{};/* climberFor resolves a REAL partner id (uuid) through your connections; CLIMBERS.find alone offered a vouch only for seed partners. */const vp=(l.partnerIds&&l.partnerIds.length?l.partnerIds.map(pid=>(climberFor?climberFor(pid):CLIMBERS.find(c=>c.id===pid))):(l.partners||[]).map(pn=>CLIMBERS.find(c=>c.name===pn||(pn&&c.name.split(" ")[0]===String(pn).split(" ")[0])))).filter(Boolean)[0];return <div key={i} id={"asc-"+i} {...clickable(()=>onOpen(r))} style={{background:i===hl?C.blueBg:C.card,borderRadius:11,padding:"11px 13px",border:"1px solid "+(i===hl?C.blue:C.border),cursor:"pointer",transition:"background 0.3s,border-color 0.3s"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8}}><div style={{display:"flex",alignItems:"baseline",gap:8,minWidth:0}}><span style={{fontSize:12,fontWeight:800,color:C.textMuted,flexShrink:0}}>{ix+1}.</span><div style={{fontSize:14.5,fontWeight:700,minWidth:0}}>{r.name}</div></div><div style={{fontSize:12,color:C.amber,flexShrink:0,letterSpacing:1}}>{"★".repeat(l.stars||0)}</div></div><div style={{display:"flex",alignItems:"center",gap:7,marginTop:4,flexWrap:"wrap"}}><span style={{fontSize:12,fontWeight:700,color:tickCol(l.tickType),background:C.surface,border:`1px solid ${C.border}`,borderRadius:6,padding:"2px 7px"}}>{l.tickType||"Logged"}</span><span style={{fontSize:12,color:C.textMuted,display:"inline-flex",alignItems:"center",gap:5}}><DiscIcon d={catOf(r)} size={14}/>{mtnOf(r)+" · "+r.grade}</span><span style={{fontSize:12,color:C.textMuted,marginLeft:"auto"}}>{fmt(l.date)}</span></div>{l.text?<div style={{fontSize:12.5,color:C.textSub,marginTop:7,lineHeight:1.5}}>{renderMD(l.text)}</div>:null}{l.caughtByName?<div style={{fontSize:11.5,color:C.amber,marginTop:5}}>Caught by {l.caughtByName.split(" ")[0]}</div>:null}<div onClick={e=>e.stopPropagation()} style={{display:"flex",gap:7,marginTop:9}}><button onClick={function(e){e.stopPropagation();onReport&&onReport(l,i);}} style={{flex:1,padding:"7px",borderRadius:8,border:"1px solid "+C.border,background:l.text?"none":C.surface,color:l.text?C.textSub:C.blue,fontSize:12,fontWeight:l.text?600:700,cursor:"pointer"}}>{l.text?"Edit report":"Add trip report"}</button>{l.text?<button onClick={function(e){e.stopPropagation();onView&&onView(l,i,r);}} style={{flexShrink:0,padding:"7px 11px",borderRadius:8,border:"1px solid "+C.blueDim,background:C.blueBg,color:C.blue,fontSize:12,fontWeight:700,cursor:"pointer"}}>View & share</button>:null}{vp?<button onClick={()=>onVouch&&onVouch(vp)} style={{flex:1,padding:"7px",borderRadius:8,border:"1px solid "+C.border,background:C.surface,color:C.green,fontSize:12,fontWeight:700,cursor:"pointer"}}>{"Vouch "+(vp._conn?pubFirst(vp):vp.name.split(" ")[0])}</button>:null}</div></div>;})}</div>}
    {condReports&&condReports.length?<div style={{marginTop:18}}><div style={{fontSize:13,fontWeight:800,color:C.text,letterSpacing:0.4,textTransform:"uppercase",borderLeft:"3px solid "+C.teal,paddingLeft:9,marginBottom:9}}>Conditions reports</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{condReports.map((cr,i)=>{const r=(routeById?routeById(cr.routeId):ROUTES.find(x=>x.id===cr.routeId));if(!r)return null;return <div key={"cr"+i} {...clickable(()=>onOpen(r,"conditions"))} style={{background:C.card,borderRadius:11,padding:"11px 13px",border:"1px solid "+C.border,cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8}}><div style={{fontSize:14.5,fontWeight:700,minWidth:0}}>{r.name}</div><span style={{fontSize:11.5,fontWeight:700,color:C.teal,background:C.tealDim,borderRadius:6,padding:"2px 8px",flexShrink:0}}>Conditions</span></div><div style={{fontSize:12,color:C.textMuted,marginTop:4,display:"flex",alignItems:"center",gap:5}}><DiscIcon d={catOf(r)} size={14}/>{mtnOf(r)+" · "+fmt(cr.date)}</div>{cr.text?<div style={{fontSize:12.5,color:C.textSub,marginTop:7,lineHeight:1.5}}>{renderMD(cr.text)}</div>:null}<div onClick={e=>e.stopPropagation()} style={{display:"flex",gap:7,marginTop:9}}><button onClick={function(e){e.stopPropagation();onReportCond&&onReportCond(cr,i);}} style={{flex:1,padding:"7px",borderRadius:8,border:"1px solid "+C.border,background:C.surface,color:C.blue,fontSize:12,fontWeight:700,cursor:"pointer"}}>Edit report</button></div></div>;})}</div></div>:null}
  </div>;
}
