// Moved out of ClimbMatchCore.jsx verbatim so it can load lazily, off the first-paint
// bundle. It is rendered only from App (ClimbMatch.jsx) behind React.lazy + Suspense.
import { clickable } from "./clickable";
import { useState } from "react";
import { ActionIcon, Av, C, CLIMBERS, SL, SwipeRow, notifTarget, pubName, vScore } from "../ClimbMatchCore.jsx";

export default function NotifPanel({requests,notifs,onAccept,onDecline,onOpenProfile,onGo,onClose,onDismiss,onClearAll,archived,onRestore}){const [archOpen,setArchOpen]=useState(false);
  const av=id=>{const c=CLIMBERS.find(x=>x.id===id);return c?c.avatar:null;};
  const empty=!requests.length&&!notifs.length;
  return <div onClick={onClose} role="dialog" aria-label="Notifications" aria-modal="true" style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.85)",zIndex:1200,overflowY:"auto",overscrollBehavior:"contain",display:"flex",alignItems:"flex-start",justifyContent:"center",padding:"12px 8px"}}>
    <div onClick={e=>e.stopPropagation()} style={{background:C.surface,borderRadius:18,width:"100%",maxWidth:440,border:`1px solid ${C.border}`,overflow:"hidden"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 16px",borderBottom:`1px solid ${C.border}`}}><div style={{color:C.text,fontSize:17,fontWeight:700,borderLeft:"3px solid "+C.blue,paddingLeft:9}}>Notifications</div><div style={{display:"flex",alignItems:"center",gap:8}}>{notifs.length?<button onClick={()=>onClearAll&&onClearAll()} style={{background:C.card,border:`1px solid ${C.border}`,color:C.textSub,borderRadius:8,padding:"0 11px",height:30,fontSize:12.5,fontWeight:700,cursor:"pointer"}}>Clear all</button>:null}<button onClick={onClose} style={{background:C.card,border:`1px solid ${C.border}`,color:C.textSub,borderRadius:8,width:36,height:36,fontSize:16,cursor:"pointer"}} aria-label="Close">×</button></div></div>
      <div style={{padding:"12px 14px",maxHeight:"72vh",overflowY:"auto",overscrollBehavior:"contain"}}>
        {requests.length?<div style={{marginBottom:14}}><SL>Friend requests</SL>{/* The two buttons never shrank and the name column had no floor, so at 360px the
        middle column collapsed to ~90px: "wants to be your climbing friend · 53" wrapped
        into a four-line tower that swallowed the 40px avatar beside it. The row now wraps
        — the buttons drop to their own line before the name is allowed to get that narrow —
        and both lines of text ellipsize rather than stacking. */}
      {requests.map(c=><div key={c.id} style={{display:"flex",alignItems:"center",gap:10,rowGap:8,marginBottom:9,flexWrap:"wrap"}}><div {...clickable(()=>onOpenProfile(c))} style={{cursor:"pointer",flexShrink:0}}><Av src={c.avatar} size={40}/></div><div {...clickable(()=>onOpenProfile(c))} style={{flex:"1 1 140px",minWidth:140,cursor:"pointer"}}><div style={{fontSize:14,fontWeight:600,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{pubName(c)}</div><div style={{fontSize:12,color:C.textMuted,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{(c._conn||c._real||c._profile||typeof c.id==="string")?"wants to be your climbing friend":("wants to be your climbing friend · "+vScore(c))}</div></div><div style={{display:"flex",gap:8,flexShrink:0,marginLeft:"auto"}}><button onClick={()=>onAccept(c)} style={{flexShrink:0,padding:"6px 12px",background:C.greenChip,color:C.green,border:"none",borderRadius:8,fontSize:13,fontWeight:700,cursor:"pointer",whiteSpace:"nowrap"}}>✓ Accept friend</button><button onClick={()=>onDecline(c.id)} style={{flexShrink:0,padding:"6px 10px",background:C.card,color:C.textMuted,border:`1px solid ${C.border}`,borderRadius:8,fontSize:13,cursor:"pointer",whiteSpace:"nowrap"}}>Decline</button></div></div>)}</div>:null}
        {notifs.length?<div><SL>Activity</SL>{notifs.map(n=>{const a=n.climberId!=null?av(n.climberId):null;const _t=notifTarget(n);const tappable=!!_t;return <SwipeRow key={n.id} radius={11} onDelete={()=>onDismiss&&onDismiss(n.id)}><div {...(_t?clickable(()=>{if(_t.kind==="profile"){const c=CLIMBERS.find(x=>x.id===_t.climberId);if(c)onOpenProfile(c);}else{onGo(_t.to);}}):{})} style={{display:"flex",alignItems:"center",gap:11,padding:"9px 11px",background:C.bg,cursor:tappable?"pointer":"default"}}><div style={{position:"relative",flexShrink:0}}>{a?<Av src={a} size={36}/>:<div style={{width:36,height:36,borderRadius:"50%",background:C.card,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18}}>{/* n.icon is an ActionIcon NAME ("user", "crews", "shield"), the same convention the
    Unfinished business list uses — rendering it bare printed the word instead of an icon. */}
                <ActionIcon name={n.icon||(n.goto?"calendar":(n.route||n.recap)?"log":"bell")} size={17} color={C.textMuted}/></div>}{a&&n.icon?<div style={{position:"absolute",bottom:-3,right:-3,fontSize:13,background:C.surface,borderRadius:"50%",width:18,height:18,display:"flex",alignItems:"center",justifyContent:"center"}}><ActionIcon name={n.icon} size={11} color={C.textMuted}/></div>:null}</div><div style={{flex:1,fontSize:13,color:C.textSub,lineHeight:1.5}}>{n.text}</div>{tappable?<span style={{color:C.blue,fontSize:14,flexShrink:0}}>→</span>:null}</div></SwipeRow>;})}</div>:null}
        {archived&&archived.length?<div style={{marginTop:14}}><div {...clickable(()=>setArchOpen(o=>!o))} style={{display:"flex",alignItems:"center",justifyContent:"space-between",cursor:"pointer",marginBottom:archOpen?8:0}}><SL>{"Archived ("+archived.length+")"}</SL><span style={{fontSize:13,color:C.textMuted}}>{archOpen?"▾":"▸"}</span></div>{archOpen?<div style={{display:"flex",flexDirection:"column",gap:7}}>{archived.map(function(n){return <div key={n.id} style={{display:"flex",alignItems:"center",gap:10,background:C.bg,border:"1px solid "+C.border,borderRadius:11,padding:"9px 11px"}}><span style={{fontSize:16,flexShrink:0,opacity:0.7,display:"flex",alignItems:"center"}}><ActionIcon name={n.icon||"bell"} size={15} color={C.textMuted}/></span><span style={{flex:1,fontSize:12.5,color:C.textMuted,lineHeight:1.4}}>{n.text}</span><button onClick={()=>onRestore&&onRestore(n.id)} style={{flexShrink:0,padding:"5px 11px",borderRadius:8,border:"1px solid "+C.blueDim,background:C.blueBg,color:C.blue,fontSize:12,fontWeight:700,cursor:"pointer"}}>Restore</button></div>;})}</div>:null}</div>:null}{empty?<div style={{textAlign:"center",padding:"34px 0",color:C.textMuted}}><div style={{fontSize:31,marginBottom:8}}>✅</div><div style={{fontSize:14}}>You’re all caught up.</div></div>:null}
      </div>
    </div>
  </div>;
}
