// Moved out of ClimbMatchCore.jsx verbatim so it can load lazily, off the first-paint
// bundle. It is rendered only from App (ClimbMatch.jsx) behind React.lazy + Suspense.
import { USE_DB } from "./supabase";
import { clickable } from "./clickable";
import { useState } from "react";
import { C, DISC, DiscIcon, HERO_BG, HERO_SHEEN, MOUNTAINS, VL, YDSL, fuzzyMatch } from "../ClimbMatchCore.jsx";

export default function Onboarding({onFinish,onSkip,initial,onHelp}){
  const [home,setHome]=useState(initial&&initial.homeArea||"");const [disc,setDisc]=useState(initial&&initial.disciplines||[]);
  const [sg,setSg]=useState(initial&&initial.sportGrade||"N/A");const [tg,setTg]=useState(initial&&initial.tradGrade||"N/A");const [bg,setBg]=useState(initial&&initial.boulderGrade||"N/A");
  const editing=!!(initial&&initial.disciplines&&initial.disciplines.length);const tog=v=>setDisc(d=>d.includes(v)?d.filter(x=>x!==v):[...d,v]);
  const areas=MOUNTAINS.filter(m=>m.id!=="world");
  const [step,setStep]=useState(editing?1:0);const [homeQ,setHomeQ]=useState(()=>{const a=areas.find(x=>x.id===home);return a?a.name:home;});
  return <div onClick={onSkip} role="dialog" aria-label="Edit your profile" aria-modal="true" style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.88)",zIndex:1300,overflowY:"auto",overscrollBehavior:"contain",display:"flex",alignItems:"flex-start",justifyContent:"center",padding:"14px 10px"}}>
    <div onClick={e=>e.stopPropagation()} style={{background:C.surface,borderRadius:18,width:"100%",maxWidth:460,border:`1px solid ${C.border}`,overflow:"hidden"}}>
      <div style={{background:HERO_BG,boxShadow:HERO_SHEEN,padding:"18px 18px 16px"}}><div style={{fontSize:20,fontWeight:800,marginBottom:4}}>{editing?"Edit your profile":"Welcome to ClimbMatch"}</div><div style={{fontSize:13,color:C.textSub,lineHeight:1.5}}>A couple quick questions so we can match you with the right partners and climbs.</div></div>
      {step===0?<div style={{padding:"6px 18px 16px"}}>{[["","Trusted conditions","Beta, live conditions, and trip reports from climbers who were just there."],["","Partners & crews","Find climbers near you, check their vouches and trust, form a crew, and vouch for who you climb with."],["","Plan every climb","Day-by-day itineraries, a what-to-bring gear list, float plans, and live forecasts."],["","Log, list & rank","Track ascents, build and share tick-lists, and see where you land on the leaderboard."]].map(f=><div key={f[0]} style={{display:"flex",gap:12,alignItems:"flex-start",marginBottom:13}}><div style={{fontSize:21,lineHeight:1.1}}>{f[0]}</div><div><div style={{fontSize:13.5,fontWeight:700,color:C.text}}>{f[1]}</div><div style={{fontSize:12,color:C.textSub,lineHeight:1.45}}>{f[2]}</div></div></div>)}<div style={{display:"flex",gap:8,marginTop:18}}><button onClick={onSkip} style={{flex:1,padding:11,background:C.surface,color:C.textSub,border:"1px solid "+C.border,borderRadius:11,fontSize:14,cursor:"pointer",fontWeight:600}}>Skip for now</button><button onClick={()=>setStep(1)} style={{flex:2,padding:11,background:C.green,color:C.bg,border:"none",borderRadius:11,fontSize:14.5,cursor:"pointer",fontWeight:700}}>Set up my profile</button></div><div style={{fontSize:12,color:C.textMuted,marginTop:10,textAlign:"center"}}>Takes about 30 seconds.</div><button onClick={onHelp} style={{display:"block",width:"100%",marginTop:12,padding:"8px",background:"none",border:"1px solid rgba(0,0,0,0.22)",boxSizing:"border-box",color:C.blue,fontSize:12.5,fontWeight:700,cursor:"pointer"}}>{"See how ClimbMatch works & read the FAQ →"}</button></div>:null}
      {step===1?<div style={{padding:16,maxHeight:"60vh",overflowY:"auto",overscrollBehavior:"contain"}}>
        <div style={{fontSize:12,color:C.textMuted,fontWeight:700,marginBottom:6,letterSpacing:0.3}}>WHERE DO YOU MAINLY CLIMB?</div>
        <div style={{position:"relative",marginBottom:16}}><input aria-label="Search a range, canyon, or peak" value={homeQ} onChange={e=>{setHomeQ(e.target.value);setHome("");}} placeholder={USE_DB?"Your city or home area — e.g. Seattle":"Search a range, canyon, or peak..."} style={{width:"100%",padding:"9px 11px",borderRadius:10,border:"1px solid "+(home?C.green:C.border),background:C.card,color:C.text,fontSize:13.5,boxSizing:"border-box"}}/>{!USE_DB&&homeQ&&!home?(()=>{const ms=areas.filter(a=>fuzzyMatch(homeQ,a.name)).slice(0,7);return <div style={{position:"absolute",top:"100%",left:0,right:0,background:C.card,border:"1px solid "+C.border,borderRadius:10,marginTop:4,maxHeight:210,overflowY:"auto",overscrollBehavior:"contain",zIndex:5,boxShadow:"0 12px 30px rgba(0,0,0,0.5)"}}>{ms.length?ms.map(a=><div key={a.id} {...clickable(()=>{setHome(a.id);setHomeQ(a.name);})} style={{padding:"9px 11px",fontSize:13.5,fontWeight:700,cursor:"pointer",borderBottom:"1px solid "+C.borderLight,color:C.text}}>{a.name}</div>):<div style={{padding:"9px 11px",fontSize:12.5,color:C.textMuted}}>No match — keep typing</div>}</div>;})():null}{home?<div style={{fontSize:11.5,color:C.green,marginTop:5,fontWeight:600}}>✓ {homeQ}</div>:null}</div>
        <div style={{fontSize:12,color:C.textMuted,fontWeight:700,marginBottom:8,letterSpacing:0.3}}>WHAT DO YOU DO? <span style={{color:C.red}}>*</span></div>
        <div style={{display:"flex",gap:7,flexWrap:"wrap",marginBottom:16}}>{Object.keys(DISC).map(k=>{const on=disc.includes(k),cat=DISC[k];return <button key={k} onClick={()=>tog(k)} aria-pressed={on} style={{display:"flex",alignItems:"center",gap:5,padding:"7px 12px",borderRadius:16,border:`1.5px solid ${on?cat.color:C.border}`,background:on?cat.bg:C.surface,color:on?cat.color:C.textSub,fontSize:13,fontWeight:600,cursor:"pointer"}}><DiscIcon d={k} size={14}/> {cat.label}</button>;})}</div>
        <div style={{fontSize:12,color:C.textMuted,fontWeight:700,marginBottom:8,letterSpacing:0.3}}>YOUR GRADES <span style={{fontWeight:500,textTransform:"none"}}>(optional)</span></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8}}>{[["Sport",sg,setSg,YDSL],["Trad",tg,setTg,YDSL],["Boulder",bg,setBg,VL]].map(x=><div key={x[0]}><div style={{fontSize:12,color:C.textMuted,marginBottom:3}}>{x[0]}</div><select aria-label={x[0]+" grade"} value={x[1]} onChange={e=>x[2](e.target.value)} style={{width:"100%",padding:"7px 8px",borderRadius:8,border:`1px solid ${C.border}`,background:C.card,color:C.text,fontSize:12.5,boxSizing:"border-box"}}><option>N/A</option>{x[3].map(g=><option key={g}>{g}</option>)}</select></div>)}</div>
      </div>:null}
      {step===1?<div style={{display:"flex",gap:8,padding:"12px 16px",borderTop:`1px solid ${C.border}`}}><button onClick={onSkip} style={{flex:1,padding:11,background:C.surface,color:C.textSub,border:`1px solid ${C.border}`,borderRadius:11,fontSize:14,cursor:"pointer",fontWeight:600}}>Skip for now</button><button onClick={()=>disc.length&&onFinish({/* homeArea is saved into profiles.location, which partner rows print as the climber's city. It sent the picked area's ID ("lcc"), so a raw id reached other climbers. Send what the box shows -- the picked name or the city already on file -- and fall back to `home` so an untouched box never blanks it. */homeArea:(homeQ||"").trim()||home,disciplines:disc,sportGrade:sg,tradGrade:tg,boulderGrade:bg})} disabled={!disc.length} style={{flex:2,padding:11,background:disc.length?C.green:C.border,color:disc.length?C.bg:C.textMuted,border:"none",borderRadius:11,fontSize:14.5,cursor:disc.length?"pointer":"default",fontWeight:700}}>{editing?"Save changes":"Finish setup"}</button></div>:null}
    </div>
  </div>;
}
