import { photoAltsOf } from "../ClimbMatchCore.jsx";

/* One climb_logs row, read by another climber, shaped exactly like a seed `activity` row. The route
   page's community reports and the Today tab's friend activity both build rows from it, so a report
   opened from either one is the same document. Moved out of RouteDetail.jsx, where it was written;
   the notes on individual fields are kept with it. `p` is the reporter's profile ({name, avatar}) or
   null. A reporter whose profile is missing gets no invented name. */
export function tripRowToActivity(r, p) {
  var cond={};if(r.approach_minutes!=null)cond.approachMin=r.approach_minutes;if(r.climb_minutes!=null)cond.climbMin=r.climb_minutes;if(r.descent_minutes!=null)cond.descentMin=r.descent_minutes;if(r.car_to_car_minutes!=null){cond.carToCar=Math.floor(r.car_to_car_minutes/60)+"h "+(r.car_to_car_minutes%60)+"m";/* Carry the INTEGER alongside the display string. `carToCar` is prose on the seed path ("3 days", "Turned around") so it can never be parsed back into a number safely; loggedTimeStats reads this field and never that one. */cond.carToCarMin=r.car_to_car_minutes;}if(r.snow_condition)cond.snow=r.snow_condition;/* the NUMBER, not uElev()'s string: the form re-seeds from it, and a formatted "3,353 m" typed back in as feet shrank the value 3.28x per metric edit */if(r.freezing_level_ft!=null)cond.freezingFt=r.freezing_level_ft;if(r.water_level)cond.water=r.water_level;if(r.bug_pressure)cond.bugs=r.bug_pressure;if(r.trail_condition)cond.trail=r.trail_condition;if(r.protection_quality)cond.protection=r.protection_quality;if(r.anchor_quality)cond.anchors=r.anchor_quality;if(r.crowd_level)cond.crowds=r.crowd_level;if(r.party_size!=null)cond.partySize=String(r.party_size);if(r.temp_f!=null)cond.tempF=r.temp_f;if(r.snow_depth)cond.snowDepth=r.snow_depth;if(r.seepage)cond.seepage=r.seepage;if(r.mud)cond.mud=r.mud;if(r.rappel_count!=null)cond.rapCount=String(r.rappel_count);if(r.rappel_longest_m!=null)cond.rapLongestM=r.rappel_longest_m;if(r.rappel_rope)cond.rapRope=r.rappel_rope;
      return {_dbId:r.id,user:p&&p.name||"A climber",avatar:p&&p.avatar||"",date:r.date_climbed,stars:r.stars,condTags:r.cond_tags||[],tickType:r.tick_type||undefined,text:r.notes||"",photos:(r.photos||[]).map(function(ph){return ph&&ph.url;}).filter(Boolean),photoAlts:photoAltsOf(r.photos),beta:r.beta||undefined,gearBeta:r.gear_beta||undefined,outcomeReasons:r.outcome_reasons||[],outcomeNote:r.outcome_note||undefined,/* buildConsensus derives faCredits from `faAscent` and isDeveloped from `developed`, and RouteDetail renders each as its own panel. `activity` dedupes route.activity -> myReports -> dbReports by _dbId, so YOUR row arrives via myReports carrying the full ClimbMatch shape and keeps these; every other climber's row exists only here. Dropping them meant a panel whose whole purpose is public attribution could only ever credit yourself. Both are booleans the logger asserted about their own ascent — same standing as the seed activity rows that have always fed these panels. */fa:!!r.fa_ascent,faAscent:!!r.fa_ascent,developed:!!r.developed,/* TripReport is what onOpenReport opens these rows INTO, and it reads all three: an itinerary block, a sun block, and gear/beta. Without them another climber's report opened from this page rendered a shorter document than the same row does in its author's own logbook. `partners` is deliberately NOT hydrated: matchClimber does `CLIMBERS.find(c=>c.name===nm&&ascent.partnerIds.includes(c.id))` against seed INTEGER ids, so feeding it uuids takes that branch and returns null for every partner — worse than the name fallback it currently uses. See check:crew-member-readers. */itinerary:r.itinerary||undefined,sunVote:r.sun_vote||undefined,sunNote:r.sun_note||undefined,roadNote:r.road_note||undefined,cond:Object.keys(cond).length?cond:undefined};
}
