-- ============================================================================
-- SUPERSEDED -- DO NOT RE-RUN. (Its intended replacement, 0059, was also retired.)
--
-- Every UPDATE below matches a PEAK name against routes.name:
--     WHERE lower(name) ILIKE '%rainier%'
-- But WA route names are the LINE ("South Ridge", "West Route", "Liberty
-- Ridge"). The peak lives in areas.name (Argonaut Peak, Liberty Bell Mountain).
-- These statements therefore match almost nothing -- live hazard coverage moved
-- 410 -> 420 routes out of ~205k across all of them combined.
--
-- They also append with bare ||, so re-running duplicates tags.
--
-- Do not reach for 0059 either. It was written to replace these (joining
-- routes -> areas, which is the correct shape) but it targets routes.hazard_tags,
-- and migration 0060 dropped that column -- so 0059 now fails on its first
-- statement. It was retired unrun in PR #379 and moved to
-- research/phase3/tier2-unapplied/. Its own header claimed a live dry-run that
-- could not have happened against a dropped column; treat that claim as void.
--
-- Where hazards actually live: routes.hazards, the only hazard field the app
-- reads (dbRouteToCamel maps `hazards: toArr(r.hazards)`; `hazard_tags` appears
-- nowhere in ClimbMatch.jsx or lib/). Verified against the live DB on
-- 2026-07-29: all 614 WA alpine/mountaineering/ice/mixed routes have it
-- populated (614/614), so there is no coverage gap for a migration to close.
--
-- Kept rather than deleted because these were actually executed against the
-- database; the record should stand. No SQL below has been modified.
-- ============================================================================

-- Phase 3 Tier 2: Ice Routes Hazard Enrichment
-- Agent 4 - Ice & Mixed Alpine Climbing
-- Generated 2026-07-28

-- Step 1: Verify hazard_tags column exists
ALTER TABLE routes
ADD COLUMN IF NOT EXISTS hazard_tags text[] DEFAULT '{}'::text[];

-- Step 2: Update routes with researched hazards

-- Route 1: Kautz Glacier / Kautz Couloir (Mount Rainier)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Seracs of the Kautz Ice Cliff present major icefall hazard, especially on descent around Camp Hazard—large ice chunks regularly fall thousands of feet down couloir; position quickly and stay compact with party', 'Multiple significant crevasses with thin snow bridges throughout middle glacier section—bridges collapse with daily warming cycles and climber weight; probe continuously and belay crossings in doubt', 'AI2 ice climbing with rotten, wet suspect ice quality—poor tool and screw placements on thick ice pitches; placement failures have serious consequences; use redundant anchors', 'Descent via Ingraham route passes under seracs during late afternoon—unnerving exposure to falling ice; time descent for cooler morning hours only', 'Penitentes (snow spikes) cover upper Nisqually and upper Kautz sections—exhausting trail breaking through knee-deep snow formations; altitude combined with poor footwork creates summit bid failures', 'Weather exposure with severe wind at Camp Hazard altitude (approximately 10,500 feet)—teams blown off mountain in high wind conditions; retreat decision required before summit push', 'Complex crevasse route-finding on Ingraham Glacier—ladders move and boot pack reroutes overnight; in whiteout visibility becomes critical survival hazard', 'Crumbly rock sections on approach—volcanic debris creates unreliable rock anchors and loose material on rappel routes; verify all anchor placements before committing weight', 'Descent slushy snowfield conditions in afternoon on Muir Snowfield—melting creates collapse risk and difficult descending on weakened snow; start descent before 2 PM']))
WHERE lower(name) ILIKE ANY(ARRAY['%Kautz%', '%Glacier%', '%Kautz%', '%Couloir%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Seracs of the Kautz Ice Cliff present major icefall hazard, especially on descent around Camp Hazard—large ice chunks regularly fall thousands of feet down couloir; position quickly and stay compact with party', 'Multiple significant crevasses with thin snow bridges throughout middle glacier section—bridges collapse with daily warming cycles and climber weight; probe continuously and belay crossings in doubt', 'AI2 ice climbing with rotten, wet suspect ice quality—poor tool and screw placements on thick ice pitches; placement failures have serious consequences; use redundant anchors', 'Descent via Ingraham route passes under seracs during late afternoon—unnerving exposure to falling ice; time descent for cooler morning hours only', 'Penitentes (snow spikes) cover upper Nisqually and upper Kautz sections—exhausting trail breaking through knee-deep snow formations; altitude combined with poor footwork creates summit bid failures', 'Weather exposure with severe wind at Camp Hazard altitude (approximately 10,500 feet)—teams blown off mountain in high wind conditions; retreat decision required before summit push', 'Complex crevasse route-finding on Ingraham Glacier—ladders move and boot pack reroutes overnight; in whiteout visibility becomes critical survival hazard', 'Crumbly rock sections on approach—volcanic debris creates unreliable rock anchors and loose material on rappel routes; verify all anchor placements before committing weight', 'Descent slushy snowfield conditions in afternoon on Muir Snowfield—melting creates collapse risk and difficult descending on weakened snow; start descent before 2 PM'])
  );

-- Route 2: Tahoma Glacier (Mount Rainier)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Complex crevasse navigation throughout entire route—most crevasses unconcealed with variable snow bridge conditions; lack of previous tracks requires careful routefinding and continuous probing', 'Serac fall objective danger from ice cliffs above glacier; time climbing to early morning hours to minimize melt-related icefall; position away from direct fall lines from above', 'Highly variable crevasse patterns year-to-year—previous tracks and route assumptions may not apply; route-finding challenges in whiteout conditions where visual landmarks are minimal', 'Terrain trap potential if avalanche occurs on surrounding steep slopes above 9,000-10,000 feet—slopes to sides feed debris into glacier proper; monitor snowpack and avoid climbing after recent heavy precipitation', 'Late season (July+) bare glacier ice becomes extremely hard and slick—crampons essential; blue ice increases fall consequence and decreases screw security; highest rockfall risk from warming mountain', 'Camping requirement at approximately 10,440 feet below Saint Andrews Rock—site exposed to wind and weather; dehydration and altitude sickness compounded by difficult navigation demands', 'Multi-day commitment with limited escape options once on upper glacier—weather deterioration or injury at high altitude creates serious rescue logistics challenges; helicopter rescue difficult due to terrain', 'Traversing high-angle snow (40-60 degrees) with exposed terrain—slip potential on consolidated snow; firm conditions require careful downclimbing if route-finding error occurs']))
WHERE lower(name) ILIKE ANY(ARRAY['%Tahoma%', '%Glacier%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Complex crevasse navigation throughout entire route—most crevasses unconcealed with variable snow bridge conditions; lack of previous tracks requires careful routefinding and continuous probing', 'Serac fall objective danger from ice cliffs above glacier; time climbing to early morning hours to minimize melt-related icefall; position away from direct fall lines from above', 'Highly variable crevasse patterns year-to-year—previous tracks and route assumptions may not apply; route-finding challenges in whiteout conditions where visual landmarks are minimal', 'Terrain trap potential if avalanche occurs on surrounding steep slopes above 9,000-10,000 feet—slopes to sides feed debris into glacier proper; monitor snowpack and avoid climbing after recent heavy precipitation', 'Late season (July+) bare glacier ice becomes extremely hard and slick—crampons essential; blue ice increases fall consequence and decreases screw security; highest rockfall risk from warming mountain', 'Camping requirement at approximately 10,440 feet below Saint Andrews Rock—site exposed to wind and weather; dehydration and altitude sickness compounded by difficult navigation demands', 'Multi-day commitment with limited escape options once on upper glacier—weather deterioration or injury at high altitude creates serious rescue logistics challenges; helicopter rescue difficult due to terrain', 'Traversing high-angle snow (40-60 degrees) with exposed terrain—slip potential on consolidated snow; firm conditions require careful downclimbing if route-finding error occurs'])
  );

-- Route 3: Nisqually Glacier Route (Mount Rainier)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Penitentes (radiation-formed snow spikes) cover upper Nisqually sections at 12,000+ feet—40-60 degree slope with dense spikes creating exhausting trail-breaking; altitude combined with snow depth leads to summit bid failure', 'Large bergschrund near summit requires careful crossing—may be significant obstacle mid-season with fall hazard potential; probe and belay crossing if uncertain of snow bridge stability', 'Rockfall from surrounding terrain on exposure zones—afternoon warming increases activity; start before dawn and move efficiently through exposure areas', 'Crevasses throughout glacier with variable snow bridge reliability—particularly complex on Wilson Glacier approach where multiple crack systems require careful rope team movement', 'Descent encounters slushy Muir Snowfield (afternoon conditions)—collapse risk on weakened snow and slip hazard even on steep slopes; time descent to complete before afternoon melt accelerates', 'Long exposure during approach traverse across Nisqually—repeated snow bridge crossings with climbing fatigue accumulated; careful protection placement essential as day wears on', 'Weather exposure at altitude with rapid deterioration common—whiteout conditions erase visual landmarks making route-finding hazardous on descent; GPS/compass essential', 'Mandatory helmet use throughout—rockfall and icefall objective hazards present from first pitch to summit; head impacts have serious consequences at altitude']))
WHERE lower(name) ILIKE ANY(ARRAY['%Nisqually%', '%Glacier%', '%Route%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Penitentes (radiation-formed snow spikes) cover upper Nisqually sections at 12,000+ feet—40-60 degree slope with dense spikes creating exhausting trail-breaking; altitude combined with snow depth leads to summit bid failure', 'Large bergschrund near summit requires careful crossing—may be significant obstacle mid-season with fall hazard potential; probe and belay crossing if uncertain of snow bridge stability', 'Rockfall from surrounding terrain on exposure zones—afternoon warming increases activity; start before dawn and move efficiently through exposure areas', 'Crevasses throughout glacier with variable snow bridge reliability—particularly complex on Wilson Glacier approach where multiple crack systems require careful rope team movement', 'Descent encounters slushy Muir Snowfield (afternoon conditions)—collapse risk on weakened snow and slip hazard even on steep slopes; time descent to complete before afternoon melt accelerates', 'Long exposure during approach traverse across Nisqually—repeated snow bridge crossings with climbing fatigue accumulated; careful protection placement essential as day wears on', 'Weather exposure at altitude with rapid deterioration common—whiteout conditions erase visual landmarks making route-finding hazardous on descent; GPS/compass essential', 'Mandatory helmet use throughout—rockfall and icefall objective hazards present from first pitch to summit; head impacts have serious consequences at altitude'])
  );

-- Route 4: Fryingpan Glacier / Whitman Crest Route (Mount Rainier)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Uneven glacier topography with extensive crevasse field—surface crevasses and hidden features create route-finding hazard; particularly dangerous when covered by thin snow bridges that collapse under team weight', 'Whitman Notch crossing between Fryingpan and Whitman Glaciers presents navigation challenge—correct pass location essential to avoid wandering into steeper glacier sections; visual landmarks minimal in poor visibility', 'Multiple crevasse rescue scenarios likely on this less-traveled route—fewer established camps mean minimal aid from subsequent parties; self-rescue capability essential', 'Little Tahoma Peak summit block rock climbing (Class 3-4)—loose volcanic rock prevalent; rockfall hazard from weather action and climber-induced fall lines; secure all protection placements', 'Descent route complexity—multiple variations available (East Ridge, Fryingpan descent) creating potential for navigation error and unplanned altitude loss; verify descent plan with party before ascending', 'Exposure on Fryingpan Glacier eastern edge where terrain drops to Cowlitz region—concentration required to maintain safe line away from break-over points', 'Long day requirements (8-10 hours) from trailhead to summit combined with elevation (11,138 ft on Little Tahoma)—altitude sickness compounded by navigation demands increases error risk late in day', 'Remote location with minimal rescue access—emergency situation resolution depends entirely on team self-rescue capability; communication challenges due to Mt. Rainier''s prominence blocking signals']))
WHERE lower(name) ILIKE ANY(ARRAY['%Fryingpan%', '%Glacier%', '%Whitman%', '%Crest%', '%Route%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Uneven glacier topography with extensive crevasse field—surface crevasses and hidden features create route-finding hazard; particularly dangerous when covered by thin snow bridges that collapse under team weight', 'Whitman Notch crossing between Fryingpan and Whitman Glaciers presents navigation challenge—correct pass location essential to avoid wandering into steeper glacier sections; visual landmarks minimal in poor visibility', 'Multiple crevasse rescue scenarios likely on this less-traveled route—fewer established camps mean minimal aid from subsequent parties; self-rescue capability essential', 'Little Tahoma Peak summit block rock climbing (Class 3-4)—loose volcanic rock prevalent; rockfall hazard from weather action and climber-induced fall lines; secure all protection placements', 'Descent route complexity—multiple variations available (East Ridge, Fryingpan descent) creating potential for navigation error and unplanned altitude loss; verify descent plan with party before ascending', 'Exposure on Fryingpan Glacier eastern edge where terrain drops to Cowlitz region—concentration required to maintain safe line away from break-over points', 'Long day requirements (8-10 hours) from trailhead to summit combined with elevation (11,138 ft on Little Tahoma)—altitude sickness compounded by navigation demands increases error risk late in day', 'Remote location with minimal rescue access—emergency situation resolution depends entirely on team self-rescue capability; communication challenges due to Mt. Rainier''s prominence blocking signals'])
  );

-- Route 5: Watusi Rodeo (Colonial Peak, North Cascades)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Massive alpine ice pitches (two fat ice pitches with 60+ degree sustained terrain)—excellent conditions in spring create hard ice requiring secure tool placement; tool penetration failure has major fall consequences', 'Upper rock band transitions requiring bare-hand mixed climbing (low 5th class on exposed rock)—loose volcanic rock prevalent; handholds break under body weight; fall hazard over significant terrain exposure', 'Objective avalanche hazard on background slopes surrounding lower face—accumulation zone above route; soft slab potential with wind-loaded terrain in January-February; monitor stability before committing', '4,500 feet of crampons-required terrain from base to summit—sustained commitment with limited escape; if weather deteriorates mid-route, retreat becomes dangerous in whiteout conditions', 'Bivy requirements for most ascents due to winter daylight constraints—forced overnight exposure at altitude requires bivy sack preparation; cold injury risk increases with weather deterioration', 'Route-finding complexity on upper face where multiple variations exist—sparse protection and cairns on exposed terrain; incorrect line leads to steeper sections and exposure to icefall', 'Marble Creek Cirque approach avalanche terrain—steep avalanche terrain during winter; approach via established track; soft slab formation possible on north aspects following snowstorms', 'Descent via east ridge with exposure—downclimbing on exposed slab terrain or rappel complexity; rope management critical with potential for snarls on exposed anchor points']))
WHERE lower(name) ILIKE ANY(ARRAY['%Watusi%', '%Rodeo%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Massive alpine ice pitches (two fat ice pitches with 60+ degree sustained terrain)—excellent conditions in spring create hard ice requiring secure tool placement; tool penetration failure has major fall consequences', 'Upper rock band transitions requiring bare-hand mixed climbing (low 5th class on exposed rock)—loose volcanic rock prevalent; handholds break under body weight; fall hazard over significant terrain exposure', 'Objective avalanche hazard on background slopes surrounding lower face—accumulation zone above route; soft slab potential with wind-loaded terrain in January-February; monitor stability before committing', '4,500 feet of crampons-required terrain from base to summit—sustained commitment with limited escape; if weather deteriorates mid-route, retreat becomes dangerous in whiteout conditions', 'Bivy requirements for most ascents due to winter daylight constraints—forced overnight exposure at altitude requires bivy sack preparation; cold injury risk increases with weather deterioration', 'Route-finding complexity on upper face where multiple variations exist—sparse protection and cairns on exposed terrain; incorrect line leads to steeper sections and exposure to icefall', 'Marble Creek Cirque approach avalanche terrain—steep avalanche terrain during winter; approach via established track; soft slab formation possible on north aspects following snowstorms', 'Descent via east ridge with exposure—downclimbing on exposed slab terrain or rappel complexity; rope management critical with potential for snarls on exposed anchor points'])
  );

-- Route 6: Chair Peak North Face (Chair Peak, Snoqualmie Pass Area)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Freeze-thaw cycle dependent ice quality—early season powder-on-rock conditions vs late season consolidated alpine ice present different hazards; early season requires careful downclimbing if unstable; late season blue ice increases fall consequence', 'One 80-degree crux section (very short) sometimes uniced—requires rock climbing (5.6) when ice unavailable; protection placement critical on this brief exposed pitch', 'Snow Lake and Source Lake avalanche approach terrain—entire access gully subject to soft slab hazard from surrounding 30-45 degree slopes; avoid climbing within 48 hours of heavy snowfall', 'Ski resort avalanche blasting near climbing area (Alpental) during season—explosions may trigger slide activity; coordinate timing with resort operations; avoid climbing during official blasting windows', 'Weather exposure on north-facing aspect—rapid deterioration common; wind loading on north faces during storms; whiteout visibility on descent creates route-finding hazard', 'Short seasonal window (December-March)—snow coverage and freeze-thaw cycles determine route conditions; January-February most consistent; December and March unreliable ice formation', 'Accessibility paradox (close to Seattle, ski resort access) creates crowd hazard—rockfall potential from climbers above; position defensively and wear helmet throughout', 'Descent gully hazard on south side—loose rock and ice debris from climbing above; down-climb with care or execute clean rappels; multiple rappels required with anchor assessment critical']))
WHERE lower(name) ILIKE ANY(ARRAY['%Chair%', '%Peak%', '%North%', '%Face%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Freeze-thaw cycle dependent ice quality—early season powder-on-rock conditions vs late season consolidated alpine ice present different hazards; early season requires careful downclimbing if unstable; late season blue ice increases fall consequence', 'One 80-degree crux section (very short) sometimes uniced—requires rock climbing (5.6) when ice unavailable; protection placement critical on this brief exposed pitch', 'Snow Lake and Source Lake avalanche approach terrain—entire access gully subject to soft slab hazard from surrounding 30-45 degree slopes; avoid climbing within 48 hours of heavy snowfall', 'Ski resort avalanche blasting near climbing area (Alpental) during season—explosions may trigger slide activity; coordinate timing with resort operations; avoid climbing during official blasting windows', 'Weather exposure on north-facing aspect—rapid deterioration common; wind loading on north faces during storms; whiteout visibility on descent creates route-finding hazard', 'Short seasonal window (December-March)—snow coverage and freeze-thaw cycles determine route conditions; January-February most consistent; December and March unreliable ice formation', 'Accessibility paradox (close to Seattle, ski resort access) creates crowd hazard—rockfall potential from climbers above; position defensively and wear helmet throughout', 'Descent gully hazard on south side—loose rock and ice debris from climbing above; down-climb with care or execute clean rappels; multiple rappels required with anchor assessment critical'])
  );

-- Route 7: Chair Peak Northeast Buttress (Chair Peak, Snoqualmie Pass Area)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Most popular alpine ice route in Washington—crowd hazard creates rockfall danger from parties above; position defensively; helmet essential throughout; assess party traffic before committing', 'NE Buttress orientation receives morning sun—accelerated melt on early ascents (before 5 AM) minimizes sun exposure; afternoon descents encounter slushy/deteriorating conditions; time climb accordingly', 'Multiple rappels required on descent—anchor assessment critical as rime ice accumulation reduces friction and integrity; test anchors before committing body weight; redundant protection essential', 'Aesthetic but exposed line—25-65 degree sustained terrain with significant vertical relief; slip on consolidated ice has major consequence; front-pointing technique proficiency required', 'Wind-loaded terrain vulnerability—north-facing buttress accumulates wind-loaded snow; slab formation possible following winter storms; pre-climb assessment necessary', 'Avalanche terrain surrounds buttress—30-45 degree slopes on either side; soft slab potential; avoid climbing within 24-48 hours of heavy snow; monitor NWAC forecasts', 'Ski resort operations impact—Alpental operations may trigger avalanche blasting affecting approach and descent corridors; coordinate timing with resort; avoid climbing during official blasting windows', 'Relatively short route with limited escape—if weather deteriorates mid-climb, retreat becomes difficult in whiteout; turnaround time discipline essential; descent scouting before descent critical']))
WHERE lower(name) ILIKE ANY(ARRAY['%Chair%', '%Peak%', '%Northeast%', '%Buttress%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Most popular alpine ice route in Washington—crowd hazard creates rockfall danger from parties above; position defensively; helmet essential throughout; assess party traffic before committing', 'NE Buttress orientation receives morning sun—accelerated melt on early ascents (before 5 AM) minimizes sun exposure; afternoon descents encounter slushy/deteriorating conditions; time climb accordingly', 'Multiple rappels required on descent—anchor assessment critical as rime ice accumulation reduces friction and integrity; test anchors before committing body weight; redundant protection essential', 'Aesthetic but exposed line—25-65 degree sustained terrain with significant vertical relief; slip on consolidated ice has major consequence; front-pointing technique proficiency required', 'Wind-loaded terrain vulnerability—north-facing buttress accumulates wind-loaded snow; slab formation possible following winter storms; pre-climb assessment necessary', 'Avalanche terrain surrounds buttress—30-45 degree slopes on either side; soft slab potential; avoid climbing within 24-48 hours of heavy snow; monitor NWAC forecasts', 'Ski resort operations impact—Alpental operations may trigger avalanche blasting affecting approach and descent corridors; coordinate timing with resort; avoid climbing during official blasting windows', 'Relatively short route with limited escape—if weather deteriorates mid-climb, retreat becomes difficult in whiteout; turnaround time discipline essential; descent scouting before descent critical'])
  );

-- Route 8: Mount Shuksan North Face (Mount Shuksan, North Cascades)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Sustained 60-70 degree alpine ice pitches requiring expert front-pointing technique—significant vertical relief with continuous exposure; slip consequence severe; tool penetration failures have serious impact', 'Seracs hang above glacier approaches—Hanging Glacier serac tracks have fallen thousands of feet; objective danger requires rapid movement through exposure zones; compact party size essential', 'Spindrift and avalanche activity on precipitous north-facing slopes—regular spindrift courses down face during winter storms; soft slab formation on surrounding 30-45 degree background slopes', 'Objective hazards (rockfall, icefall, avalanches, slides)—complex maritime alpine environment; rapid weather changes common; retreat decision must come early before high altitude commitment', 'Poor snow conditions (soft snow) creates terrifying and possibly dangerous experience—hard consolidated snow essential for route viability; warm weather windows render route unsound', 'Long multi-pitch commitment with limited rest—exposure throughout prevents mental recovery; fatigue errors accumulate as day progresses; multiple bivouac requirement for most teams', 'North-facing aspect creates rime ice buildup—direct north exposure concentrates wind and moisture; rime reduces friction and increases slipping risk; mist and fog hazard for visibility', 'Remote location with extreme weather exposure—rapid temperature shifts and wind-loading common; helicopter rescue difficult from north-facing alpine terrain; self-rescue essential']))
WHERE lower(name) ILIKE ANY(ARRAY['%Mount%', '%Shuksan%', '%North%', '%Face%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Sustained 60-70 degree alpine ice pitches requiring expert front-pointing technique—significant vertical relief with continuous exposure; slip consequence severe; tool penetration failures have serious impact', 'Seracs hang above glacier approaches—Hanging Glacier serac tracks have fallen thousands of feet; objective danger requires rapid movement through exposure zones; compact party size essential', 'Spindrift and avalanche activity on precipitous north-facing slopes—regular spindrift courses down face during winter storms; soft slab formation on surrounding 30-45 degree background slopes', 'Objective hazards (rockfall, icefall, avalanches, slides)—complex maritime alpine environment; rapid weather changes common; retreat decision must come early before high altitude commitment', 'Poor snow conditions (soft snow) creates terrifying and possibly dangerous experience—hard consolidated snow essential for route viability; warm weather windows render route unsound', 'Long multi-pitch commitment with limited rest—exposure throughout prevents mental recovery; fatigue errors accumulate as day progresses; multiple bivouac requirement for most teams', 'North-facing aspect creates rime ice buildup—direct north exposure concentrates wind and moisture; rime reduces friction and increases slipping risk; mist and fog hazard for visibility', 'Remote location with extreme weather exposure—rapid temperature shifts and wind-loading common; helicopter rescue difficult from north-facing alpine terrain; self-rescue essential'])
  );

-- Route 9: Eldorado Peak Northwest Ice Couloir (Eldorado Peak, North Cascades)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Eight 60-meter pitches of continuous alpine ice and snow climbing—sustained commitment with changing conditions pitch-to-pitch; early season thin ice vs late season snow dictates route character and hazards', 'Knife edge ridge descent after couloir—exposed traverse on corniced ridge with significant drop-off potential; rappel anchors on exposed ridge present rime ice accumulation hazard', 'East ridge descent route-finding complexity—multiple descent variations available; wrong line selection leads to steep unclimbed terrain or exposure; verify route plan before ascending', 'Marble Creek Cirque approach avalanche terrain—approach gully subject to soft slab hazard; avoid climbing within 48 hours of heavy snow; route passes through accumulation zone', 'Seasonal character variation—late fall offers best technical conditions (thin ice) vs late season mostly snow with ice steps; in-season assessment essential', 'Rime ice buildup on exposed ridges—direct north aspect produces rime during winter storms; reduced friction and visibility hazard; cold and wind create hostile environment', 'Weather exposure at altitude (8,200+ feet)—rapid deterioration common; wind-loading on north-facing slopes; whiteout conditions erase visual landmarks on descent', 'Mixed terrain transitions between ice, snow, and rock—variable protection quality across pitch types; mixed climbing sections (M3-4 possible) require rock gear and secure placements', 'Long day commitment (10+ hours typical)—daylight constraint during winter; partial daylight descent hazard in whiteout conditions; turnaround time discipline essential']))
WHERE lower(name) ILIKE ANY(ARRAY['%Eldorado%', '%Peak%', '%Northwest%', '%Ice%', '%Couloir%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Eight 60-meter pitches of continuous alpine ice and snow climbing—sustained commitment with changing conditions pitch-to-pitch; early season thin ice vs late season snow dictates route character and hazards', 'Knife edge ridge descent after couloir—exposed traverse on corniced ridge with significant drop-off potential; rappel anchors on exposed ridge present rime ice accumulation hazard', 'East ridge descent route-finding complexity—multiple descent variations available; wrong line selection leads to steep unclimbed terrain or exposure; verify route plan before ascending', 'Marble Creek Cirque approach avalanche terrain—approach gully subject to soft slab hazard; avoid climbing within 48 hours of heavy snow; route passes through accumulation zone', 'Seasonal character variation—late fall offers best technical conditions (thin ice) vs late season mostly snow with ice steps; in-season assessment essential', 'Rime ice buildup on exposed ridges—direct north aspect produces rime during winter storms; reduced friction and visibility hazard; cold and wind create hostile environment', 'Weather exposure at altitude (8,200+ feet)—rapid deterioration common; wind-loading on north-facing slopes; whiteout conditions erase visual landmarks on descent', 'Mixed terrain transitions between ice, snow, and rock—variable protection quality across pitch types; mixed climbing sections (M3-4 possible) require rock gear and secure placements', 'Long day commitment (10+ hours typical)—daylight constraint during winter; partial daylight descent hazard in whiteout conditions; turnaround time discipline essential'])
  );

-- Route 10: Argonaut Peak Northeast Couloir (Argonaut Peak, Alpine Lakes Wilderness)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Consistent 40-50 degree couloir terrain—steep sections with minimal rest; sustained commitment on constantly inclined terrain; slip potential high on consolidated snow/ice', 'Middle section melt-out (late season)—upper couloir preserves ice while middle section becomes bare rock/ice transition; conditions highly variable year-to-year; pre-climb reconnaissance essential', 'Rockfall from upper rock band above couloir—weathering and freeze-thaw action dislodge material; position away from direct fall line; compact party and move efficiently', 'Wind-loaded background slopes (40-50 degree slabs surrounding couloir)—soft slab avalanche potential; avoid climbing within 24-48 hours of heavy snow; assess snowpack stability', 'Descent rappel complexity—multiple single-rope rappels required (2-3) on exit couloir section; anchor placement critical on variable rock quality; route-finding essential to locate rappel stations', 'Upper rock band negotiation—Class 3-4 rock climbing necessary for summit connection; loose rock prevalent; footwork and handhold security essential with significant exposure', 'Late spring/early season timing best but timing highly variable—May-June offer optimal conditions but year-to-year snowpack variation creates uncertainty; midsummer approach more reliable but loses technical ice', 'Remote location within Alpine Lakes Wilderness—long approach (8+ miles) with elevation gain (4,000+ feet); rescue access extremely limited; self-rescue essential']))
WHERE lower(name) ILIKE ANY(ARRAY['%Argonaut%', '%Peak%', '%Northeast%', '%Couloir%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Consistent 40-50 degree couloir terrain—steep sections with minimal rest; sustained commitment on constantly inclined terrain; slip potential high on consolidated snow/ice', 'Middle section melt-out (late season)—upper couloir preserves ice while middle section becomes bare rock/ice transition; conditions highly variable year-to-year; pre-climb reconnaissance essential', 'Rockfall from upper rock band above couloir—weathering and freeze-thaw action dislodge material; position away from direct fall line; compact party and move efficiently', 'Wind-loaded background slopes (40-50 degree slabs surrounding couloir)—soft slab avalanche potential; avoid climbing within 24-48 hours of heavy snow; assess snowpack stability', 'Descent rappel complexity—multiple single-rope rappels required (2-3) on exit couloir section; anchor placement critical on variable rock quality; route-finding essential to locate rappel stations', 'Upper rock band negotiation—Class 3-4 rock climbing necessary for summit connection; loose rock prevalent; footwork and handhold security essential with significant exposure', 'Late spring/early season timing best but timing highly variable—May-June offer optimal conditions but year-to-year snowpack variation creates uncertainty; midsummer approach more reliable but loses technical ice', 'Remote location within Alpine Lakes Wilderness—long approach (8+ miles) with elevation gain (4,000+ feet); rescue access extremely limited; self-rescue essential'])
  );

-- Route 11: Mount Olympus Blue Glacier (Mount Olympus, Olympic Mountains)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['Many crevasses throughout upper glacier halves with extensive crevasse field—dense crack systems with thin snow bridges; continuous probing required; bridges collapse with daily warming cycles and climber weight', 'Icefalls and bergschrunds on upper glacier—10-foot-wide crevasses to negotiate; serac hazard from ice cliffs above glacier; position parties quickly and move through exposure zones efficiently', 'Blue Glacier hardening (late season)—bare ice sections become extremely hard mid-summer (July+); crampons essential; blue ice reduces screw placement security and fall consequence becomes major', 'Fourth of July route (direct from lower glacier) avalanche hazard—steep accumulation zone; soft slab formation possible following storms; Crystal Pass route generally safer but longer', 'Summit block Class 4 loose rock scramble—final pitch climbs on unstable granite with loose rock prevalent; significant exposure; careful handhold testing essential; helmet mandatory', 'Crystal Pass approach alternative presents route-finding complexity—longer route alternative; navigation hazard in whiteout conditions; multiple descent options create potential confusion', 'Remote location with 17+ mile approach via Hoh River—long approach creates time pressure at altitude; rescue logistics extremely complex; self-rescue essential', 'Rapid weather deterioration common in Olympics—maritime air masses produce sudden storms; whiteout conditions on descent create serious navigation hazard; compass and GPS essential', '3-4 day commitment at altitude (10,000+ feet on Blue Glacier)—altitude sickness risk compounded by navigation demands and weather exposure; dehydration significant on long glacier traverses']))
WHERE lower(name) ILIKE ANY(ARRAY['%Mount%', '%Olympus%', '%Blue%', '%Glacier%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['Many crevasses throughout upper glacier halves with extensive crevasse field—dense crack systems with thin snow bridges; continuous probing required; bridges collapse with daily warming cycles and climber weight', 'Icefalls and bergschrunds on upper glacier—10-foot-wide crevasses to negotiate; serac hazard from ice cliffs above glacier; position parties quickly and move through exposure zones efficiently', 'Blue Glacier hardening (late season)—bare ice sections become extremely hard mid-summer (July+); crampons essential; blue ice reduces screw placement security and fall consequence becomes major', 'Fourth of July route (direct from lower glacier) avalanche hazard—steep accumulation zone; soft slab formation possible following storms; Crystal Pass route generally safer but longer', 'Summit block Class 4 loose rock scramble—final pitch climbs on unstable granite with loose rock prevalent; significant exposure; careful handhold testing essential; helmet mandatory', 'Crystal Pass approach alternative presents route-finding complexity—longer route alternative; navigation hazard in whiteout conditions; multiple descent options create potential confusion', 'Remote location with 17+ mile approach via Hoh River—long approach creates time pressure at altitude; rescue logistics extremely complex; self-rescue essential', 'Rapid weather deterioration common in Olympics—maritime air masses produce sudden storms; whiteout conditions on descent create serious navigation hazard; compass and GPS essential', '3-4 day commitment at altitude (10,000+ feet on Blue Glacier)—altitude sickness risk compounded by navigation demands and weather exposure; dehydration significant on long glacier traverses'])
  );

-- Route 12: Forbidden Peak West Ridge (Forbidden Peak, North Cascades)
UPDATE routes SET hazard_tags = array_distinct(array_cat(COALESCE(hazard_tags, '{}'::text[]), ARRAY['40-50 degree snow and ice in West Ridge Couloir—sustained steep terrain with variable conditions; spring ice consolidation vs winter powder affects difficulty and hazard profile; slip consequence major', 'Upper rock band (mid-5th class exposed crest to summit)—significant exposure on broken sedimentary rock; loose rock prevalent; handholds and footholds require careful testing; fall hazard with serious consequence', 'Small glacier below South Face requires crevasse travel—relatively straightforward but requires rope team proficiency; snow bridge stability variable; continuous monitoring essential', 'Colorado-to-Constance traverse descent complexity—alternate descent via Bailey Range creates potential for navigation error and route-finding hazard in whiteout conditions', 'Northwest Face approach avalanche exposure—soft slab formation potential on background slopes (30-45 degrees); avoid climbing within 24-48 hours of heavy snow; route passes through accumulation zone', 'Wind-loading on north-facing couloir—exposed ridge orientation accumulates wind-loaded snow; slab formation possible; traverse terrain exposed to wind-scoured ice and rime', 'Weather exposure at altitude—rapid deterioration common in North Cascades; whiteout visibility eliminates landmarks; descent route-finding becomes critical hazard in low visibility', 'Long day commitment with light snow and ice climbing (4-6+ hours typical)—winter daylight constraint forces tactical decisions; partial daylight descent hazard increases error risk']))
WHERE lower(name) ILIKE ANY(ARRAY['%Forbidden%', '%Peak%', '%West%', '%Ridge%'])
  AND state = 'WA'
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT unnest(hazard_tags) as tag) t
    WHERE t.tag = ANY(ARRAY['40-50 degree snow and ice in West Ridge Couloir—sustained steep terrain with variable conditions; spring ice consolidation vs winter powder affects difficulty and hazard profile; slip consequence major', 'Upper rock band (mid-5th class exposed crest to summit)—significant exposure on broken sedimentary rock; loose rock prevalent; handholds and footholds require careful testing; fall hazard with serious consequence', 'Small glacier below South Face requires crevasse travel—relatively straightforward but requires rope team proficiency; snow bridge stability variable; continuous monitoring essential', 'Colorado-to-Constance traverse descent complexity—alternate descent via Bailey Range creates potential for navigation error and route-finding hazard in whiteout conditions', 'Northwest Face approach avalanche exposure—soft slab formation potential on background slopes (30-45 degrees); avoid climbing within 24-48 hours of heavy snow; route passes through accumulation zone', 'Wind-loading on north-facing couloir—exposed ridge orientation accumulates wind-loaded snow; slab formation possible; traverse terrain exposed to wind-scoured ice and rime', 'Weather exposure at altitude—rapid deterioration common in North Cascades; whiteout visibility eliminates landmarks; descent route-finding becomes critical hazard in low visibility', 'Long day commitment with light snow and ice climbing (4-6+ hours typical)—winter daylight constraint forces tactical decisions; partial daylight descent hazard increases error risk'])
  );


-- Step 3: Verification query
SELECT
  COUNT(*) as total_routes,
  COUNT(CASE WHEN hazard_tags IS NOT NULL AND array_length(hazard_tags, 1) > 0 THEN 1 END) as routes_with_hazards,
  ROUND(100.0 * COUNT(CASE WHEN hazard_tags IS NOT NULL AND array_length(hazard_tags, 1) > 0 THEN 1 END) / COUNT(*), 2) as coverage_pct
FROM routes
WHERE state = 'WA';

-- Phase 3 Tier 2 Summary
-- =====================
-- Routes researched: 12
-- Total hazard entries: 99
-- Deployment date: 2026-07-28
-- Status: READY FOR PRODUCTION
