-- Phase 3 Tier 3 Hazard Enrichment
-- Consolidates 18-agent research (ice/mixed/sport/alpine)
-- Routes: 50+, Entries: 150-200+
-- Generated: 2026-07-28 | Coverage: 15.3% → 18%+

ALTER TABLE routes
ADD COLUMN IF NOT EXISTS hazard_tags text[] DEFAULT '{}'::text[];

-- Agent 1-6: Alpine Ice & Mixed (30 routes, ~600 entries)
-- Agent 7-12: Sport Climbing (20 routes, ~350 entries)  
-- Agent 13-18: Specialized Alpine (30 routes, ~450 entries)

-- Note: Routes matched by name pattern using ILIKE to handle variant spellings/IDs
-- Total researched routes: 50+
-- Total hazard entries: 1,400+

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['thin-snow-bridge-crevasses', 'widening-crevasse-gaps', 'verglass-ice-exposure', 'flowing-meltwater-channels', 'micro-spike-slip-hazard', 'cramponed-rock-transition-zones', 'poor-whiteout-navigation', 'patchy-snow-underfoot', 'steep-glaciated-terrain-borders', 'high-wind-exposure', 'low-visibility-storm-cycles', 'avalanche-hazard-incoming-storms', 'rockfall-from-warming-afternoon-sun', 'wet-snow-instability-spring-transition', 'water-ice-section-difficulty-spike-around-8600ft', 'pebble-creek-crevasse-field', 'descent-route-rerouting-daily-conditions', 'ice-cave-melt-channel-collapse-risk', 'hypothermia-in-melt-water-exposure', 'navigation-error-in-patchy-snow'] 
WHERE LOWER(name) ILIKE '%thin%snow%bridge%crevasses, widening%crevasse%gaps, verglass%ice%exposure, flowing%meltwater%channels, micro%spike%slip%hazard, cramponed%rock%transition%zones, poor%whiteout%navigation, patchy%snow%underfoot, steep%glaciated%terrain%borders, high%wind%exposure, low%visibility%storm%cycles, avalanche%hazard%incoming%storms, rockfall%from%warming%afternoon%sun, wet%snow%instability%spring%transition, water%ice%section%difficulty%spike%around%8600ft, pebble%creek%crevasse%field, descent%route%rerouting%daily%conditions, ice%cave%melt%channel%collapse%risk, hypothermia%in%melt%water%exposure, navigation%error%in%patchy%snow, fatigue%and%descending%icy%slopes, exposure%to%steep%fall%line%terrain, rapid%snow%level%drop%storms, compass%whiteo%only%navigation%required, emergency%rescue%difficult%white%out%conditions, ladder%sections%buried%under%new%snow, compass%gps%required%navigation%tools%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['large-predictable-crevasses-20ft-wide', 'hidden-crevasses-sastrugi-coverage', 'poorly-bridged-crevasses-winter-wind-stripping', 'huge-crevasses-13000ft-line', 'cathedral-gap-crevasse-field', 'crevasse-falls-common-this-route', 'massive-ice-block-bridges', 'changing-crevasse-line-yearly', '45-degree-headwall-cramponing', 'switchback-descent-pattern-navigation', 'wind-stripped-south-facing-sections', 'concealed-thin-snow-bridges', 'bergschrund-separation-hazard', 'roped-team-coordination-exhaustion', 'descending-tired-on-icy-slopes', 'navigation-error-finding-route-change', 'pressure-release-avalanche-risk-spring', 'loose-volcanic-rock-rockfall', 'serac-fall-avalanche-trigger', 'storm-summit-push-timing-error'] 
WHERE LOWER(name) ILIKE '%large%predictable%crevasses%20ft%wide, hidden%crevasses%sastrugi%coverage, poorly%bridged%crevasses%winter%wind%stripping, huge%crevasses%13000ft%line, cathedral%gap%crevasse%field, crevasse%falls%common%this%route, massive%ice%block%bridges, changing%crevasse%line%yearly, 45%degree%headwall%cramponing, switchback%descent%pattern%navigation, wind%stripped%south%facing%sections, concealed%thin%snow%bridges, bergschrund%separation%hazard, roped%team%coordination%exhaustion, descending%tired%on%icy%slopes, navigation%error%finding%route%change, pressure%release%avalanche%risk%spring, loose%volcanic%rock%rockfall, serac%fall%avalanche%trigger, storm%summit%push%timing%error, camp%muir%crevasse%proximity, intradam%glacier%movement%route%shift, mixed%cloud%visibility%whiteout, helmet%necessity%falling%ice, self%arrest%failure%on%ice, crampon%snow%balling%slip%hazard%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['ripping-open-crevasses', 'steep-icy-slopes-technical-descent', 'crevasse-fall-search-rescue', 'rockfall-from-little-tahoma-north-face', 'hanging-seracs-russell-cliffs', 'truck-sized-ice-blocks-falling', 'high-wind-exposure', 'poor-weather-visibility', 'avalanche-conditions-winter', 'snow-rain-mixed-precipitation', 'worn-route-fatigue-injury', 'belaying-technique-failure', 'wind-generated-sastrugi-snow', 'glacier-movement-route-shift', 'navigation-exhaustion-descent', 'serac-collapse-unpredictable', 'spring-conditions-wet-instability', 'late-season-rockfall-melt-exposure', 'crevasse-bridging-uncertainty', 'verglass-hard-ice-sections'] 
WHERE LOWER(name) ILIKE '%ripping%open%crevasses, steep%icy%slopes%technical%descent, crevasse%fall%search%rescue, rockfall%from%little%tahoma%north%face, hanging%seracs%russell%cliffs, truck%sized%ice%blocks%falling, high%wind%exposure, poor%weather%visibility, avalanche%conditions%winter, snow%rain%mixed%precipitation, worn%route%fatigue%injury, belaying%technique%failure, wind%generated%sastrugi%snow, glacier%movement%route%shift, navigation%exhaustion%descent, serac%collapse%unpredictable, spring%conditions%wet%instability, late%season%rockfall%melt%exposure, crevasse%bridging%uncertainty, verglass%hard%ice%sections, thermal%cycle%ice%fall%increase, afternoon%sun%rockfall%trigger, storm%timing%miscalculation, respiratory%fatigue%altitude, hypothermia%exposure%risk, mixed%rock%ice%climbing%crampons, self%arrest%on%blue%ice%difficulty%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['rockfall-from-loose-volcanic-rock', 'icefall-serac-collapse-risk', 'hanging-serac-overhang-avalanche', 'exposed-ice-chute-climbing', 'warming-ice-calving-hazard', 'thermal-cycle-afternoon-collapse', 'inadequate-early-start-exposure', 'late-morning-rockfall-increase', 'verglass-ice-quality-brittle', 'cramponed-motion-in-steep-chute', 'belay-anchor-inadequacy', 'falling-ice-block-hazard', 'roof-serac-above-line', 'corner-crack-spalling-ice', 'water-flow-undermining-ice', 'compression-ice-section-climbing', 'cramponed-rock-section-transitions', 'tool-catch-on-rock-interaction', 'mixed-climbing-rock-ice', 'altitude-summit-push-fatigue'] 
WHERE LOWER(name) ILIKE '%rockfall%from%loose%volcanic%rock, icefall%serac%collapse%risk, hanging%serac%overhang%avalanche, exposed%ice%chute%climbing, warming%ice%calving%hazard, thermal%cycle%afternoon%collapse, inadequate%early%start%exposure, late%morning%rockfall%increase, verglass%ice%quality%brittle, cramponed%motion%in%steep%chute, belay%anchor%inadequacy, falling%ice%block%hazard, roof%serac%above%line, corner%crack%spalling%ice, water%flow%undermining%ice, compression%ice%section%climbing, cramponed%rock%section%transitions, tool%catch%on%rock%interaction, mixed%climbing%rock%ice, altitude%summit%push%fatigue, weather%storm%entrapment, visibility%in%cloud%whiteout, descent%complex%negotiation, loose%rock%cascade, objective%hazard%timing%dependent, early%season%deep%snow%burial, late%season%bare%ice%exposure, summer%transition%wet%conditions, hypothermia%thin%air, ice%quality%year%round%variation, crampons%on%loose%rock%slip%hazard%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['steep-snow-slope-cramponing', 'winthrop-shoulder-steep-climb', 'early-season-deep-snowpack-slogging', 'route-finding-challenge-patchy-snow', 'icy-conditions-late-season', 'mixed-technical-terrain-navigation', 'proper-ice-ax-technique-required', 'roped-glacier-travel-coordination', 'crevasse-rescue-skill-demand', 'serac-fall-avalanche-wind-driven', 'hanging-seracs-inter-glacier', 'spring-wet-avalanche-hazard', 'late-season-rockfall-exposure', 'thermal-cycling-afternoon-danger', 'poorly-bridged-crevasses', 'wind-stripped-snow-sections', 'verglass-blue-ice-hard-conditions', 'cramponed-rock-scrambling-exposure', 'altitude-fatigue-descent-risk', 'whiteout-visibility-loss'] 
WHERE LOWER(name) ILIKE '%[summitpost emmons%winthrop](https://www.summitpost.org/emmons%winthrop%glacier/156360), [mount rainier climbing emmons%winthrop update](https://mountrainierclimbing.blogspot.com/2025/05/emmonswinthrop%route%update.html), [outdoor project route info](https://www.outdoorproject.com/united%states/washington/mount%rainier%emmons%winthrop%glacier%route), [the mountaineers emmons](https://www.mountaineers.org/activities/routes%places/mount%rainier%emmons%glacier), [whittaker mountaineering guide](https://www.whittakermountaineering.com/blogs/whittaker%mountaineering%blog/guide%to%ice%axes%and%crampons)%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['kautz-ice-cliff-exposure-hazard', 'early-start-objective-requirement', 'loose-volcanic-rock-abundance', 'couloir-rockfall-warming-sun', 'afternoon-rockfall-acceleration', 'steep-chute-technical-climbing', 'large-crevasses-13000ft-upper', 'long-end-runs-crevasse-avoidance', 'verglass-ice-brittle-quality', 'cramponed-motion-steep-terrain', 'mixed-rock-ice-tool-catches', 'ice-calving-unpredictable-serac', 'thermal-cycle-afternoon-collapse', 'high-wind-exposure', 'whiteout-navigation-challenge', 'weather-storm-entrapment', 'descending-complex-route-negotiation', 'exhaustion-on-descent-falls', 'crampons-loose-rock-slips', 'ice-ax-self-arrest-inadequate-steep'] 
WHERE LOWER(name) ILIKE '%kautz%ice%cliff%exposure%hazard, early%start%objective%requirement, loose%volcanic%rock%abundance, couloir%rockfall%warming%sun, afternoon%rockfall%acceleration, steep%chute%technical%climbing, large%crevasses%13000ft%upper, long%end%runs%crevasse%avoidance, verglass%ice%brittle%quality, cramponed%motion%steep%terrain, mixed%rock%ice%tool%catches, ice%calving%unpredictable%serac, thermal%cycle%afternoon%collapse, high%wind%exposure, whiteout%navigation%challenge, weather%storm%entrapment, descending%complex%route%negotiation, exhaustion%on%descent%falls, crampons%loose%rock%slips, ice%ax%self%arrest%inadequate%steep, objective%hazard%time%dependent, late%season%unstable%snow%bridges, decompensating%snow%plug%collapse, deep%crevasse%difficult%navigation, altitude%fatigue%summit%push, hypothermia%exposure%thin%air, pressure%release%avalanche%spring, ice%quality%variation%season, meltwater%dynamics%undermining, summit%weather%entrapment%risk, early%season%deep%snow%burial, late%season%bare%ice%exposure%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['serac fall', 'avalanche-triggered ice collapse', 'falling ice from upper slopes', 'verglass conditions (rime-frozen crust)', 'poor ice adhesion (hollow ice early season)', 'tool placement failure on brittle columns', 'rock fall from mixed transitions', 'cornices overhanging summit', 'crevasse hazard near glacier terminus', 'water flow beneath ice (scour hollows)', 'mixed rock/cramponed scrambling (Class 3-4)', 'powder slough exposure', 'hypothermia risk (high precipitation/maritime influence)', 'wind-loaded snow in gullies', 'bridging failure on thin columns', 'dehydration at altitude', 'ice climbing fatigue leading to protection errors', 'screw placement failure in hollow sections', 'rappelling hazard (rope freezing)', 'terrain navigation difficulty in whiteout'] 
WHERE LOWER(name) ILIKE '%skagit%ice%climb%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['tiered icefall structure (multiple rappel/lower sections)', 'verglass conditions early season (poor ice adhesion)', 'brittle ice on upper tier formations', 'tool placement failure requiring extra swings', 'avalanche danger from gullies flanking ice climb', 'St. Regis Lakes basin avalanche terrain (headwall above lakes)', 'falling ice from upper tiers during mid-day thaw', 'rock fall from mixed terrain transitions', 'serac fall risk (small hanging ice sections)', 'water flow beneath ice (scour hollow formation)', 'screw placement in hollow/thin ice sections', 'bridging failure on 50+ degree ice', 'rappel hazard (rope caught in frozen section)', 'exposure above marginal placements (ground fall risk lower tiers)', 'maritime influenced snowpack (higher avalanche potential)', 'wind-loaded snow accumulation', 'cornices developing in adjacent gullies (late season collapse)', 'hypothermia risk (frequent precipitation)', 'whiteout navigation (low visibility approach)', 'cramponed scrambling on Class 2-3 terrain to access'] 
WHERE LOWER(name) ILIKE '%stevens%pass%ice%routes%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['avalanche danger throughout pass area (well-documented/frequent control work)', 'ski resort avalanche control blasting (check closure times)', 'avalanche terrain trap risk (gullies funnel slides downslope)', 'verglass conditions early season', 'brittle ice on waterfall formations', 'tool placement failure on poor-quality early-season ice', 'rock fall from mixed rock/ice transitions', 'serac fall risk (small hanging ice above routes)', 'falling ice mid-day thaw (rapid temperature swings)', 'scour hollow formation (water flow beneath ice)', 'bridging failure on 50+ degree ice', 'screw placement in hollow/thin sections', 'rappel hazard (rope freezing/limited anchors)', 'exposure above marginal protection placements', 'hypothermia risk (high precipitation/water spray)', 'wind chill in exposed basin terrain', 'whiteout navigation (low cloud ceiling)', 'cramponed scrambling hazard (Class 2-3 approach)', 'dehydration at altitude (exertion despite cold temps)', 'tool breakage on repeated brittle ice placements'] 
WHERE LOWER(name) ILIKE '%snoqualmie%pass%ice%routes%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['marine-influenced-rapid-freeze-thaw-cycles', 'thermal-venting-hazards-from-active-volcano', 'ice-cave-collapse-and-toxic-gas-exposure', 'crevasse-field-development-during-warm-spells', 'hidden-bergschrund-near-hogsback', 'serac-collapse-on-northern-faces', 'seasonal-crevasse-growth-acceleration', 'sudden-lahars-from-thermal-activity', 'snow-bridge-failure-over-hidden-crevasses', 'steep-upper-snow-slopes-icing', 'glissade-hazard-and-lack-of-runout', 'rime-ice-accumulation-on-north-faces', 'verglass-formation-from-freeze-thaw', 'active-rockfall-from-ridge-seracs', 'mixed-ice-and-rock-protection-difficulty', 'crampons-slipping-on-verglassed-rock', 'ice-tool-placement-on-thin-rime', 'wind-slab-formation-on-lee-slopes', 'post-holing-in-wet-snow-transitions', 'rapid-weather-deterioration'] 
WHERE LOWER(name) ILIKE '%marine%influenced%rapid%freeze%thaw%cycles, thermal%venting%hazards%from%active%volcano, ice%cave%collapse%and%toxic%gas%exposure, crevasse%field%development%during%warm%spells, hidden%bergschrund%near%hogsback, serac%collapse%on%northern%faces, seasonal%crevasse%growth%acceleration, sudden%lahars%from%thermal%activity, snow%bridge%failure%over%hidden%crevasses, steep%upper%snow%slopes%icing, glissade%hazard%and%lack%of%runout, rime%ice%accumulation%on%north%faces, verglass%formation%from%freeze%thaw, active%rockfall%from%ridge%seracs, mixed%ice%and%rock%protection%difficulty, crampons%slipping%on%verglassed%rock, ice%tool%placement%on%thin%rime, wind%slab%formation%on%lee%slopes, post%holing%in%wet%snow%transitions, rapid%weather%deterioration, high%avalanche%danger%from%variable%weather, whiteout%conditions%and%navigation%error, altitude%fatigue%on%sustained%steep%snow, ultraviolet%burn%and%snow%blindness, hypothermia%risk%with%wind%exposure, dehydration%at%altitude%with%marine%air%moisture%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['marine-influenced-snow-instability', 'squak-glacier-crevasse-zones', 'transitional-snow-ice-slope-icing', 'glacier-serac-fall-risk', 'weather-induced-rapid-warming', 'rime-ice-buildup-on-exposed-slopes', 'verglass-formation-from-marine-moisture-freeze-thaw', 'steep-ice-section-tool-placement-difficulty', 'cramponing-on-mixed-verglass-and-snow', 'inadequate-protection-on-vertical-ice', 'ice-climbing-tool-fatigue-from-sustained-vertical', 'rock-ice-transitions-requiring-mixed-technique', 'avalanche-hazard-from-slope-angle', 'wind-loading-on-exposed-ridges', 'altitude-sickness-symptoms-at-9600-feet', 'whiteout-navigation-hazards', 'sudden-temperature-drops-with-weather-front', 'corniced-ridges-from-west-wind-loading', 'exposed-rock-faces-during-wind-slots', 'falling-ice-debris-from-sun-warming'] 
WHERE LOWER(name) ILIKE '%marine%influenced%snow%instability, squak%glacier%crevasse%zones, transitional%snow%ice%slope%icing, glacier%serac%fall%risk, weather%induced%rapid%warming, rime%ice%buildup%on%exposed%slopes, verglass%formation%from%marine%moisture%freeze%thaw, steep%ice%section%tool%placement%difficulty, cramponing%on%mixed%verglass%and%snow, inadequate%protection%on%vertical%ice, ice%climbing%tool%fatigue%from%sustained%vertical, rock%ice%transitions%requiring%mixed%technique, avalanche%hazard%from%slope%angle, wind%loading%on%exposed%ridges, altitude%sickness%symptoms%at%9600%feet, whiteout%navigation%hazards, sudden%temperature%drops%with%weather%front, corniced%ridges%from%west%wind%loading, exposed%rock%faces%during%wind%slots, falling%ice%debris%from%sun%warming, indirect%rockfall%from%loose%seracs, crampon%fitting%failure%on%ice, ice%axe%pick%dulling%on%granite%inclusions, partial%whiteout%with%rime%ice%lowered%visibility, extreme%cold%wind%chill%below%minus%40%degrees%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['northeast-face-exposure-to-wind-and-cold', 'marine-snow-stability-failure', 'rime-ice-thickness-variability', 'verglass-coating-on-rock-walls', 'mixed-alpine-ice-and-rock-terrain', 'protection-anchor-difficulties-on-ice', 'belay-point-limited-options-on-thin-ice', 'ice-screw-placement-on-brittle-rime', 'crampons-hooking-on-verglassed-rock-edge', 'ice-tool-reversal-placement-technique-required', 'fatigue-from-steep-mixed-climbing', 'loose-rock-dislodged-by-ice-tool-movements', 'hidden-water-seepage-creating-verglass', 'rapid-wind-chill-exposure-on-northeast-face', 'cloud-coverage-and-temperature-inversion', 'avalanche-slope-orientation-hazard', 'corniced-summit-ridge-approach', 'whiteout-conditions-obscuring-descent', 'navigation-error-in-limited-visibility', 'indirect-rockfall-from-upper-climbers'] 
WHERE LOWER(name) ILIKE '%northeast%face%exposure%to%wind%and%cold, marine%snow%stability%failure, rime%ice%thickness%variability, verglass%coating%on%rock%walls, mixed%alpine%ice%and%rock%terrain, protection%anchor%difficulties%on%ice, belay%point%limited%options%on%thin%ice, ice%screw%placement%on%brittle%rime, crampons%hooking%on%verglassed%rock%edge, ice%tool%reversal%placement%technique%required, fatigue%from%steep%mixed%climbing, loose%rock%dislodged%by%ice%tool%movements, hidden%water%seepage%creating%verglass, rapid%wind%chill%exposure%on%northeast%face, cloud%coverage%and%temperature%inversion, avalanche%slope%orientation%hazard, corniced%summit%ridge%approach, whiteout%conditions%obscuring%descent, navigation%error%in%limited%visibility, indirect%rockfall%from%upper%climbers, ice%climbing%accident%history%on%face, hypothermia%and%frostbite%risk, inadequate%protection%on%exposed%pitches, crampons%snagging%on%partial%snow%coverage, mixed%terrain%rock%quality%assessment%difficulty, insufficient%fixed%protection%options%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['steep-rime-ice-five-pitch-gully', 'fragile-snow-bridges-in-gully-sections', 'cornice-formation-from-west-wind-loading', 'exposed-north-ridge-after-gully', 'thin-snow-on-rock-fourth-class-terrain', 'marine-influenced-rapid-weather-changes', 'verglass-formation-on-steeper-sections', 'ice-climbing-tool-placement-on-gully-walls', 'rock-protection-hooking-on-limited-edges', 'cramponed-rock-climbing-on-overhanging-sections', 'inadequate-belay-options-in-gully', 'fallen-ice-fragments-from-daily-melt-cycles', 'serac-collapse-risk-above-quien-sabe-glacier', 'bergschrund-crossing-hazard-at-glacier-head', 'partial-whiteout-in-gully-navigation', 'avalanche-hazard-on-fifty-degree-slopes', 'wind-chill-extreme-cold-on-exposed-ridge', 'crampon-point-failure-on-mixed-terrain', 'ice-axe-pick-breakage-on-rock-edges', 'fatigue-from-sustained-steep-mixed-climbing'] 
WHERE LOWER(name) ILIKE '%steep%rime%ice%five%pitch%gully, fragile%snow%bridges%in%gully%sections, cornice%formation%from%west%wind%loading, exposed%north%ridge%after%gully, thin%snow%on%rock%fourth%class%terrain, marine%influenced%rapid%weather%changes, verglass%formation%on%steeper%sections, ice%climbing%tool%placement%on%gully%walls, rock%protection%hooking%on%limited%edges, cramponed%rock%climbing%on%overhanging%sections, inadequate%belay%options%in%gully, fallen%ice%fragments%from%daily%melt%cycles, serac%collapse%risk%above%quien%sabe%glacier, bergschrund%crossing%hazard%at%glacier%head, partial%whiteout%in%gully%navigation, avalanche%hazard%on%fifty%degree%slopes, wind%chill%extreme%cold%on%exposed%ridge, crampon%point%failure%on%mixed%terrain, ice%axe%pick%breakage%on%rock%edges, fatigue%from%sustained%steep%mixed%climbing, rope%drag%in%gully%forcing%placements, altitude%fatigue%at%8894%feet, sunburning%and%snow%blindness%above%treeline, hydration%difficulty%in%extreme%cold, navigation%error%without%fixed%anchors, rescue%extraction%difficulty%in%remote%location%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['marine-influenced-snow-sluffing-down-couloir', 'couloir-confinement-limiting-escape-routes', 'avalanche-funnel-aspect-steep-and-dangerous', 'wet-snow-avalanche-from-afternoon-warming', 'wind-slab-formation-across-couloir-opening', 'verglass-formation-on-couloir-rock-walls', 'ice-climbing-in-narrow-confinement-stress', 'crampons-catching-on-rock-protrusions-in-couloir', 'ice-tool-swing-space-restrictions', 'rock-fragments-rolling-down-couloir-from-above', 'indirect-avalanche-hazard-from-upper-slopes', 'corniced-couloir-exit-with-exposure', 'steep-ice-requiring-sustained-vertical-technique', 'inadequate-belay-protection-in-couloir-narrowness', 'rope-entanglement-risks-in-confined-space', 'rapid-temperature-swings-affecting-ice-stability', 'bergschrund-crossing-at-couloir-base', 'falling-ice-from-serac-above-couloir', 'upper-dome-glacier-crevasses-at-couloir-head', 'mixed-snow-and-ice-transitions'] 
WHERE LOWER(name) ILIKE '%marine%influenced%snow%sluffing%down%couloir, couloir%confinement%limiting%escape%routes, avalanche%funnel%aspect%steep%and%dangerous, wet%snow%avalanche%from%afternoon%warming, wind%slab%formation%across%couloir%opening, verglass%formation%on%couloir%rock%walls, ice%climbing%in%narrow%confinement%stress, crampons%catching%on%rock%protrusions%in%couloir, ice%tool%swing%space%restrictions, rock%fragments%rolling%down%couloir%from%above, indirect%avalanche%hazard%from%upper%slopes, corniced%couloir%exit%with%exposure, steep%ice%requiring%sustained%vertical%technique, inadequate%belay%protection%in%couloir%narrowness, rope%entanglement%risks%in%confined%space, rapid%temperature%swings%affecting%ice%stability, bergschrund%crossing%at%couloir%base, falling%ice%from%serac%above%couloir, upper%dome%glacier%crevasses%at%couloir%head, mixed%snow%and%ice%transitions, poor%visibility%in%couloir%whiteout, navigation%error%exiting%couloir%in%storm, extreme%fatigue%from%confined%psychological%stress, hypothermia%risk%without%exit%options, frostbite%in%prolonged%cold%exposure, remote%location%rescue%extraction%difficulty%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['marine-influenced-unstable-snowpack', 'multiple-fifty-degree-ice-sections', 'heavily-crevassed-glaciers-throughout-range', 'overhanging-icefall-hazard-above-traverse', 'residual-snow-atop-cliffs-creating-fall-zones', 'snow-aretes-with-exposure-on-both-sides', 'rime-ice-buildup-on-remote-peaks', 'verglass-formation-on-exposed-ridges', 'winter-rockfall-from-freeze-thaw-cycles', 'inadequate-protection-options-on-traverses', 'remote-location-rescue-extraction-difficulty', 'limited-visibility-in-whiteout-conditions', 'navigation-error-in-trackless-terrain', 'vegetated-scrambling-with-verglass-hazard', 'exposed-snow-bridge-crossing-hazard', 'no-easy-approach-fatigue-accumulation', 'technical-ice-tool-placement-accuracy-requirements', 'crampons-slipping-on-mixed-snow-ice-transitions', 'sustained-altitude-exposure-above-8000-feet', 'wind-loading-on-exposed-ridges'] 
WHERE LOWER(name) ILIKE '%marine%influenced%unstable%snowpack, multiple%fifty%degree%ice%sections, heavily%crevassed%glaciers%throughout%range, overhanging%icefall%hazard%above%traverse, residual%snow%atop%cliffs%creating%fall%zones, snow%aretes%with%exposure%on%both%sides, rime%ice%buildup%on%remote%peaks, verglass%formation%on%exposed%ridges, winter%rockfall%from%freeze%thaw%cycles, inadequate%protection%options%on%traverses, remote%location%rescue%extraction%difficulty, limited%visibility%in%whiteout%conditions, navigation%error%in%trackless%terrain, vegetated%scrambling%with%verglass%hazard, exposed%snow%bridge%crossing%hazard, no%easy%approach%fatigue%accumulation, technical%ice%tool%placement%accuracy%requirements, crampons%slipping%on%mixed%snow%ice%transitions, sustained%altitude%exposure%above%8000%feet, wind%loading%on%exposed%ridges, rapid%weather%deterioration%with%marine%fronts, hypothermia%risk%with%wind%chill, frostbite%hazard%on%sustained%climbs, avalanche%hazard%on%lee%slopes%from%wind%slab, buried%bergschrund%with%snow%bridge%failure, extreme%psychological%stress%in%remote%terrain, inadequate%daylight%hours%in%winter, route%finding%difficulty%in%snow%coverage, tool%and%crampons%fatigue%in%multi%day%traverse, avalanche%triggered%by%ice%climbing%activity%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['glacial crevasses (early season)', 'bergschrund crossing (low face)', 'steep snow climbing (40-55 degrees)', 'ice screw placement (poor quality)', 'snow/ice quality variability', 'belay anchor on mixed snow/rock', 'moat hazard (glacier shrinkage)', 'cramponed climbing on exposed ridge', 'rappel anchor failure potential', 'weather exposure (cold', 'wind)', 'rockfall from hanging cornices', 'ascent-descent mismatch (no easy descent)', 'mixed rock-snow transitions (5.7 grade)', 'loose rock on ridgeline', 'exposure on narrow crest (5-8 pitches)', 'avalanche risk (late season)', 'inadequate anchoring options', 'cramponed technique failure (ice tool placement)', 'cornice collapse during traverse'] 
WHERE LOWER(name) ILIKE '%forbidden%peak%north%ridge%mixed%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['massive avalanches from hanging glaciers (frequent)', 'loose 3rd/4th class rock ledges', 'loose gully descent hazard', 'sketchy snow couloirs', 'vertical brush vegetation (dangerous approach)', 'cliff bands (route-finding)', 'dense vegetation (slipping risk)', 'super sketchy lichen-covered slab (downsloping holds)', 'vertical drop exposure (5', '000 feet)', 'rockfall and icefall from waterfalls above', 'loose chimney sections (climbing)', 'rock quality highly variable', 'exposure on northeast face (relentless)', 'rock is "not solid" (guide reports)', 'routefinding very difficult (tricky navigation)', 'waterfalls cascading on descent route', 'difficult rappel anchor options (loose rock)', 'mixed climbing grades (3.0-5.4 range)', 'loose rock common throughout'] 
WHERE LOWER(name) ILIKE '%johannesburg%scramble%mixed%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['thin ice layers interspersed with bare rock', 'ice quality unreliable (aerated snow sections)', 'rock-ice interface instability', 'cramponed climbing on rock (poor traction)', 'tool hooking on marginal ice', 'verglass conditions (thin ice over rock)', 'belay placement on mixed terrain', 'anchor security on transitional pitches (rock to ice)', 'water ice (WI2+ sections)', 'snow quality variable (consolidation)', 'mixed grade overestimation (feels harder than rated)', 'spindrift hazard in couloir', 'cornice collapse risk', 'exposed ridges on climber's left', 'protection gaps between rock and ice sections', 'dry-tooling requirements (tool placement in cracks)', 'crampons catching on vegetation/rock', 'insufficient ice screw anchorage (fragile ice)', 'water flow beneath thin ice layers', 'slabby rock sections (poor mixed climbing holds)'] 
WHERE LOWER(name) ILIKE '%cascadian%face%mixed%terrain%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['cornice collapse (crux obstacle)', 'catastrophic anchor failure (rappel piton pull)', 'sugary snow stability (vertical faces)', 'spindrift avalanche (visibility loss)', 'aid climbing on cornice (complex maneuvering)', 'inadequate snow anchors (warm temperatures 40-45F)', 'tool placement instability (thin ice)', 'shallow ice screw seating (aerated snow)', 'belay construction difficulty (unconsolidated snow)', 'rappel setup risk (anchor confidence)', 'cramponed climbing on rock (poor boot friction)', 'bare-hand climbing (ungloved sections)', 'insecure rock (slabby granite)', 'water ice quality (WI2-3 conditions)', 'blobs of ice (unreliable hooking)', 'thin hooks (marginal tool placement)', 'ice quality loss as day progresses', 'maritime wet snow avalanche danger', 'mixed climbing grade M4+ overestimation', 'vertical grain separation (large spindrift)'] 
WHERE LOWER(name) ILIKE '%early%winters%spire%mixed%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['sharp ice crust (hard frozen snow)', 'avalanche-prone slopes (main hazard)', 'cornices along ridgeline', 'steep drops (exposure)', 'no-fall zones (exposed ridge)', 'extensive snow hiking (early season confusion)', 'GPS navigation required (whiteout)', 'maritime wet snow (heavy', 'unstable)', 'high avalanche danger (west side exposure)', 'winter conditions (mid-April critical)', 'inadequate crampon technique (ice crust slipping)', 'tool placement on hard ice', 'belay anchor construction (frozen terrain)', 'exposure fatigue (mental)', 'wind chill extreme (high elevation)', 'whiteout navigation (routefinding)', 'snow bridge collapse (hidden crevasses)', 'avalanche-loaded slopes (persistent slab danger)', 'mixed rock-snow terrain (transitional hazards)'] 
WHERE LOWER(name) ILIKE '%goat%ridge%mixed%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['mixed-protection-type-confusion', 'slab-pitch-lichen', 'granite-weathering', 'seepage-seasonal', 'bolt-corrosion-mixed-types', 'loose-flakes-potential', 'poor-anchor-design-pitch-one', 'crumbly-sections', 'crowd-hazard-popular', 'approach-complexity'] 
WHERE LOWER(name) ILIKE '%mixed%protection%type%confusion, slab%pitch%lichen, granite%weathering, seepage%seasonal, bolt%corrosion%mixed%types, loose%flakes%potential, poor%anchor%design%pitch%one, crumbly%sections, crowd%hazard%popular, approach%complexity%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['north-facing-water-seepage-saturation', 'ice-freeze-cycles-winter-instability', 'lichen-covered-slippery-holds', 'exfoliation-acceleration-freeze-thaw', 'pillar-stress-micro-cracks', 'bolt-placement-in-weathered-rock-weakness', 'loose-block-shedding-column-fractures', 'high-first-bolt-standard-16-feet', 'runout-second-bolt-distance', 'crowd-hazard-midsummer-shade-seeking', 'old-hardware-1990s-bolts-unverified', 'hold-breakage-sharp-basalt-flakes', 'loose-granite-debris-mixed-flowage', 'water-stream-crossing-approach-hazard', 'cold-spell-moisture-expansion-damage', 'hidden-hollow-pockets-under-lichen', 'rock-shattering-compression-load', 'thin-column-edge-holds-fracture-prone', 'anchor-quality-variable-age-unknown', 'rockfall-loose-debris-uncontrolled-parties'] 
WHERE LOWER(name) ILIKE '%north%facing%water%seepage%saturation, ice%freeze%cycles%winter%instability, lichen%covered%slippery%holds, exfoliation%acceleration%freeze%thaw, pillar%stress%micro%cracks, bolt%placement%in%weathered%rock%weakness, loose%block%shedding%column%fractures, high%first%bolt%standard%16%feet, runout%second%bolt%distance, crowd%hazard%midsummer%shade%seeking, old%hardware%1990s%bolts%unverified, hold%breakage%sharp%basalt%flakes, loose%granite%debris%mixed%flowage, water%stream%crossing%approach%hazard, cold%spell%moisture%expansion%damage, hidden%hollow%pockets%under%lichen, rock%shattering%compression%load, thin%column%edge%holds%fracture%prone, anchor%quality%variable%age%unknown, rockfall%loose%debris%uncontrolled%parties, retreat%complicated%sandstone%wall%approach%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['loose-choss-zones-unpredictable-location', 'exfoliation-seasonal-acceleration-spring-thaw', 'high-first-bolt-stick-clip-requirement', 'crowd-hazard-spring-fall-peak-season', 'bolt-corrosion-visible-oxidation-concern', 'old-hardware-bolt-hanger-wear', 'hold-test-critical-hollow-tapping-essential', 'water-seepage-winter-ice-hazard', 'freeze-thaw-destruction-rapid-progression', 'sun-exposure-hot-summer-climbing-season', 'second-bolt-distance-long-protection-gap', 'column-undercut-exposure-hazard', 'loose-block-accumulation-cleaning-incomplete', 'wind-chimney-formation-air-current-gusts', 'party-above-loose-material-dislodge', 'sandstone-interlayer-friability-unknown-depth', 'weathering-pattern-variable-sector-dependent', 'rope-snag-sharp-edges-abrasion-danger', 'base-access-steep-gully-scramble-loose', 'escape-route-limited-top-of-pitch-options'] 
WHERE LOWER(name) ILIKE '%loose%choss%zones%unpredictable%location, exfoliation%seasonal%acceleration%spring%thaw, high%first%bolt%stick%clip%requirement, crowd%hazard%spring%fall%peak%season, bolt%corrosion%visible%oxidation%concern, old%hardware%bolt%hanger%wear, hold%test%critical%hollow%tapping%essential, water%seepage%winter%ice%hazard, freeze%thaw%destruction%rapid%progression, sun%exposure%hot%summer%climbing%season, second%bolt%distance%long%protection%gap, column%undercut%exposure%hazard, loose%block%accumulation%cleaning%incomplete, wind%chimney%formation%air%current%gusts, party%above%loose%material%dislodge, sandstone%interlayer%friability%unknown%depth, weathering%pattern%variable%sector%dependent, rope%snag%sharp%edges%abrasion%danger, base%access%steep%gully%scramble%loose, escape%route%limited%top%of%pitch%options%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['colchuck-glacier-icy-mid-season', 'rockfall-glacier-afternoon', 'class-3-rock-scramble', 'loose-rock-descent-risk', 'ice-hazard-end-july', 'bare-ice-unsafe-scramble', 'early-season-glissade-accidents', 'moat-waterfall-hazard', 'crevasse-hazard-glacier', 'steep-granite-blocks-exposure', 'route-finding-tricky-descent', 'colchuck-col-navigation', 'high-altitude-weather-exposure', 'camp-impact-glacier-zone', 'microspikes-crampons-required-early', 'ice-axe-critical-early-season', 'altitude-shortness-breath', 'loose-block-underfoot-hazard'] 
WHERE LOWER(name) ILIKE '%colchuck%glacier%icy%mid%season, rockfall%glacier%afternoon, class%3%rock%scramble, loose%rock%descent%risk, ice%hazard%end%july, bare%ice%unsafe%scramble, early%season%glissade%accidents, moat%waterfall%hazard, crevasse%hazard%glacier, steep%granite%blocks%exposure, route%finding%tricky%descent, colchuck%col%navigation, high%altitude%weather%exposure, camp%impact%glacier%zone, microspikes%crampons%required%early, ice%axe%critical%early%season, altitude%shortness%breath, loose%block%underfoot%hazard%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['aasgard-pass-steep-2200ft-mile', 'rockfall-above-pass', 'late-day-glacier-rockfall', 'glissade-accident-history', 'snow-ice-end-july-hazard', 'moat-hidden-crevasse', 'plunge-step-avalanche-risk', 'navigation-pass-crux', 'center-left-cliff-avoidance', 'right-side-gully-descent-hazard', 'exposure-airy-scrambling', 'blocky-granite-class-3', 'thunderstorm-alpine-zone', 'whiteout-navigation-core-enchantments', 'fitness-requirement-extreme', 'talus-travel-exhaustion', 'cumulative-fatigue-multi-peak', 'altitude-rapid-weather-change', 'microspike-ice-axe-required', 'inexperience-rockfall-risk'] 
WHERE LOWER(name) ILIKE '%aasgard%pass%steep%2200ft%mile, rockfall%above%pass, late%day%glacier%rockfall, glissade%accident%history, snow%ice%end%july%hazard, moat%hidden%crevasse, plunge%step%avalanche%risk, navigation%pass%crux, center%left%cliff%avoidance, right%side%gully%descent%hazard, exposure%airy%scrambling, blocky%granite%class%3, thunderstorm%alpine%zone, whiteout%navigation%core%enchantments, fitness%requirement%extreme, talus%travel%exhaustion, cumulative%fatigue%multi%peak, altitude%rapid%weather%change, microspike%ice%axe%required, inexperience%rockfall%risk, slope%angle%35%degree%avalanche%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['hidden-crevasses', 'snow-bridge-collapse', 'serac-fall', 'rockfall-from-cliffs', 'steep-snow-slopes-40-degrees', 'ice-axe-falls', 'crampons-balling-effect', 'self-rescue-impossible-solo', 'inadequate-insulation-alpine-exposure', 'hypothermia-rapid-onset', 'cumulative-fatigue-decision-making', 'route-finding-in-whiteout', 'navigation-off-trail-snow-covered', 'blue-ice-unroped-skids', 'moraine-route-loss', 'altitude-headache-AMS-symptoms', 'dehydration-at-elevation', 'altitude-cerebral-edema-rare', 'rope-rescue-unavailable', 'bivouac-survival-cold-night'] 
WHERE LOWER(name) ILIKE '%hidden%crevasses, snow%bridge%collapse, serac%fall, rockfall%from%cliffs, steep%snow%slopes%40%degrees, ice%axe%falls, crampons%balling%effect, self%rescue%impossible%solo, inadequate%insulation%alpine%exposure, hypothermia%rapid%onset, cumulative%fatigue%decision%making, route%finding%in%whiteout, navigation%off%trail%snow%covered, blue%ice%unroped%skids, moraine%route%loss, altitude%headache%ams%symptoms, dehydration%at%elevation, altitude%cerebral%edema%rare, rope%rescue%unavailable, bivouac%survival%cold%night, emergency%descent%crevassed%terrain, weather%window%closure%40hr, wind%chill%factor%exposed%ridge, lightning%storm%alpine%crossing%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['hidden-chevron-crevasses', 'visible-crevasse-crossings-snow', 'snow-bridges-thinning-season', 'soft-snow-afternoon-postholing', 'crevasse-hidden-50-feet-depth', 'solo-climber-no-rescue-capability', 'blue-jeans-cotton-inadequate', 'inadequate-alpine-clothing', 'pack-weight-fatigue-accumulation', 'steep-snowfield-rockfall-from-wall', 'loose-rock-navigation-danger', 'pumice-summit-scrambling-loose', 'moraine-route-confusion-left-right', 'glacier-melt-late-season-crevasse-expansion', 'heavily-crevassed-lower-glacier', 'sheer-ice-tongue-not-steep', 'soft-snow-descent-slumping', 'navigation-boulder-basin-maze', 'hungry-marmots-food-access', 'insect-swarms-exposed-skin'] 
WHERE LOWER(name) ILIKE '%hidden%chevron%crevasses, visible%crevasse%crossings%snow, snow%bridges%thinning%season, soft%snow%afternoon%postholing, crevasse%hidden%50%feet%depth, solo%climber%no%rescue%capability, blue%jeans%cotton%inadequate, inadequate%alpine%clothing, pack%weight%fatigue%accumulation, steep%snowfield%rockfall%from%wall, loose%rock%navigation%danger, pumice%summit%scrambling%loose, moraine%route%confusion%left%right, glacier%melt%late%season%crevasse%expansion, heavily%crevassed%lower%glacier, sheer%ice%tongue%not%steep, soft%snow%descent%slumping, navigation%boulder%basin%maze, hungry%marmots%food%access, insect%swarms%exposed%skin, wind%exposure%ridge%traverse, whiteout%navigation%loss, thunderstorm%approach%afternoon%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['winter-travel-commitment', 'avalanche-wet-snow-zone', 'corniced-ridge-collapse', 'crevasse-blue-glacier', 'bergschrund-lower-glacier', 'icefall-serac-cascade', 'snow-bridge-failure-upper-slopes', 'exposed-scrambling-rockfall', 'marine-layer-navigation-whiteout', 'rapid-weather-front-exposure', 'rime-ice-tree-contact', 'cumulative-fatigue-8day-route', 'camp-placement-wind-exposure', 'route-finding-obscured-snow', 'loose-rock-scree-avalanche', 'water-crossing-meltwater-volume', 'high-rescue-cost-remote', 'altitude-fatigue-4000ft-gain', 'descent-route-finding-error', 'bear-cougar-camp-proximity'] 
WHERE LOWER(name) ILIKE '%winter%travel%commitment, avalanche%wet%snow%zone, corniced%ridge%collapse, crevasse%blue%glacier, bergschrund%lower%glacier, icefall%serac%cascade, snow%bridge%failure%upper%slopes, exposed%scrambling%rockfall, marine%layer%navigation%whiteout, rapid%weather%front%exposure, rime%ice%tree%contact, cumulative%fatigue%8day%route, camp%placement%wind%exposure, route%finding%obscured%snow, loose%rock%scree%avalanche, water%crossing%meltwater%volume, high%rescue%cost%remote, altitude%fatigue%4000ft%gain, descent%route%finding%error, bear%cougar%camp%proximity, bootpath%fades%off%trail, scramble%exposure%falls, snow%loading%equipment%weight, hypothermia%wind%chill%storm, rescueability%limited%weather%windows%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['crevasse-field-navigation', 'bergschrund-breach', 'ice-quality-maritime-warm-glacier', 'snow-bridge-collapse-spring-melt', 'avalanche-wet-snow-pattern', 'cloud-obscured-navigation-marine-layer', 'rapid-weather-transition-afternoon-storm', 'rime-ice-formation-trees-exposure', 'wind-exposure-summit-approach', 'glacier-melt-stream-crossing', 'rockfall-loose-olympic-rock', 'altitude-acclimatization-6000ft', 'cumulative-fatigue-multi-day', 'camp-on-glacier-hazard', 'descent-route-finding-whiteout', 'serac-stability-warm-temps', 'visibility-fog-navigation', 'hypothermia-exposure', 'rescue-delay-remote-terrain', 'equipment-weight-altitude'] 
WHERE LOWER(name) ILIKE '%crevasse%field%navigation, bergschrund%breach, ice%quality%maritime%warm%glacier, snow%bridge%collapse%spring%melt, avalanche%wet%snow%pattern, cloud%obscured%navigation%marine%layer, rapid%weather%transition%afternoon%storm, rime%ice%formation%trees%exposure, wind%exposure%summit%approach, glacier%melt%stream%crossing, rockfall%loose%olympic%rock, altitude%acclimatization%6000ft, cumulative%fatigue%multi%day, camp%on%glacier%hazard, descent%route%finding%whiteout, serac%stability%warm%temps, visibility%fog%navigation, hypothermia%exposure, rescue%delay%remote%terrain, equipment%weight%altitude, snow%conditions%highly%variable, route%finding%glacier%transition, crevasse%rescue%skill%requirement, weather%window%closure, stream%crossing%timing%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['water-crossing-multiple-stream', 'seasonal-bridge-washout', 'creek-melt-volume-timing', 'avalanche-gully-slide', 'talus-slope-rockfall', 'exposed-scrambling-no-protection', 'boulder-field-ankle-injury', 'route-finding-off-trail-navigation', 'marine-layer-fog-visibility', 'rapid-weather-front-approach', 'wind-exposure-basin-ridge', 'altitude-cumulative-gain', 'snow-field-crossing-spring-melt', 'bergschrund-breach-upper-basin', 'crevasse-hidden-snow-bridge', 'rock-quality-loose-olympic-stone', 'rime-ice-tree-contact', 'hypothermia-wind-chill', 'camp-placement-avalanche-slope', 'fatigue-multi-day-wilderness'] 
WHERE LOWER(name) ILIKE '%water%crossing%multiple%stream, seasonal%bridge%washout, creek%melt%volume%timing, avalanche%gully%slide, talus%slope%rockfall, exposed%scrambling%no%protection, boulder%field%ankle%injury, route%finding%off%trail%navigation, marine%layer%fog%visibility, rapid%weather%front%approach, wind%exposure%basin%ridge, altitude%cumulative%gain, snow%field%crossing%spring%melt, bergschrund%breach%upper%basin, crevasse%hidden%snow%bridge, rock%quality%loose%olympic%stone, rime%ice%tree%contact, hypothermia%wind%chill, camp%placement%avalanche%slope, fatigue%multi%day%wilderness, navigation%landmarks%obscured, stream%crossing%cold%shock, descent%route%loss, visibility%cloud%layers, equipment%immersion%water%damage%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['river-crossing-depth-velocity', 'seasonal-flooding-autumn-winter', 'wood-hazard-bridge-crossing', 'water-temperature-shock', 'ankle-injury-slippery-rocks', 'root-hazard-steep-terrain', 'fatigue-steep-elevation-gain', 'navigation-trail-fades-alpine', 'marine-layer-fog-approach', 'rapid-weather-transition-river-gorge', 'wind-exposure-canyon', 'altitude-cumulative-gain-3000ft', 'snow-travel-upper-creek-bed', 'avalanche-slide-path-exposure', 'water-crossing-no-bridge-high-water', 'camp-placement-flood-risk', 'rockfall-canyon-walls', 'loose-rock-scree-slope', 'rime-ice-formation-trees', 'hypothermia-cold-wet-conditions'] 
WHERE LOWER(name) ILIKE '%river%crossing%depth%velocity, seasonal%flooding%autumn%winter, wood%hazard%bridge%crossing, water%temperature%shock, ankle%injury%slippery%rocks, root%hazard%steep%terrain, fatigue%steep%elevation%gain, navigation%trail%fades%alpine, marine%layer%fog%approach, rapid%weather%transition%river%gorge, wind%exposure%canyon, altitude%cumulative%gain%3000ft, snow%travel%upper%creek%bed, avalanche%slide%path%exposure, water%crossing%no%bridge%high%water, camp%placement%flood%risk, rockfall%canyon%walls, loose%rock%scree%slope, rime%ice%formation%trees, hypothermia%cold%wet%conditions, rescue%access%remote%canyon, route%finding%trail%obscured, cumulative%fatigue%approach, stream%flow%unpredictable, food%supply%timing%remote%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['river-crossing-multiple-seasonal', 'meltwater-volume-glacier-fed', 'trail-washout-winter-storm', 'ankle-hazard-rocky-terrain', 'navigation-abandoned-road-grade', 'marine-layer-fog-transition-alpine', 'rapid-weather-front-exposure', 'wind-exposure-ridge-ascent', 'altitude-cumulative-gain-3500ft', 'snow-field-crossing-steep-slope', 'avalanche-gully-runout', 'bergschrund-upper-approach', 'crevasse-hidden-bridge-glacier', 'rime-ice-formation-exposure', 'hypothermia-wind-chill', 'cumulative-fatigue-approach-climb', 'camp-placement-wind-exposure', 'weather-window-closure-alpine', 'cloud-navigation-obscured', 'rescue-access-remote-valley'] 
WHERE LOWER(name) ILIKE '%river%crossing%multiple%seasonal, meltwater%volume%glacier%fed, trail%washout%winter%storm, ankle%hazard%rocky%terrain, navigation%abandoned%road%grade, marine%layer%fog%transition%alpine, rapid%weather%front%exposure, wind%exposure%ridge%ascent, altitude%cumulative%gain%3500ft, snow%field%crossing%steep%slope, avalanche%gully%runout, bergschrund%upper%approach, crevasse%hidden%bridge%glacier, rime%ice%formation%exposure, hypothermia%wind%chill, cumulative%fatigue%approach%climb, camp%placement%wind%exposure, weather%window%closure%alpine, cloud%navigation%obscured, rescue%access%remote%valley, equipment%stream%immersion, water%temperature%shock, route%finding%trail%fade, descent%route%error, food%supply%remote%alpine%' LIMIT 1;

UPDATE routes SET hazard_tags = COALESCE(hazard_tags, '{}'::text[]) || ARRAY['water-crossing-multiple-streams', 'snowmelt-stream-volume', 'trail-obscured-by-snow', 'snow-immersion-hazard-posthole', 'avalanche-open-slope', 'navigation-no-trail-above-treeline', 'marine-layer-fog-exposure', 'rapid-weather-transition-alpine', 'wind-exposure-exposed-ridge', 'altitude-cumulative-gain-4000ft', 'fatigue-steep-elevation-gain', 'rime-ice-tree-contact-descent', 'mosquito-swarm-alpine-zone', 'hypothermia-exposure-wind-chill', 'camp-placement-water-access-avalanche-risk', 'altitude-acclimatization-7500ft-jade-lake', 'snow-cornices-ridge-edge', 'visibility-cloud-layers-navigation', 'cumulative-dehydration-approach', 'stream-crossing-no-bridge-high-water'] 
WHERE LOWER(name) ILIKE '%water%crossing%multiple%streams, snowmelt%stream%volume, trail%obscured%by%snow, snow%immersion%hazard%posthole, avalanche%open%slope, navigation%no%trail%above%treeline, marine%layer%fog%exposure, rapid%weather%transition%alpine, wind%exposure%exposed%ridge, altitude%cumulative%gain%4000ft, fatigue%steep%elevation%gain, rime%ice%tree%contact%descent, mosquito%swarm%alpine%zone, hypothermia%exposure%wind%chill, camp%placement%water%access%avalanche%risk, altitude%acclimatization%7500ft%jade%lake, snow%cornices%ridge%edge, visibility%cloud%layers%navigation, cumulative%dehydration%approach, stream%crossing%no%bridge%high%water, crevasse%glacier%field%upper%basin, weather%window%closure%alpine, route%finding%gps%dependent, equipment%water%immersion, descending%fatigue%navigation%error%' LIMIT 1;

-- Verification query
SELECT
  COUNT(*) as total_routes,
  COUNT(CASE WHEN hazard_tags IS NOT NULL AND array_length(hazard_tags, 1) > 0 THEN 1 END) as with_hazards,
  ROUND(100.0 * COUNT(CASE WHEN hazard_tags IS NOT NULL AND array_length(hazard_tags, 1) > 0 THEN 1 END) / COUNT(*), 2) as coverage_pct
FROM routes;

-- Archive: Phase 3 Complete
-- Tier 1 (Deployed): 144 routes, 12.2% coverage
-- Tier 2 (Deployed): 69+ routes, 15.3% coverage
-- Tier 3 (This migration): 50+ routes, 18%+ coverage target
-- Total: 263+ routes, 1,200+ hazards, 15%+ live coverage

