-- 0051: rappel_detail round 3 -- gap3 additions, other-discipline expansion, and
-- verification of the 23 gap-fill routes added in migration 0050.
--
-- 1. Gap3 (8 candidates, 1 included): routes where BOTH the `rappels` summary field
--    AND the `pitches` count column were null/wrong -- a category neither of the two
--    prior gap queries (in 0050) caught, since one required pitches>=2 and the other
--    required rappels not null.
--
-- 2. Other-discipline expansion (118 candidates, 17 included): the Rappels section
--    isn't alpine-specific, so this extends the same treatment to WA routes in other
--    disciplines (trad, ice, mixed, rock, mountaineering, scrambling) with genuine
--    multi-pitch, multi-rappel descents -- previously out of scope entirely.
--
-- 3. Verification of the 23 gap-fill routes from 0050 (12 confirmed, 8 unable to
--    verify, 3 corrected): those 23 routes were added via lighter-touch research and
--    had not yet been through the same independent-verification pass the original 118
--    routes got. Notably, this pass caught a fabrication introduced by the *previous*
--    audit itself: a "fatality / waterfall-polished-slabs" caution on the
--    Torment-Forbidden Traverse's final rappel that no source actually supports, now
--    removed.


-- Part 1: gap3 addition -- a route where BOTH `rappels` and `pitches` were null/wrong.

update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "sling/cord around rock horn or block", "notes": "First rappel off the ridge crest dropping down the east side toward Crescent Creek; begins the transition off technical ground since there is no walk-off option from this ridge."}, {"n": 2, "lengthM": 30, "anchor": "sling/cord around rock horn or block", "notes": "Continues down steeper ground/past gendarmes on the east ridge; exact station location isn''t documented in available beta for this rarely-repeated line."}, {"n": 3, "lengthM": 30, "anchor": "sling/cord around rock horn or block", "notes": "Final rappel reaches easier talus/snow terrain that can be downclimbed or walked the rest of the way to the Crescent Creek side."}]'::jsonb, rappel_count_note = 'Route beta explicitly states there is no walk-off descent and parties rappel the east ridge toward Crescent Creek; exact rappel count/lengths/anchors are not documented in available sources for this remote, lightly-traveled Southern Pickets line, so count is estimated from the route''s own pitch count (3) and typical natural (horn/block sling) anchors used on unbolted Pickets ridgelines. Treat lengths as approximate.' where id = 'wa_the_rake_traverse_route';

-- Part 2: other-discipline additions (trad/ice/mixed/rock/mountaineering/scrambling)
-- -- the Rappels section isn't alpine-specific, so this extends the same treatment
-- to non-alpine WA routes with genuine multi-pitch, multi-rappel descents.

update routes set rappel_detail = '[{"n": 1, "lengthM": 25, "anchor": "two-bolt anchor", "notes": "Single-strand rappel from a two-bolt anchor down to a narrow ledge; reached via a short walk across a flat slab from the summit. Carrying double ropes is recommended for this whole descent."}, {"n": 2, "lengthM": 60, "anchor": "large ledge / slung-boulder anchor near top of pitch 2", "notes": "The longest of the three, described as a ''full-rope-length'' rappel on a single 60m rope. Do not try to skip straight to the base in one long rappel — a crack below this anchor is prone to catching and jamming ropes."}, {"n": 3, "lengthM": 30, "anchor": "fixed bolts / natural slung-boulder station (mixed, reinforced with webbing)", "notes": "Final rappel down to the base ledges. Anchors on this shared South Ridge descent mix bolts and natural slung boulders reinforced with webbing, so carry spare tat. From the base, downclimb the class 3-4 gully back to the notch/talus."}]'::jsonb, rappel_count_note = NULL where id = 'wa_east_ridge_9';
update routes set rappel_detail = '[{"n": 1, "lengthM": 40, "anchor": "natural station (tree or horn) below Launch Ledge", "notes": "First of the descent''s rappels down the route itself, not CBR''s usual scree walk-off — The Scoop''s line sits right of that gully. No bolts or fixed gear anywhere on the route by design; equalize a natural anchor yourself if a station looks marginal."}, {"n": 2, "lengthM": 40, "anchor": "natural station (slung tree/horn) in the crack system", "notes": "Watch for rope-snag risk in the corner systems below the crux Scoop pitch."}, {"n": 3, "lengthM": 40, "anchor": "natural station (slung tree/horn)", "notes": "Exact position not documented by available sources; extra slings/cord are worth carrying to build or reinforce a station."}, {"n": 4, "lengthM": 40, "anchor": "natural station (slung tree/horn)", "notes": "Mid-route rappel; anchor spacing depends on where prior parties'' slings sit rather than a fixed, published sequence."}, {"n": 5, "lengthM": 40, "anchor": "natural station (slung tree/horn)", "notes": "Continue lowering through the crack systems below Launch Ledge on the two joined 60m ropes."}, {"n": 6, "lengthM": 40, "anchor": "natural station (slung tree/horn)", "notes": "Loose rock increases in the gully system toward the base; take care if bailing partway rather than finishing the sequence."}, {"n": 7, "lengthM": 30, "anchor": "natural station near the basin", "notes": "Final rappel back to the basin at the base of the formation; length shortened as an estimate since parties would use remaining rope/terrain rather than a full 40m station here."}]'::jsonb, rappel_count_note = 'Source states ''expect on the order of 6-7 rappels'' for this ~900-1,000 ft line and notes exact station spacing isn''t published. Treating 7 as the representative count; per-rappel lengths below are rough estimates (route length / count), not documented individual station distances.' where id = 'wa_the_scoop_2';
update routes set rappel_detail = '[{"n": 1, "lengthM": 15, "anchor": "rappel anchor atop the friction slab (type not specified in source)", "notes": "Downclimb about 10 ft from the summit to reach the anchor, then a short rappel down the friction slab. A single 30m rope is reported sufficient for both rappels on this descent."}, {"n": 2, "lengthM": 20, "anchor": "existing webbing/anchor at the top of the lower chimney", "notes": "After downclimbing/scrambling back to the top of the lower chimney, rappel on reportedly existing webbing/anchors down to the ridge below, then descend class 2 ridge and scree/basin travel back toward Willow Creek."}]'::jsonb, rappel_count_note = NULL where id = 'wa_big_snagtooth_west_ridge';
update routes set rappel_detail = '[{"n": 1, "lengthM": 25, "anchor": "rock station on the west side of the summit block (anchor type not specified in source)", "notes": "First of three single-rope rappels (a single 50m rope is sufficient) down the west side of the summit block toward the ridge notch. This is the only reasonable retreat once on the roped summit block — there is no walk-off partway up."}, {"n": 2, "lengthM": 25, "anchor": "rock station on the summit block (anchor type not specified in source)", "notes": "Second of the three single-rope rappels; route-finding through the ledges on this descent is reported as the crux, slower than the ascent."}, {"n": 3, "lengthM": 25, "anchor": "rock station on the summit block (anchor type not specified in source)", "notes": "Final rappel reaching the ridge notch; from there downclimb the Class 3-4 gully system back to the base of the face and retrace through Dutch Miller Gap."}]'::jsonb, rappel_count_note = NULL where id = 'wa_bears_breast_mountain_southwest_face';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "tree/gear sling", "notes": "First rappel down the upper South Face on a natural tree or gear anchor, joining the shared South Face descent line used by several routes on this side of the peak."}, {"n": 2, "lengthM": 30, "anchor": "tree/gear sling", "notes": "Continues down the face on natural anchors toward easier ground above Pineapple Pass."}, {"n": 3, "lengthM": 30, "anchor": "bolted chain station", "notes": "First of two bolted chain rap stations near Pineapple Pass; a 60m rope is recommended through this section."}, {"n": 4, "lengthM": 30, "anchor": "bolted chain station", "notes": "Second chain station, dropping to the basin/talus below Pineapple Pass; from there hike or ski out toward Source Lake and the Alpental trailhead."}]'::jsonb, rappel_count_note = 'Descends via Guye Peak''s shared South Face rap line; reported as ~4 rappels combining upper tree/gear anchors with two bolted chain stations lower down near Pineapple Pass (confirmed via a Mountaineers.org South Face/Rib trip report describing 4 raps on one rope, or 2 on twin ropes, with sling anchors on trees/boulders). Individual per-station lengths beyond the ~4-rap, single-60m-rope total aren''t separately published, so lengths below are approximate.' where id = 'wa_east_face_variation';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "bolted anchor", "notes": "First rappel off the summit rock band, starting down the West Couloir/Chockstone side."}, {"n": 2, "lengthM": 30, "anchor": "bolted anchor", "notes": "Continues down bolted stations, with some downclimbing worked in between rappels."}, {"n": 3, "lengthM": 30, "anchor": "bolted anchor", "notes": "Passes the steepest, most broken sections of the West Couloir face."}, {"n": 4, "lengthM": 15, "anchor": "fixed piton-and-nut/chockstone anchor", "notes": "Short (~50 ft) free rappel off the ''giant chockstone'' to reach lower-angle terrain near the base; a single 60m rope is sufficient for the whole descent."}]'::jsonb, rappel_count_note = 'The safer, standard descent uses the bolted West Couloir/Chockstone Route line; most sources cite about 4 rappels (a SummitPost description notes up to 5 depending on conditions/rope count, including a short rappel off the ''giant chockstone''). Do not descend the unequipped east side of the couloir itself — the May 2025 fatal accident on this route happened when a party improvised anchors on that unbolted side instead of using this line.' where id = 'wa_early_winter_couloir';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "tree/gear sling", "notes": "From the summit area, first rappel down the upper South Face on a natural tree or gear anchor."}, {"n": 2, "lengthM": 30, "anchor": "tree/gear sling", "notes": "Continues down the face on natural anchors toward easier ground above Pineapple Pass."}, {"n": 3, "lengthM": 30, "anchor": "bolted chain station", "notes": "First of two bolted chain rap stations near Pineapple Pass; a 60m rope is recommended through this section."}, {"n": 4, "lengthM": 30, "anchor": "bolted chain station", "notes": "Second chain station, dropping to the basin/talus below Pineapple Pass; from there downclimb/traverse back through the basin toward Source Lake."}]'::jsonb, rappel_count_note = 'Descends via the same shared South Face rap line as neighboring routes on this peak (Guye Peak); reported as ~4 rappels combining upper tree/gear anchors with two bolted chain stations near Pineapple Pass lower down, per trip-report beta. Individual per-station lengths beyond the ~4-rap, single-60m-rope total aren''t separately published, so lengths below are approximate.' where id = 'wa_northeast_slabs';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "tree or rock anchor", "notes": "From the sub-summit saddle, first rappel down the steep SW-facing gully/chimney to bypass the wettest or iciest section."}, {"n": 2, "lengthM": 30, "anchor": "tree or rock anchor", "notes": "Second rappel continues down the gully; below this, downclimb or plunge-step the remaining snow-filled gully back to the basin below the east face."}]'::jsonb, rappel_count_note = NULL where id = 'wa_northeast_buttress_3';
update routes set rappel_detail = '[{"n": 1, "lengthM": 15, "anchor": "tree/bush or existing station", "notes": "First rappel off the upper face; loose rock throughout this descent."}, {"n": 2, "lengthM": 10, "anchor": "tree/bush or existing station", "notes": "Continues down exposed terrain; route-finding can be difficult here."}, {"n": 3, "lengthM": 15, "anchor": "tree/bush or existing station", "notes": "Bushes and small trees are generally more reliable anchors than pitons or chocks in this rock."}, {"n": 4, "lengthM": 10, "anchor": "tree/bush or existing station", "notes": "Further down the face; carry extra webbing and rap rings to back up old slings."}, {"n": 5, "lengthM": 15, "anchor": "tree/bush or existing station", "notes": "Final rappel reaching easier terrain above the approach gully toward Lake Serene; allow about 5 hours for the full descent."}]'::jsonb, rappel_count_note = 'Reported as 4-5 rappels of roughly 30-50 ft each on existing (sometimes old) anchors; exact station-by-station beta beyond the total count and length range isn''t published — inspect and back up any worn anchors with extra webbing/rap rings.' where id = 'wa_north_face_6';
update routes set rappel_detail = '[{"n": 1, "lengthM": 60, "anchor": "bolted chain station", "notes": "From chain anchors at the top of the North Face, the first of three single-rope rappels back toward the notch."}, {"n": 2, "lengthM": 55, "anchor": "bolted chain station (or flake-and-tree ~30 ft below)", "notes": "Goes over a sharp lip onto vertical face; a 50m rope only just barely reaches this station, so a 60m rope is strongly preferred."}, {"n": 3, "lengthM": 30, "anchor": "bolted chain station", "notes": "Lands on downclimbable low-5th/4th-class terrain just above the high notch where the route began."}]'::jsonb, rappel_count_note = 'Can also be done as 2 x 50m double-rope rappels; the sequence below is the more common 3 x 60m single-rope version.' where id = 'wa_kangaroo_temple_north_face';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "Natural anchor (rock horn/chockstone or picket, condition-dependent)", "notes": "First rappel off the upper ridge/east face exit, often over verglas or hard snow/ice near the top. Anchors here are reported as marginal — back up or extend as needed."}, {"n": 2, "lengthM": 30, "anchor": "Natural rock anchor", "notes": "Second rappel through a steeper, narrower section lower on the ridge/face; exact location shifts year to year with ice and rockfall conditions."}, {"n": 3, "lengthM": 30, "anchor": "Natural rock or picket anchor", "notes": "Third rappel is used in some years/conditions but not always; other parties downclimb this lower section instead, making it the most conditions-dependent of the three."}]'::jsonb, rappel_count_note = 'Source material describes this as ''variable; several rappels (2-3+) commonly used descending the upper ridge/east face, backed up where anchors are marginal'' without exact locations, lengths, or anchor specifics per rappel. Web research to firm this up was inconclusive (search budget exhausted, no usable trip-report results returned). The breakdown below is a representative reconstruction using 30m as a typical single-rope-length rappel and should be treated as approximate, not confirmed beta — count and locations can vary by season/ice conditions.' where id = 'wa_johannesburg_mountain_cj_couloir';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "Natural rock anchor (sling on horn/chockstone) near the cannonhole", "notes": "Bypasses the exposed Class 4 downclimb from the summit horn through the ''cannonhole'' feature."}, {"n": 2, "lengthM": 30, "anchor": "Natural gear anchor (cams/nuts) in the gully/chimney", "notes": "Descends the loose rock gully/chimney system below the cannonhole; rockfall-prone, so parties should descend one at a time."}, {"n": 3, "lengthM": 30, "anchor": "Natural rock anchor near the notch", "notes": "Final rappel beneath the flying buttress to regain the notch at the head of the Redoubt Glacier, after which the party ropes up again for the glacier descent."}]'::jsonb, rappel_count_note = 'Source data states ''3 x 30m rappels'' explicitly, but descent_text only names the general terrain (summit horn/cannonhole, loose gully/chimney, area beneath the flying buttress near the glacier-head notch) without per-rappel anchor detail. Web research to confirm specifics was inconclusive (search budget exhausted). Anchors below are inferred as natural gear typical of this North Cascades terrain, ordered to match the descent narrative — treat as a reasonable reconstruction, not confirmed fixed-station beta.' where id = 'wa_mount_redoubt_south_face';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "natural rock (horn/block) near summit ridge", "notes": "First rappel off the west summit ridge toward the col between Big Four and Hall Peak, mixed with steep downclimbing; exact anchor type not documented in sources."}, {"n": 2, "lengthM": 30, "anchor": "tree", "notes": "First of several tree-anchored rappels descending through the North Face bowl below the col."}, {"n": 3, "lengthM": 30, "anchor": "tree", "notes": "Continue down the bowl; navigation is critical here since parties have mistakenly descended south instead of northwest in poor visibility."}, {"n": 4, "lengthM": 30, "anchor": "tree", "notes": "Final tree rappel to the base of the North Face bowl; length and exact count are approximate since trip reports only say ''several.''"}]'::jsonb, rappel_count_note = 'Source describes ''rappels and steep downclimbing'' to the Big Four-Hall Peak col followed by ''several tree-anchored rappels'' through the North Face bowl, but gives no exact count or measured lengths; this is an approximate reconstruction (col rap + 3 bowl raps), not a verified topo.' where id = 'wa_big_four_mountain_spindrift_couloir';
update routes set rappel_detail = '[{"n": 1, "lengthM": 45, "anchor": "V-thread/Abalakov (\"Zero-Thread\") ice anchor", "notes": "First of 1-3 rappels down the upper ice step (up to 300+ ft of AI3 alpine ice); V-thread anchors leave no gear behind and are not left in place between ascent and descent."}, {"n": 2, "lengthM": 45, "anchor": "V-thread/Abalakov ice anchor", "notes": "Continue down the upper ice step; belay to easier ground climber''s-left/east into the chute rather than committing to team-arrest on exposed ice."}, {"n": 3, "lengthM": 30, "anchor": "V-thread/Abalakov ice anchor", "notes": "First of 1-2 rappels down the lower ice step, same anchor style as above."}, {"n": 4, "lengthM": 30, "anchor": "V-thread/Abalakov ice anchor", "notes": "Final rappel through the lower ice step; after the chute, move fast across the traverse back toward the Rock Step since this stretch sits under the active Kautz Ice Cliff."}]'::jsonb, rappel_count_note = 'NPS route brief and trip reports give a range (2-5 rappels total depending on rope length/number of ropes carried): 1-3 on the upper ice step, 1-2 on the lower ice step. 4 is used here as a representative middle count for a party on a single 60m rope; fewer with two ropes, more if short-pitching.' where id = 'wa_mount_rainier_kautz_glacier';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "natural gear/slung horn or chockstone", "notes": "First of three rappels reversing the technical upper section from the summit; build a natural anchor and expect to leave cord/webbing since there is no fixed hardware on this seldom-climbed route."}, {"n": 2, "lengthM": 30, "anchor": "natural gear/slung horn or chockstone", "notes": "Second rappel continuing down toward the upper gully/notch below the crux 5.8 chimney; a single 60m rope (or doubled 30m) is adequate for each rappel given the pitch lengths involved."}, {"n": 3, "lengthM": 30, "anchor": "natural gear/slung horn or chockstone", "notes": "Final rappel reaching the gully/notch below the crux chimney and the roped 5.5-5.8 pitches climbed on ascent; from here reverse the south ridge or, snow permitting, descend the east-facing couloir."}]'::jsonb, rappel_count_note = 'Explicitly documented as three rappels down to the upper gully/notch below the crux 5.8 chimney; route is very seldom climbed with no bolted/fixed anchors, so natural anchors must be built and cord/webbing left behind.' where id = 'wa_agnes_mountain_west_route';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "Natural (slung horn, chockstone, or gear placement) — no fixed/bolted hardware reported", "notes": "First of two rappels down from near the summit block, through the loose, exposed class 3-4 gully. Rock is rotten and remote (Olympic NP); inspect and back up any tat before trusting it."}, {"n": 2, "lengthM": 30, "anchor": "Natural (slung horn, chockstone, or gear placement) — no fixed/bolted hardware reported", "notes": "Second rappel continues down to the south ridge notch/saddle, after which the remaining class 2-3 terrain is downclimbed toward Mystery Glacier."}]'::jsonb, rappel_count_note = 'A Mountaineers trip report describes two single-rope (60m) rappels from near the summit block down to the south ridge notch/saddle rather than downclimbing the whole loose gully; exact per-rappel lengths aren''t specified in sources, so lengths below are estimated as roughly half the 60m rope.' where id = 'wa_mount_mystery_standard';
update routes set rappel_detail = '[{"n": 1, "lengthM": 10, "anchor": "Natural: slung horn, block, or hand-placed piton in a crack", "notes": "First of two rappels getting down the steep upper step of the southeast ridge/northeast face (the same short low-5th-class face climbed on ascent), roughly a 25-ft drop. No fixed or bolted hardware; build your own anchor from a small rack of stoppers, pitons, and slings."}, {"n": 2, "lengthM": 10, "anchor": "Natural: slung horn, block, or hand-placed piton in a crack", "notes": "Second rappel down a similarly short step below the first. A final downclimb/traverse below regains the sloping ledge leading to the Meany-Noyes col."}]'::jsonb, rappel_count_note = 'Two independent trip reports describe two rappels to descend the summit block''s steep upper step; pitch heights are approximate (~25 ft each) and not precisely documented.' where id = 'wa_mount_meany_standard';

-- Part 3: corrections to the 23 gap-fill routes added in migration 0050, which
-- had not yet received the independent verification pass the original 118 got.
-- 12 confirmed accurate, 8 unable to verify (both need no SQL),
-- 3 had real errors -- including a fabricated caution note this very
-- audit process had itself introduced in migration 0050 (a 'fatality/waterfall-
-- polished-slabs' warning on the Torment-Forbidden Traverse with no supporting source).

update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "slung horn/chockstone (ridge crest)", "notes": "First rappel off the West Ridge crest toward the West Ridge notch"}, {"n": 2, "lengthM": 30, "anchor": "fixed piton-and-nut or slung horn (ridge crest)", "notes": "Continuing down the ridge crest to the top of the descent gully"}, {"n": 3, "lengthM": 30, "anchor": "natural chockstone/horn (descent gully)", "notes": "Into the gully system toward Crescent Creek Basin"}, {"n": 4, "lengthM": 30, "anchor": "natural chockstone/horn (lower gully)", "notes": "Final rappel down to Crescent Creek Basin; do not rappel into the low notch north of the Chopping Block"}]'::jsonb, rappel_count_note = 'Independent trip reports document 3 rappels for this exact West Ridge/Crescent Creek Basin descent; consistent with the sibling North Face entry''s own 3-5 range, 4 is used as a representative middle count rather than the unsupported locked ''5''.' where id = 'wa_mount_terror_southeast_face';
update routes set rappel_detail = '[{"n": 1, "lengthM": 25, "anchor": "natural sling/horn/block", "notes": "West Ridge toward the Notch; length estimated, not documented"}, {"n": 2, "lengthM": 25, "anchor": "natural sling/horn/block", "notes": "West Ridge toward the Notch; length estimated"}, {"n": 3, "lengthM": 25, "anchor": "natural sling/horn/block", "notes": "West Ridge toward the Notch; length estimated"}, {"n": 4, "lengthM": 25, "anchor": "slung horn/chockstone or fixed sling", "notes": "Upper Cat Scratch Gullies; length estimated"}, {"n": 5, "lengthM": 25, "anchor": "slung horn/chockstone or fixed sling", "notes": "Cat Scratch Gullies; length estimated"}, {"n": 6, "lengthM": 25, "anchor": "slung horn/chockstone or fixed sling", "notes": "Cat Scratch Gullies; length estimated"}, {"n": 7, "lengthM": 25, "anchor": "slung horn/chockstone or fixed sling", "notes": "Cat Scratch Gullies; length estimated"}, {"n": 8, "lengthM": 25, "anchor": "slung horn/chockstone or fixed sling", "notes": "Cat Scratch Gullies; length estimated"}, {"n": 9, "lengthM": 25, "anchor": "slung horn/chockstone or fixed sling", "notes": "Cat Scratch Gullies; length estimated"}, {"n": 10, "lengthM": 30, "anchor": "fixed/in-situ anchor (best available near glacier remnant)", "notes": "Final rappel onto the snowfield/glacier remnant below Forbidden''s South Face; exact length not documented in any source found. The previously claimed 55m length and fatality/waterfall-polished-slabs caution could not be independently corroborated and have been removed — use general moat/glacier-edge caution instead."}]'::jsonb, rappel_count_note = 'Corroborated by the SpokAlpine trip report (3 West Ridge rappels + 7 Cat Scratch Gully rappels = 10 total, matching the ''most commonly cited'' figures in the route''s own descent text). Per-rappel lengths are not documented in any source found and are estimated; the previously queued ''fatality/waterfall-polished-slabs'' claim on the final rappel could not be corroborated by any accident database, trip report, or other source and has been removed as unsupported.' where id = 'wa_mount_torment_torment_forbidden_traverse';
update routes set rappel_detail = '[{"n": 1, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Length estimated from 60m rope doubled; exact station not individually documented."}, {"n": 2, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Length estimated, not individually documented."}, {"n": 3, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Length estimated, not individually documented."}, {"n": 4, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Length estimated, not individually documented."}, {"n": 5, "lengthM": 30, "anchor": "fixed titanium knifeblade piton equalized with a stopper", "notes": "Exact position in sequence undocumented; placed here as representative mid-sequence station."}, {"n": 6, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Length estimated, not individually documented."}, {"n": 7, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Length estimated, not individually documented."}, {"n": 8, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Length estimated, not individually documented."}, {"n": 9, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Length estimated, not individually documented."}, {"n": 10, "lengthM": 30, "anchor": "natural anchor (chockstone/horn/sling)", "notes": "Final rappel to glacier; length estimated, not individually documented."}]'::jsonb, rappel_count_note = 'Trip reports vary widely, from as few as 4 to 10+ rappels, depending on exact line taken and season/snow coverage. Beckey''s Cascade Alpine Guide (via independent secondary sourcing) states the descent ''may require ten or more rappels'' via the Beckey-Schmidtke line; 10 is used as the representative count consistent with that documented floor. Per-station lengths are estimated (60m rope doubled, ~30m per rappel), not individually documented.' where id = 'wa_nooksack_tower_south_face';
