-- 0262: put back the REAL place names 0259 removed.
--
-- Owner, 2026-10-07, after 0259 folded 147 areas named only by discipline: "if it actually names a place
-- then keep it". 0259's rule (scripts/lib/generic-area-name.mjs) reads a name made only of generic words
-- as a bucket, and "The Crags" / "The Boulders" can be the real name of a crag cluster or a sector. Every
-- such name 0259 removed was researched (audits/generic-area-names-2026-10-07/real-names.json, evidence per
-- id); the 5 READ as real are restored here — a dissolved grouping re-created from 0259's rollback
-- snapshot with its sub-areas moved back, a renamed leaf given its real name back — and listed in
-- scripts/data/generic-area-names-exempt.json so check:generic-area-names accepts them.
-- Generated by scripts/oneoff/plan-restore-real-place-names.mjs. Each step asserts its effect.

begin;

create or replace function pg_temp.mk(p_id text, p_name text, p_parent text, p_lat float8, p_lng float8, p_type text, p_region text, p_blurb text) returns void language plpgsql as $f$
begin
  if exists (select 1 from areas where id = p_id) then raise exception '0262: % already exists', p_id; end if;
  insert into areas (id, name, parent_id, area_type, region, lat, lng, blurb) values (p_id, p_name, p_parent, p_type, p_region, p_lat, p_lng, p_blurb);
end $f$;
create or replace function pg_temp.mv_area(p_id text, p_from text, p_to text) returns void language plpgsql as $f$
begin
  update areas set parent_id = p_to where id = p_id and parent_id = p_from;
  if not found then raise exception '0262: % is not under % (re-parent to %)', p_id, p_from, p_to; end if;
end $f$;
create or replace function pg_temp.ren(p_id text, p_from text, p_to text) returns void language plpgsql as $f$
begin
  update areas set name = p_to where id = p_id and name = p_from;
  if not found then raise exception '0262: % is not named "%"', p_id, p_from; end if;
end $f$;

create temp table m_recount on commit drop as
  select distinct a.id from areas a join areas t on a.path @> t.path where t.id in ('co_crags_the', 'id_boulders_the', 'wa_boulders_the', 'ca_the_areas', 'ma_general_the', 'co_co_hwy_7_tributaries', 'region', 'co_castaway_crag', 'co_crosswinds', 'co_enclosures_the', 'co_enos_mills', 'co_grey_slab', 'co_highlander_crag', 'co_lower_great_face', 'co_pandemic_rock', 'co_pinpoint', 'co_rib_rock', 'co_sharksfin', 'co_treasure_island', 'co_upper_great_face_the', 'co_wizard_s_gate', 'co_woodstone_half_half_and_slot_rock', 'co_mid_rib', 'wa_fossil_rock', 'crag', 'ca_main_elsewhere', 'ca_area_five', 'ca_area_four', 'ca_area_one', 'ca_area_three', 'ca_area_two');

do $$ begin
-- An EMPTY database (a Supabase preview) has no catalog; a re-run finds the names already back.
if not exists (select 1 from areas where id = 'colorado') then return; end if;
if exists (select 1 from areas where id = 'co_crags_the' and name = 'The Crags') then raise notice '0262: already applied'; return; end if;
perform pg_temp.mk('co_crags_the', 'The Crags', 'co_co_hwy_7_tributaries', 40.3053808888889, -105.523487777778, 'region', 'Colorado', null);  -- re-created: Crags, The
perform pg_temp.mv_area('co_castaway_crag', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Castaway Crag
perform pg_temp.mv_area('co_crosswinds', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Crosswinds
perform pg_temp.mv_area('co_enclosures_the', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Enclosures, The
perform pg_temp.mv_area('co_enos_mills', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Enos Mills
perform pg_temp.mv_area('co_grey_slab', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Grey Slab
perform pg_temp.mv_area('co_highlander_crag', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Highlander Crag
perform pg_temp.mv_area('co_lower_great_face', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Lower Great Face
perform pg_temp.mv_area('co_pandemic_rock', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Pandemic Rock
perform pg_temp.mv_area('co_pinpoint', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Pinpoint
perform pg_temp.mv_area('co_rib_rock', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Rib Rock
perform pg_temp.mv_area('co_sharksfin', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Sharksfin
perform pg_temp.mv_area('co_treasure_island', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Treasure Island
perform pg_temp.mv_area('co_upper_great_face_the', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Upper Great Face, The
perform pg_temp.mv_area('co_wizard_s_gate', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Wizard's Gate
perform pg_temp.mv_area('co_woodstone_half_half_and_slot_rock', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Woodstone, Half & Half, and Slot Rock
perform pg_temp.mv_area('co_mid_rib', 'co_co_hwy_7_tributaries', 'co_crags_the');  -- Mid Rib
perform pg_temp.ren('id_boulders_the', 'Table Rock Bouldering', 'The Boulders');  -- was "Boulders, The" before 0259
perform pg_temp.mk('wa_boulders_the', 'The Boulders', 'wa_fossil_rock', 46.8271, -122.4254, 'crag', 'Washington', null);  -- re-created: Boulders, The
perform pg_temp.mk('ca_the_areas', 'The Areas', 'ca_main_elsewhere', null, null, 'region', 'California', null);  -- re-created: The Areas
perform pg_temp.mv_area('ca_area_five', 'ca_main_elsewhere', 'ca_the_areas');  -- Area Five
perform pg_temp.mv_area('ca_area_four', 'ca_main_elsewhere', 'ca_the_areas');  -- Area Four
perform pg_temp.mv_area('ca_area_one', 'ca_main_elsewhere', 'ca_the_areas');  -- Area One
perform pg_temp.mv_area('ca_area_three', 'ca_main_elsewhere', 'ca_the_areas');  -- Area Three
perform pg_temp.mv_area('ca_area_two', 'ca_main_elsewhere', 'ca_the_areas');  -- Area Two
perform pg_temp.ren('ma_general_the', 'The General Boulder', 'The General');  -- was "General, The" before 0259
end $$;

do $$ declare k int; begin
  loop
    update areas c set path = p.path || text2ltree(c.id) from areas p
     where c.parent_id = p.id and c.path is distinct from p.path || text2ltree(c.id);
    get diagnostics k = row_count;
    exit when k = 0;
  end loop;
end $$;

insert into m_recount select distinct a.id from areas a join areas t on a.path @> t.path where t.id in ('co_crags_the', 'id_boulders_the', 'wa_boulders_the', 'ca_the_areas', 'ma_general_the', 'co_co_hwy_7_tributaries', 'region', 'co_castaway_crag', 'co_crosswinds', 'co_enclosures_the', 'co_enos_mills', 'co_grey_slab', 'co_highlander_crag', 'co_lower_great_face', 'co_pandemic_rock', 'co_pinpoint', 'co_rib_rock', 'co_sharksfin', 'co_treasure_island', 'co_upper_great_face_the', 'co_wizard_s_gate', 'co_woodstone_half_half_and_slot_rock', 'co_mid_rib', 'wa_fossil_rock', 'crag', 'ca_main_elsewhere', 'ca_area_five', 'ca_area_four', 'ca_area_one', 'ca_area_three', 'ca_area_two');
update areas set route_count = (
  select count(*) from routes r join areas a2 on a2.id = r.area_id where a2.path <@ areas.path
) where id in (select id from m_recount);

commit;
